pkgname: 'mocks'

packages:
  github.com/moroz/homeosapiens-go/services:
    interfaces:
      StripeService:
        config:
          dir: services/mocks
          filename: "mock_stripe_service.go"
  github.com/moroz/homeosapiens-go/internal/mailers:
    interfaces:
      Mailer:
        config:
          dir: services/mocks
          filename: "mock_mailer.go"
      OrderMailer:
        config:
          dir: services/mocks
          filename: "mock_order_mailer.go"
      UserMailer:
        config:
          dir: services/mocks
          filename: "mock_user_mailer.go"
