[tools]
age = "latest"
"aqua:axllent/mailpit" = "latest"
caddy = "latest"
go = "1.27"
"go:github.com/air-verse/air" = "latest"
"go:github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen" = "latest"
"go:github.com/pressly/goose/v3/cmd/goose" = "latest"
"go:github.com/riverqueue/river/cmd/river" = "latest"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"
"go:github.com/vektra/mockery/v3" = "v3.7.0"
jq = "latest"
node = "latest"
overmind = "latest"
"pipx:ansible" = "latest"
pnpm = "latest"
prettier = "latest"
python = "latest"
sops = "latest"
stripe = "latest"
uv = "latest"
xh = "latest"

[settings.age]
key_file = "~/.ssh/id_ed25519"

[env]
PGDATABASE = "homeosapiens_dev"
PGUSER = "postgres"
PGPASSWORD = "postgres"
PGHOST = "localhost"
DATABASE_URL = "postgres://postgres:postgres@localhost:5432/{{ env.PGDATABASE }}?options=-c%20TimeZone%3DUTC"
GOOSE_DBSTRING = "{{ env.DATABASE_URL }}"
GOOSE_DRIVER = "postgres"
GOOSE_MIGRATION_DIR = "db/migrations"
SECRET_KEY_BASE = "YhTVeJ58o+vuYEvASxp68UMydUhvMsAOQZkCmlEeAE/IVJ/WkpjXS0+spVyWttR0ZMs0aKbbx+jkqV7oD9Lp+w=="
TEST_DATABASE = "homeosapiens_test"
TEST_DATABASE_URL = "postgres://{{ env.PGUSER }}:{{ env.PGPASSWORD }}@{{ env.PGHOST }}:5432/{{ env.TEST_DATABASE }}?options=-c%20TimeZone%3DUTC"
STRIPE_SECRET_KEY = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHNHcTlDdyA0YzJvVU5NelJndEh4VWM2MndmN0d1bnBVbWZQcnVDckdwWkxhZDlodmxRCldHWmU3L3A5NXg4QXhtTHhxN1JIb2JKdHNabVdSUnh1ZW9Vc2Znb2J5OTgKLT4gc3NoLXJzYSBzZittVncKbC9HZ1VJa1o3bGZwc0szU2lZYlk2Mm1UZXZaNGw2REVsbS84YkNCRkZWdzRLSTVSTnRqUzkyK3EvR0tJK0t5UQo3a01td0RrckhzSVBtOGU4cEI4TTdtUFJmbDk5UmxhRXB4eG04cnVtWGd6SDlhNm4wbmc1Wis4V0haZEM1SkZ5CjJVc0ZKZSt4MWxGbDVSL3ZtdVhpbFIvZmZxZkVQM3NXN3NRbHhBWjZQSVlWUG9NRnhDR3QxTHZlUjArUkIzUi8KZGQyajFKVmt6ampkVkRleVVRaDJaZzJGS2NJVHBHKzZwckV2Y2VhU0VWaytmSVgzOUhEdHM0a0hsQitTQVd4UApEL3R1SzBjS3AyNmJONkdud1Zmd2JVVHZuMVd4eTFrRHBzZzZqaTVFZUJBVHZJRURpTjRWcG5lZzlYN3BYVEJRCmdGSWFXQkhSQ1JMM0loVWVjVjVLQUEKLT4gYzk0LWdyZWFzZSBmCkdBbGJtT0MvdnNFbW5SaXluMEpCVlg1dnIzczhjLzdvV2VSd1RzQ09EdEJKYy80ZXpwVUZVY2ZZN2NGM0piWnAKNHVEbklibFY4bWp6anUzRHY1bTYwRGhzZ3puSgotLS0gTzNrN2xLbjRkZmZOZkU5cHFkdUhKeVhGWEM1TE9CeDVabVZaT0tzWmJwQQolV/KDWG015VClfty5iNLP2Z2it2fbC6symVs7WVZPogwTe2ivo66tIFYSrrWiKPXqU3FNxXGyjQUpNP2WgyBi+z5qd0hLoZKR0Jjr/DUbTp8/Wl7ZrusP9+pnr3lkfyo4UNxZ3TgU5X8PzYjo6c6bgad0fjBn1rq7XW+s3r29+OaLK4aypMMXj+AD" }
STRIPE_PUBLISHABLE_KEY = "pk_test_51TFe1mCyj9ryWA1RRFNkwsVRIZbLncoY4rejdPwjd6nPGYgY2qTYJvMvMlnfcfF9gAPjzUvoDf3Gz7CWpvvDi92A00mI4ZMDBT"
PUBLIC_URL = "http://localhost:5000"
PORT = "5000"

STRIPE_LISTEN_TO_EVENTS = "checkout.session.completed"
GOOGLE_CLIENT_ID = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHNHcTlDdyBPaVJNV3dKamJiY25YQlVlZW8zbmlVSW42Zng1cEZVU0ZSeVYwVXhTazBVCnBVeStHVmFzU21ETU5oV2p1S2ltb3lSZlI5dlUwRmd2V3ZnTkYycWhpSzQKLT4gc3NoLXJzYSBzZittVncKVTZOOGVoN0hWZG5zOXFiU0wyKzhVUE5melFjZm81QXdOOThWNm5QRDhoN3p0azJObGlRaG9rN3UwRkJqNDJmNgpNVU5qWVc0U0psd2pqSjd0WXhJQ0kvY1Qxa245V3NGSTc2ZmVrMWtrT1dzR1dDTmdXaWZadldXRnZ4eGVhZEFSCmpQQXg5TVhSc202SDU0OSsrRmtzdmxiM2JiM1hzL2FXaVduZHZtakFFc3NGOWE1TjJtYTV1d3lpNDM2SmhRa0IKYzBySDNMVkxraDNhd0VkV0NCUDRwT2VLbHFMWDErbjdJMFp4dStRYWx3czJycG9RdDdVSGtoR0F6Um5Oald4UApEd0ZjS1FidTNBVGd0Z1h0NVFBc3ZRYmVCenZENkhUeG9oTmVHVGJZbi9EYlQyR1dUcHRIVXFXSTVXZWkwRUxsClVHSDJPblcyT1c2REV5cFpDSGhVTXcKLT4gR00xNyEtZ3JlYXNlIDM8NDhaIFdxImJmdmF+IFgKN3l0ckVLU2pob3JVVmRhSUEwaUZJcDZ0K1lZMU5TaWNWRWovaStuZ2pYMHlleUV1K3RQRmtaRzI2bS9DZDJqYgo2YmtIcGpGdlVrY3VhWmxuSTcxeXNqS3lWK25uZC9jbi9KRFFmMXh5cm5Fako0eGhyV3BrVGdQeENYbnBNcmsKLS0tIFBobTROeGpuNzA3QWp6VjQ5RjZINkZhU2EwRGo3LzMyRkU3Zm9Md2JJQkEKXV2j3m7bMTLI3ib6KknfpZHRXo2Ybwn69LRhVjK/VsagjTtRaGvjcpzQSmjshHcZXV3rKaJ8y7quc4M+sjo7zCK2kcHRMRlAIZRL27n3Xwh2MknMdycqgkWlt9raaq6YHHsZ0sGSZPU" }
GOOGLE_CLIENT_SECRET = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHNHcTlDdyBTR3IxdWQ5REY2NTBYaVBaTWZlQ0NOV1oxSXlPOEEyczVjQ2pCbzE3alZnCjFrcm50Z2ZxTEluSnBxMElqa1FtY2ltQmxHeFQ2bzhGcXZMdVozRlUyVFkKLT4gc3NoLXJzYSBzZittVncKczBlRUlBV01mQ3gxMDVJTzcwbGlESTNYRTQ3MlRPSS9wT1kyU1NWbFNJTFE1YWxTOW1wOW1JQnNPaGFhQ3JvQgpXTDgvNVU3VlFaekhwd2dqd0VtR2NJWFFkWlM2YWhTcnA1MVM4UnlHdEF3Wk9wK0cxcy9zUjRtSWJZalJlVk91Clc4VEt6VVFWWmp5Rm5MSUtSVmphZzRqZjNrTGZNR2plbk5SbW45RE53Mnh6cUFQOTZuMVQ0Yyt4UWc1WWJabWcKTS9LTVRIaTVuWDl3b0VZQ2E1REd2RS9MVEg0c2JXS09uR25yZ3lVOWRmbTUvUHdMcEE5VUpyZ1hpOEhubGNQYgpwMnB4SkdtRFg2UEpmaHRMemJNejR6WDkyczlIQ1hpbEtuVEtKc0d3YVFvck1ldHJ2WjRlNVVWOEhENDZvTlJGCjI5bXpZQjZCL1BZcXNpOEVCcDBqbFEKLT4gXWEtZVwtZ3JlYXNlIClOID1VCk1vUi81emdGNGRuWEpWY1l2RU1UN2lva09uVjJ0VEZOdWlDeHZyVlB1Z1B0T0o1eUtHalNUc3Y5alNTVzdDSEkKSTY0aVIzK1dpaDUwYkxaK2dKcm0zdFlmVnpqcklTeCtGdTgKLS0tIENUQW9iR3FaZVZtaE9aZENvclNFQS9abFVsTUJCNnpoUG5JM0hhUnQ4TFUK8OQKwuGgrJrH0IJuTlPDc+mANUTtDGDk8E7xu9raQpVxg+Frdi7kFMoK/eYRh38OYkhq+B9W9NU8Q/GGCPZI2M6Xnw" }
STRIPE_WEBHOOK_SIGNING_SECRET = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHNHcTlDdyBwY2FGRzdIbFFWdzNYaVRtRVYrUkxvUnArUFZnUGxPaTgzTUlya1R6bW5BClRaQWZKWWJrSFdma2I1NThNd1B3MkpHM0pFUzc3cVEvdnlPSzkrOTRTMmcKLT4gc3NoLXJzYSBzZittVncKc3J4ZGlpelVINnZsNnUvN1pSK3ErS1crdnpRNTA0Vjc5YVFvU2Z4NVYxRVI4aVNiVDJ4bWZuMElQUGdDdmY2WgpTR2pJMS8rcnpVVG5tMXNPZkl4SG9SR0g5V0Vvc3NWUUdVbEJwZVZ1djc5bTFtcFoxdGdWLzFvaWxwWkF5SFpkCnk3TUNUQ2IxTndUY1M5MHIwTUNhbTc3cHdlVVhsdDNBT0xZNGJoTmkwb3pWWnJIYU5oY3hoUEQ5UUhxN1h2enQKQ2sxZGFPU2hrN1NCQm5xUGIrNjlmWTJCYlErcHM1RCtFcHJqWWkwL1FzNHpEc0RiQkNOb1V4Y28vZ3Y1NWtGTAp2TUxNRjdGaGFtZDk1U1d2RVRLcGN5TTVJeVpNZFlhYmZPdUtOYzYwQk5uRzVlNllIQk9sVW1QYkNCeXlEL0hLCkxQY2JHczFFTW9ibkRadFBMdWdQdkEKLT4gYEE7JnYtZ3JlYXNlCk5WZ21zRjdNQUE5cG9tQlRSTFYwYmg2bGRzdHNkU1VuRXJZRWdpOUM2bTRkWDdXYUpKbnZCNm5Jd2t0RU5abXUKOU42N2FtZisxS2tPMzFZY09aWmx4MVRUV0ZKdUZCRng0MmV1Tk5FCi0tLSAxOElDSHdPMHZwcDlHbW5PbUV6UE1CS2N4YnFpdlhYT0NmT2hFdzFBdnZFCgek24o3n4KgLo6d1dn1Qaokj26Tb6NdSaq1cxpay0tEZ60OubLdaBnWcvxavIK/nP2dnbcmEUEpy3S5+dkfy278q0B6+/k" }

[tasks.setup]
depends = ["caddy:permit"]
run = """
#!/usr/bin/env -S bash -euo pipefail

cd assets && pnpm install && cd ..
mise db:setup
"""

[tasks.restart]
run = """
#!/usr/bin/env -S bash -euo pipefail

if [[ -S .overmind.sock ]]; then
  overmind restart air
fi
"""

[tasks."db:seed"]
run = """
#!/usr/bin/env -S bash -euo pipefail

TABLES=(assets products events hosts video_groups video_groups_videos videos product_prices events_hosts video_hosts)

psql $DATABASE_URL -c "truncate $(IFS=,; echo "${TABLES[*]}") cascade;"
psql $DATABASE_URL -f db/seeds/data.sql >/dev/null
(cd db/seeds && go run .)
mise restart
"""

[tasks."db:seed:dump"]
run = """
#!/usr/bin/env -S bash -euo pipefail

TABLES=(assets products events hosts video_groups video_groups_videos videos product_prices events_hosts video_sources video_hosts)

tables_option="$(printf ' -t %s' "${TABLES[@]}")"

pg_dump -Fp $DATABASE_URL --data-only --inserts --no-comments $tables_option -f db/seeds/data.sql
"""

[tasks."db:setup"]
run = """
#!/usr/bin/env -S bash -euo pipefail

createdb $PGDATABASE || true
psql -c "alter database $PGDATABASE set timezone to 'UTC'"
goose up
mise db:seed
"""

[tasks."db:reset"]
run = """
#!/usr/bin/env -S bash -euo pipefail

dropdb $PGDATABASE --force
mise r db:setup
mise restart
"""

[tasks."db:test:prepare"]
run = """
#!/usr/bin/env -S bash -euo pipefail

if [[ ! -n "$TEST_DATABASE" ]]; then
  echo "TEST_DATABASE is not set!"
  exit 1
fi

EXISTS="$(psql -tA postgres -c "select s.exists from (select exists (select from pg_database where datname = '$TEST_DATABASE')) s;")"

export TEST_DATABASE_URL=postgres://$PGUSER:$PGPASSWORD@$PGHOST:5432/$TEST_DATABASE
export GOOSE_DBSTRING=$TEST_DATABASE_URL

if [[ "$EXISTS" = "f" ]]; then
  createdb $TEST_DATABASE
fi

goose up
psql $TEST_DATABASE_URL -c "truncate river_job"
"""

[tasks.test]
depends = ["db:test:prepare"]
run = "env GO_ENV=test go test -v ./..."

[tasks."format.css"]
run = "scripts/format-classes.mjs tmpl/**/*.go"

[tasks."format.json"]
run = """
#!/usr/bin/env -S bash -euo pipefail

for file in i18n/*.json; do
  jq -r . -S $file | sponge $file
done
"""

[tasks."seeds:build"]
description = "Builds the seed program for use in production"
run = """
#!/usr/bin/env -S bash -euo pipefail

cd db/seeds
GOOS=linux GOARCH=amd64 go build .
"""

[tasks."deploy:staging"]
run = "cd scripts/deploy && ansible-playbook -v deploy.yml --limit staging"

[tasks."deploy:prod"]
run = "cd scripts/deploy && ansible-playbook -v deploy.yml --limit prod"

[tasks.check]
run = "go run ."
dir = "scripts/check-locales"

[tasks.watch]
run = "overmind start"
depends = ["caddy:permit"]

[tasks."caddy:permit"]
run = """
#!/usr/bin/env -S bash -euo pipefail

if [[ $(uname) = "Linux" ]]; then
  getcap $(mise which caddy) | grep -q 'cap_net_bind_service' || sudo setcap 'cap_net_bind_service=+ep' $(mise which caddy)
fi
"""

[tasks.gen]
run = """
sqlc generate
go generate ./...
cd admin && pnpm run gen:api
"""
