// Code generated by "stringer -type=FlashLevel -trimprefix=FlashLevel_"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FlashLevel_Info-0]
	_ = x[FlashLevel_Success-1]
	_ = x[FlashLevel_Error-2]
}

const _FlashLevel_name = "InfoSuccessError"

var _FlashLevel_index = [...]uint8{0, 4, 11, 16}

func (i FlashLevel) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_FlashLevel_index)-1 {
		return "FlashLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FlashLevel_name[_FlashLevel_index[idx]:_FlashLevel_index[idx+1]]
}
