/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the currently signed in user */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Optionally filtered by `search`. Because user PII is encrypted at rest, the filter has two paths: an email-shaped term is matched exactly against the `email_hash` blind index (at most one result); any other term is matched as a case-insensitive substring against the decrypted given and family names, scanned in application code (unindexed, O(n)).
         */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List videos */
        get: operations["listVideos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List hosts */
        get: operations["listHosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @example ok */
            status: string;
        };
        /** @description Pagination metadata describing the returned page. */
        Pagination: {
            /**
             * Format: int32
             * @description The 1-based page number that was returned.
             */
            page: number;
            /**
             * Format: int32
             * @description The effective page size after clamping.
             */
            perPage: number;
            /**
             * Format: int64
             * @description Total number of items across all pages.
             */
            total: number;
            /**
             * Format: int32
             * @description Total number of pages given the effective page size.
             */
            totalPages: number;
        };
        PaginatedUsers: {
            data: components["schemas"]["User"][];
            pagination: components["schemas"]["Pagination"];
        };
        PaginatedVideos: {
            data: components["schemas"]["Video"][];
            pagination: components["schemas"]["Pagination"];
        };
        PaginatedEvents: {
            data: components["schemas"]["Event"][];
            pagination: components["schemas"]["Pagination"];
        };
        PaginatedHosts: {
            data: components["schemas"]["Host"][];
            pagination: components["schemas"]["Pagination"];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            givenName: string;
            familyName: string;
            /** @enum {string} */
            role: "Regular" | "Administrator";
            /** @description Locale code, e.g. pl or en */
            preferredLocale: string;
            /** Format: date-time */
            emailConfirmedAt?: string | null;
            /** Format: date-time */
            insertedAt: string;
            /** Format: uri */
            profilePicture?: string;
        };
        Video: {
            /** Format: uuid */
            id: string;
            titlePl: string;
            titleEn: string;
        };
        Event: {
            /** Format: uuid */
            id: string;
            slug: string;
            titlePl: string;
            titleEn: string;
            subtitlePl?: string | null;
            subtitleEn?: string | null;
            eventType: string;
            isVirtual: boolean;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
        };
        Host: {
            /** Format: uuid */
            id: string;
            /** @description i18n message key, e.g. common.hosts.salutation.dr */
            salutation?: string | null;
            givenName: string;
            familyName: string;
            /** @description ISO 3166-1 alpha-2 country code */
            country?: string | null;
        };
    };
    responses: never;
    parameters: {
        /** @description 1-based page number. Values below 1 are treated as 1. */
        PageParam: number;
        /** @description Number of items per page. Clamped to the [1, 100] range. */
        PerPageParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description 1-based page number. Values below 1 are treated as 1. */
                page?: components["parameters"]["PageParam"];
                /** @description Number of items per page. Clamped to the [1, 100] range. */
                perPage?: components["parameters"]["PerPageParam"];
                /** @description Filter term. An email address is matched exactly via the email_hash index; any other value is a case-insensitive substring match on decrypted given/family names. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of users, ordered by insertion time (newest first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUsers"];
                };
            };
        };
    };
    listVideos: {
        parameters: {
            query?: {
                /** @description 1-based page number. Values below 1 are treated as 1. */
                page?: components["parameters"]["PageParam"];
                /** @description Number of items per page. Clamped to the [1, 100] range. */
                perPage?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of videos, ordered by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedVideos"];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query?: {
                /** @description 1-based page number. Values below 1 are treated as 1. */
                page?: components["parameters"]["PageParam"];
                /** @description Number of items per page. Clamped to the [1, 100] range. */
                perPage?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of events, ordered by start time (newest first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedEvents"];
                };
            };
        };
    };
    listHosts: {
        parameters: {
            query?: {
                /** @description 1-based page number. Values below 1 are treated as 1. */
                page?: components["parameters"]["PageParam"];
                /** @description Number of items per page. Clamped to the [1, 100] range. */
                perPage?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of hosts, ordered by name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedHosts"];
                };
            };
        };
    };
}
