/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the currently signed in user */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Optionally filtered by `search`. Because user PII is encrypted at rest, the filter has two paths: an email-shaped term is matched exactly against the `email_hash` blind index (at most one result); any other term is matched as a case-insensitive substring against the decrypted given and family names, scanned in application code (unindexed, O(n)).
         */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List videos */
        get: operations["listVideos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events */
        get: operations["listEvents"];
        put?: never;
        /** Create an event */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single event by primary key */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        /**
         * Delete an event
         * @description Permanently deletes an event and its host associations. Refused with a 409 once anyone has signed up: registrations are the record of who is owed a seat, so a live event is retired by unpublishing it instead. Any product created for the event is left behind, because order line items reference it.
         */
        delete: operations["deleteEvent"];
        options?: never;
        head?: never;
        /** Update an event */
        patch: operations["updateEvent"];
        trace?: never;
    };
    "/events/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark an event as published. */
        post: operations["publishEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take an event off the public listing.
         * @description Clears publishedAt. Always allowed, including for an event with registrations: existing sign-ups keep their record of the event, it just stops being listed and joinable. Unpublishing a draft is a no-op.
         */
        post: operations["unpublishEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}/attendants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users signed up for the event. */
        get: operations["listEventAttendants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List hosts */
        get: operations["listHosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @example ok */
            status: string;
        };
        /** @description Pagination metadata describing the returned page. */
        Pagination: {
            /**
             * Format: int32
             * @description The 1-based page number that was returned.
             */
            page: number;
            /**
             * Format: int32
             * @description The effective page size after clamping.
             */
            perPage: number;
            /**
             * Format: int64
             * @description Total number of items across all pages.
             */
            total: number;
            /**
             * Format: int32
             * @description Total number of pages given the effective page size.
             */
            totalPages: number;
        };
        PaginatedUsers: {
            data: components["schemas"]["User"][];
            pagination: components["schemas"]["Pagination"];
        };
        PaginatedVideos: {
            data: components["schemas"]["Video"][];
            pagination: components["schemas"]["Pagination"];
        };
        PaginatedEvents: {
            data: components["schemas"]["Event"][];
            pagination: components["schemas"]["Pagination"];
        };
        PaginatedHosts: {
            data: components["schemas"]["Host"][];
            pagination: components["schemas"]["Pagination"];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            givenName: string;
            familyName: string;
            /** @enum {string} */
            role: "Regular" | "Administrator";
            /** @description Locale code, e.g. pl or en */
            preferredLocale: string;
            /** Format: date-time */
            emailConfirmedAt?: string | null;
            /** Format: date-time */
            insertedAt: string;
            /** Format: uri */
            profilePicture?: string;
        };
        Video: {
            /** Format: uuid */
            id: string;
            titlePl: string;
            titleEn: string;
        };
        Event: {
            /** Format: uuid */
            id: string;
            slug: string;
            titlePl: string;
            titleEn: string;
            subtitlePl?: string | null;
            subtitleEn?: string | null;
            eventType: string;
            isVirtual: boolean;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** Format: date-time */
            insertedAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            publishedAt?: string;
        };
        EventDetails: components["schemas"]["Event"] & {
            descriptionPl?: string | null;
            descriptionEn?: string | null;
            isFree: boolean;
            /** @description Decimal price string, e.g. "19.99". Null when free. */
            price?: string | null;
            /** @description Currency code. Null when free. */
            currency?: string | null;
            hosts: components["schemas"]["Host"][];
            venueNameEn?: string | null;
            venueNamePl?: string | null;
            venueStreet?: string | null;
            venueCityEn?: string | null;
            venueCityPl?: string | null;
            venuePostalCode?: string | null;
            /** @description ISO 3166-1 alpha-2 country code */
            venueCountryCode?: string | null;
        };
        /** @description Editable fields of an event, used for both create and update. Server-managed fields (id, insertedAt, updatedAt) are ignored. */
        EventInput: {
            slug: string;
            titlePl: string;
            titleEn: string;
            subtitlePl?: string | null;
            subtitleEn?: string | null;
            eventType: string;
            isVirtual: boolean;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            descriptionPl?: string | null;
            descriptionEn?: string | null;
            /** @description Decimal price string, e.g. "19.99". Null when free. A null or zero price makes the event free. */
            price?: string | null;
            /** @description Currency code. Null when free. */
            currency?: string | null;
            /** @description IDs of hosts associated with the event. */
            hostIds: string[];
            venueNameEn?: string | null;
            venueNamePl?: string | null;
            venueStreet?: string | null;
            venueCityEn?: string | null;
            venueCityPl?: string | null;
            venuePostalCode?: string | null;
            /** @description ISO 3166-1 alpha-2 country code */
            venueCountryCode?: string | null;
        };
        /** @description Selective update of an event. Every field is optional: absent fields are left untouched, and fields backed by a nullable column may be cleared by passing an explicit null. */
        PatchEventInput: {
            titleEn?: string;
            titlePl?: string;
            slug?: string;
            subtitleEn?: string | null;
            subtitlePl?: string | null;
            descriptionEn?: string | null;
            descriptionPl?: string | null;
            /** @description Decimal price string, e.g. "19.99". Null when free. */
            price?: string | null;
            /** @description Currency code. Null when free. */
            currency?: string | null;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            /** @description IDs of hosts associated with the event. Replaces the existing set wholesale. */
            hostIds?: string[];
            /** @description Flipping this to false requires the event to end up with a full venue, whether the address comes from this payload or is already stored on the event. */
            isVirtual?: boolean;
            venueNameEn?: string | null;
            venueNamePl?: string | null;
            venueStreet?: string | null;
            venueCityEn?: string | null;
            venueCityPl?: string | null;
            venuePostalCode?: string | null;
            /** @description ISO 3166-1 alpha-2 country code */
            venueCountryCode?: string | null;
        };
        /** @description Map of field name to validation error message(s) for that field. */
        ValidationErrors: {
            errors: {
                [key: string]: string;
            };
        };
        Host: {
            /** Format: uuid */
            id: string;
            /** @description i18n message key, e.g. common.hosts.salutation.dr */
            salutation?: string | null;
            givenName: string;
            familyName: string;
            /** @description ISO 3166-1 alpha-2 country code */
            country?: string | null;
        };
    };
    responses: never;
    parameters: {
        /** @description 1-based page number. Values below 1 are treated as 1. */
        PageParam: number;
        /** @description Number of items per page. Clamped to the [1, 100] range. */
        PerPageParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description 1-based page number. Values below 1 are treated as 1. */
                page?: components["parameters"]["PageParam"];
                /** @description Number of items per page. Clamped to the [1, 100] range. */
                perPage?: components["parameters"]["PerPageParam"];
                /** @description Filter term. An email address is matched exactly via the email_hash index; any other value is a case-insensitive substring match on decrypted given/family names. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of users, ordered by insertion time (newest first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUsers"];
                };
            };
        };
    };
    listVideos: {
        parameters: {
            query?: {
                /** @description 1-based page number. Values below 1 are treated as 1. */
                page?: components["parameters"]["PageParam"];
                /** @description Number of items per page. Clamped to the [1, 100] range. */
                perPage?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of videos, ordered by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedVideos"];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query?: {
                /** @description 1-based page number. Values below 1 are treated as 1. */
                page?: components["parameters"]["PageParam"];
                /** @description Number of items per page. Clamped to the [1, 100] range. */
                perPage?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of events, ordered by start time (newest first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedEvents"];
                };
            };
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventInput"];
            };
        };
        responses: {
            /** @description The created event */
            201: {
                headers: {
                    /** @description URL of the created event. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetails"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrors"];
                };
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event primary key. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested event */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetails"];
                };
            };
            /** @description No event with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event primary key. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Confirms that the event has been deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No event with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The event has registrations and cannot be deleted */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrors"];
                };
            };
        };
    };
    updateEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event primary key. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchEventInput"];
            };
        };
        responses: {
            /** @description The updated event */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetails"];
                };
            };
            /** @description No event with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrors"];
                };
            };
        };
    };
    publishEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event primary key. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Confirms that the event has been successfully published */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No event with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrors"];
                };
            };
        };
    };
    unpublishEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event primary key. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Confirms that the event is no longer published */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No event with that ID. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listEventAttendants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event primary key */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lists all users signed up for the event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No event with that ID. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listHosts: {
        parameters: {
            query?: {
                /** @description 1-based page number. Values below 1 are treated as 1. */
                page?: components["parameters"]["PageParam"];
                /** @description Number of items per page. Clamped to the [1, 100] range. */
                perPage?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of hosts, ordered by name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedHosts"];
                };
            };
        };
    };
}
