//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/moroz/homeosapiens-go/types"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UserRole.
const (
	Administrator UserRole = "Administrator"
	Regular       UserRole = "Regular"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Administrator:
		return true
	case Regular:
		return true
	default:
		return false
	}
}

// Event defines model for Event.
type Event struct {
	EndsAt      time.Time          `json:"endsAt"`
	EventType   string             `json:"eventType"`
	Id          openapi_types.UUID `json:"id"`
	InsertedAt  time.Time          `json:"insertedAt"`
	IsVirtual   bool               `json:"isVirtual"`
	PublishedAt *time.Time         `json:"publishedAt,omitempty"`
	Slug        string             `json:"slug"`
	StartsAt    time.Time          `json:"startsAt"`
	SubtitleEn  *string            `json:"subtitleEn,omitempty"`
	SubtitlePl  *string            `json:"subtitlePl,omitempty"`
	TitleEn     string             `json:"titleEn"`
	TitlePl     string             `json:"titlePl"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

// EventDetails defines model for EventDetails.
type EventDetails struct {
	// Currency Currency code. Null when free.
	Currency      *string            `json:"currency,omitempty"`
	DescriptionEn *string            `json:"descriptionEn,omitempty"`
	DescriptionPl *string            `json:"descriptionPl,omitempty"`
	EndsAt        time.Time          `json:"endsAt"`
	EventType     string             `json:"eventType"`
	Hosts         []Host             `json:"hosts"`
	Id            openapi_types.UUID `json:"id"`
	InsertedAt    time.Time          `json:"insertedAt"`
	IsFree        bool               `json:"isFree"`
	IsVirtual     bool               `json:"isVirtual"`

	// Price Decimal price string, e.g. "19.99". Null when free.
	Price       *string    `json:"price,omitempty"`
	PublishedAt *time.Time `json:"publishedAt,omitempty"`
	Slug        string     `json:"slug"`
	StartsAt    time.Time  `json:"startsAt"`
	SubtitleEn  *string    `json:"subtitleEn,omitempty"`
	SubtitlePl  *string    `json:"subtitlePl,omitempty"`
	TitleEn     string     `json:"titleEn"`
	TitlePl     string     `json:"titlePl"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	VenueCityEn *string    `json:"venueCityEn,omitempty"`
	VenueCityPl *string    `json:"venueCityPl,omitempty"`

	// VenueCountryCode ISO 3166-1 alpha-2 country code
	VenueCountryCode *string `json:"venueCountryCode,omitempty"`
	VenueNameEn      *string `json:"venueNameEn,omitempty"`
	VenueNamePl      *string `json:"venueNamePl,omitempty"`
	VenuePostalCode  *string `json:"venuePostalCode,omitempty"`
	VenueStreet      *string `json:"venueStreet,omitempty"`
}

// EventInput Editable fields of an event, used for both create and update. Server-managed fields (id, insertedAt, updatedAt) are ignored.
type EventInput struct {
	// Currency Currency code. Null when free.
	Currency      *string   `json:"currency,omitempty"`
	DescriptionEn *string   `json:"descriptionEn,omitempty"`
	DescriptionPl *string   `json:"descriptionPl,omitempty"`
	EndsAt        time.Time `json:"endsAt"`
	EventType     string    `json:"eventType"`

	// HostIds IDs of hosts associated with the event.
	HostIds   []openapi_types.UUID `json:"hostIds"`
	IsVirtual bool                 `json:"isVirtual"`

	// Price Decimal price string, e.g. "19.99". Null when free. A null or zero price makes the event free.
	Price       *string   `json:"price,omitempty"`
	Slug        string    `json:"slug"`
	StartsAt    time.Time `json:"startsAt"`
	SubtitleEn  *string   `json:"subtitleEn,omitempty"`
	SubtitlePl  *string   `json:"subtitlePl,omitempty"`
	TitleEn     string    `json:"titleEn"`
	TitlePl     string    `json:"titlePl"`
	VenueCityEn *string   `json:"venueCityEn,omitempty"`
	VenueCityPl *string   `json:"venueCityPl,omitempty"`

	// VenueCountryCode ISO 3166-1 alpha-2 country code
	VenueCountryCode *string `json:"venueCountryCode,omitempty"`
	VenueNameEn      *string `json:"venueNameEn,omitempty"`
	VenueNamePl      *string `json:"venueNamePl,omitempty"`
	VenuePostalCode  *string `json:"venuePostalCode,omitempty"`
	VenueStreet      *string `json:"venueStreet,omitempty"`
}

// Health defines model for Health.
type Health struct {
	// Status Example: ok
	Status string `json:"status"`
}

// Host defines model for Host.
type Host struct {
	// Country ISO 3166-1 alpha-2 country code
	Country    *string            `json:"country,omitempty"`
	FamilyName string             `json:"familyName"`
	GivenName  string             `json:"givenName"`
	Id         openapi_types.UUID `json:"id"`

	// Salutation i18n message key, e.g. common.hosts.salutation.dr
	Salutation *string `json:"salutation,omitempty"`
}

// PaginatedEvents defines model for PaginatedEvents.
type PaginatedEvents struct {
	Data []Event `json:"data"`

	// Pagination Pagination metadata describing the returned page.
	Pagination Pagination `json:"pagination"`
}

// PaginatedHosts defines model for PaginatedHosts.
type PaginatedHosts struct {
	Data []Host `json:"data"`

	// Pagination Pagination metadata describing the returned page.
	Pagination Pagination `json:"pagination"`
}

// PaginatedUsers defines model for PaginatedUsers.
type PaginatedUsers struct {
	Data []User `json:"data"`

	// Pagination Pagination metadata describing the returned page.
	Pagination Pagination `json:"pagination"`
}

// PaginatedVideos defines model for PaginatedVideos.
type PaginatedVideos struct {
	Data []Video `json:"data"`

	// Pagination Pagination metadata describing the returned page.
	Pagination Pagination `json:"pagination"`
}

// Pagination Pagination metadata describing the returned page.
type Pagination struct {
	// Page The 1-based page number that was returned.
	Page int32 `json:"page"`

	// PerPage The effective page size after clamping.
	PerPage int32 `json:"perPage"`

	// Total Total number of items across all pages.
	Total int64 `json:"total"`

	// TotalPages Total number of pages given the effective page size.
	TotalPages int32 `json:"totalPages"`
}

// PatchEventInput Selective update of an event. Every field is optional: absent fields are left untouched, and fields backed by a nullable column may be cleared by passing an explicit null.
type PatchEventInput = types.PatchEventInput

// User defines model for User.
type User struct {
	Email            openapi_types.Email `json:"email"`
	EmailConfirmedAt *time.Time          `json:"emailConfirmedAt,omitempty"`
	FamilyName       string              `json:"familyName"`
	GivenName        string              `json:"givenName"`
	Id               openapi_types.UUID  `json:"id"`
	InsertedAt       time.Time           `json:"insertedAt"`

	// PreferredLocale Locale code, e.g. pl or en
	PreferredLocale string   `json:"preferredLocale"`
	ProfilePicture  *string  `json:"profilePicture,omitempty"`
	Role            UserRole `json:"role"`
}

// UserRole defines model for User.Role.
type UserRole string

// ValidationErrors Map of field name to validation error message(s) for that field.
type ValidationErrors struct {
	Errors map[string]string `json:"errors"`
}

// Video defines model for Video.
type Video struct {
	Id      openapi_types.UUID `json:"id"`
	TitleEn string             `json:"titleEn"`
	TitlePl string             `json:"titlePl"`
}

// PageParam defines model for PageParam.
type PageParam = int32

// PerPageParam defines model for PerPageParam.
type PerPageParam = int32

// ListEventsParams defines parameters for ListEvents.
type ListEventsParams struct {
	// Page 1-based page number. Values below 1 are treated as 1.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of items per page. Clamped to the [1, 100] range.
	PerPage *PerPageParam `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// ListHostsParams defines parameters for ListHosts.
type ListHostsParams struct {
	// Page 1-based page number. Values below 1 are treated as 1.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of items per page. Clamped to the [1, 100] range.
	PerPage *PerPageParam `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Page 1-based page number. Values below 1 are treated as 1.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of items per page. Clamped to the [1, 100] range.
	PerPage *PerPageParam `form:"perPage,omitempty" json:"perPage,omitempty"`

	// Search Filter term. An email address is matched exactly via the email_hash index; any other value is a case-insensitive substring match on decrypted given/family names.
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// ListVideosParams defines parameters for ListVideos.
type ListVideosParams struct {
	// Page 1-based page number. Values below 1 are treated as 1.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of items per page. Clamped to the [1, 100] range.
	PerPage *PerPageParam `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody = EventInput

// UpdateEventJSONRequestBody defines body for UpdateEvent for application/json ContentType.
type UpdateEventJSONRequestBody = PatchEventInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListEvents List events
	// (GET /events)
	ListEvents(w http.ResponseWriter, r *http.Request, params ListEventsParams)
	// CreateEvent Create an event
	// (POST /events)
	CreateEvent(w http.ResponseWriter, r *http.Request)
	// DeleteEvent Delete an event
	// (DELETE /events/{id})
	DeleteEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetEvent Get a single event by primary key
	// (GET /events/{id})
	GetEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateEvent Update an event
	// (PATCH /events/{id})
	UpdateEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// PublishEvent Mark an event as published.
	// (POST /events/{id}/publish)
	PublishEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UnpublishEvent Take an event off the public listing.
	// (POST /events/{id}/unpublish)
	UnpublishEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetHealth Liveness probe
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// ListHosts List hosts
	// (GET /hosts)
	ListHosts(w http.ResponseWriter, r *http.Request, params ListHostsParams)
	// GetSession Get the currently signed in user
	// (GET /session)
	GetSession(w http.ResponseWriter, r *http.Request)
	// ListUsers List users
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams)
	// ListVideos List videos
	// (GET /videos)
	ListVideos(w http.ResponseWriter, r *http.Request, params ListVideosParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListEvents operation middleware
func (siw *ServerInterfaceWrapper) ListEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEventsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "perPage", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "perPage"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateEvent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEvent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteEvent operation middleware
func (siw *ServerInterfaceWrapper) DeleteEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvent operation middleware
func (siw *ServerInterfaceWrapper) GetEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateEvent operation middleware
func (siw *ServerInterfaceWrapper) UpdateEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PublishEvent operation middleware
func (siw *ServerInterfaceWrapper) PublishEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PublishEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnpublishEvent operation middleware
func (siw *ServerInterfaceWrapper) UnpublishEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnpublishEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListHosts operation middleware
func (siw *ServerInterfaceWrapper) ListHosts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListHostsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "perPage", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "perPage"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHosts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "perPage", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "perPage"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "search"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVideos operation middleware
func (siw *ServerInterfaceWrapper) ListVideos(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVideosParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "perPage", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "perPage"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVideos(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/session", wrapper.GetSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users", wrapper.ListUsers)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/videos", wrapper.ListVideos)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/events", wrapper.ListEvents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/events", wrapper.CreateEvent)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/events/{id}", wrapper.DeleteEvent)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/events/{id}", wrapper.GetEvent)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/events/{id}", wrapper.UpdateEvent)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/events/{id}/publish", wrapper.PublishEvent)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/events/{id}/unpublish", wrapper.UnpublishEvent)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/hosts", wrapper.ListHosts)

	return m
}

type ListEventsRequestObject struct {
	Params ListEventsParams
}

type ListEventsResponseObject interface {
	VisitListEventsResponse(w http.ResponseWriter) error
}

type ListEvents200JSONResponse PaginatedEvents

func (response ListEvents200JSONResponse) VisitListEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEventRequestObject struct {
	Body *CreateEventJSONRequestBody
}

type CreateEventResponseObject interface {
	VisitCreateEventResponse(w http.ResponseWriter) error
}

type CreateEvent201ResponseHeaders struct {
	Location *string
}

type CreateEvent201JSONResponse struct {
	Body    EventDetails
	Headers CreateEvent201ResponseHeaders
}

func (response CreateEvent201JSONResponse) VisitCreateEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEvent422JSONResponse ValidationErrors

func (response CreateEvent422JSONResponse) VisitCreateEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteEventRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteEventResponseObject interface {
	VisitDeleteEventResponse(w http.ResponseWriter) error
}

type DeleteEvent204Response struct {
}

func (response DeleteEvent204Response) VisitDeleteEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteEvent404Response struct {
}

func (response DeleteEvent404Response) VisitDeleteEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type DeleteEvent409JSONResponse ValidationErrors

func (response DeleteEvent409JSONResponse) VisitDeleteEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetEventRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetEventResponseObject interface {
	VisitGetEventResponse(w http.ResponseWriter) error
}

type GetEvent200JSONResponse EventDetails

func (response GetEvent200JSONResponse) VisitGetEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetEvent404Response struct {
}

func (response GetEvent404Response) VisitGetEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateEventRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateEventJSONRequestBody
}

type UpdateEventResponseObject interface {
	VisitUpdateEventResponse(w http.ResponseWriter) error
}

type UpdateEvent200JSONResponse EventDetails

func (response UpdateEvent200JSONResponse) VisitUpdateEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateEvent404Response struct {
}

func (response UpdateEvent404Response) VisitUpdateEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateEvent422JSONResponse ValidationErrors

func (response UpdateEvent422JSONResponse) VisitUpdateEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type PublishEventRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type PublishEventResponseObject interface {
	VisitPublishEventResponse(w http.ResponseWriter) error
}

type PublishEvent204Response struct {
}

func (response PublishEvent204Response) VisitPublishEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PublishEvent404Response struct {
}

func (response PublishEvent404Response) VisitPublishEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PublishEvent422JSONResponse ValidationErrors

func (response PublishEvent422JSONResponse) VisitPublishEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type UnpublishEventRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type UnpublishEventResponseObject interface {
	VisitUnpublishEventResponse(w http.ResponseWriter) error
}

type UnpublishEvent204Response struct {
}

func (response UnpublishEvent204Response) VisitUnpublishEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UnpublishEvent404Response struct {
}

func (response UnpublishEvent404Response) VisitUnpublishEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListHostsRequestObject struct {
	Params ListHostsParams
}

type ListHostsResponseObject interface {
	VisitListHostsResponse(w http.ResponseWriter) error
}

type ListHosts200JSONResponse PaginatedHosts

func (response ListHosts200JSONResponse) VisitListHostsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSessionRequestObject struct {
}

type GetSessionResponseObject interface {
	VisitGetSessionResponse(w http.ResponseWriter) error
}

type GetSession200JSONResponse User

func (response GetSession200JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSession401Response struct {
}

func (response GetSession401Response) VisitGetSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ListUsersRequestObject struct {
	Params ListUsersParams
}

type ListUsersResponseObject interface {
	VisitListUsersResponse(w http.ResponseWriter) error
}

type ListUsers200JSONResponse PaginatedUsers

func (response ListUsers200JSONResponse) VisitListUsersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListVideosRequestObject struct {
	Params ListVideosParams
}

type ListVideosResponseObject interface {
	VisitListVideosResponse(w http.ResponseWriter) error
}

type ListVideos200JSONResponse PaginatedVideos

func (response ListVideos200JSONResponse) VisitListVideosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListEvents List events
	// (GET /events)
	ListEvents(ctx context.Context, request ListEventsRequestObject) (ListEventsResponseObject, error)
	// CreateEvent Create an event
	// (POST /events)
	CreateEvent(ctx context.Context, request CreateEventRequestObject) (CreateEventResponseObject, error)
	// DeleteEvent Delete an event
	// (DELETE /events/{id})
	DeleteEvent(ctx context.Context, request DeleteEventRequestObject) (DeleteEventResponseObject, error)
	// GetEvent Get a single event by primary key
	// (GET /events/{id})
	GetEvent(ctx context.Context, request GetEventRequestObject) (GetEventResponseObject, error)
	// UpdateEvent Update an event
	// (PATCH /events/{id})
	UpdateEvent(ctx context.Context, request UpdateEventRequestObject) (UpdateEventResponseObject, error)
	// PublishEvent Mark an event as published.
	// (POST /events/{id}/publish)
	PublishEvent(ctx context.Context, request PublishEventRequestObject) (PublishEventResponseObject, error)
	// UnpublishEvent Take an event off the public listing.
	// (POST /events/{id}/unpublish)
	UnpublishEvent(ctx context.Context, request UnpublishEventRequestObject) (UnpublishEventResponseObject, error)
	// GetHealth Liveness probe
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// ListHosts List hosts
	// (GET /hosts)
	ListHosts(ctx context.Context, request ListHostsRequestObject) (ListHostsResponseObject, error)
	// GetSession Get the currently signed in user
	// (GET /session)
	GetSession(ctx context.Context, request GetSessionRequestObject) (GetSessionResponseObject, error)
	// ListUsers List users
	// (GET /users)
	ListUsers(ctx context.Context, request ListUsersRequestObject) (ListUsersResponseObject, error)
	// ListVideos List videos
	// (GET /videos)
	ListVideos(ctx context.Context, request ListVideosRequestObject) (ListVideosResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListEvents operation middleware
func (sh *strictHandler) ListEvents(w http.ResponseWriter, r *http.Request, params ListEventsParams) {
	var request ListEventsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListEvents(ctx, request.(ListEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListEventsResponseObject); ok {
		if err := validResponse.VisitListEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateEvent operation middleware
func (sh *strictHandler) CreateEvent(w http.ResponseWriter, r *http.Request) {
	var request CreateEventRequestObject

	var body CreateEventJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateEvent(ctx, request.(CreateEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateEventResponseObject); ok {
		if err := validResponse.VisitCreateEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteEvent operation middleware
func (sh *strictHandler) DeleteEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteEventRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteEvent(ctx, request.(DeleteEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteEventResponseObject); ok {
		if err := validResponse.VisitDeleteEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEvent operation middleware
func (sh *strictHandler) GetEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetEventRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEvent(ctx, request.(GetEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEventResponseObject); ok {
		if err := validResponse.VisitGetEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateEvent operation middleware
func (sh *strictHandler) UpdateEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateEventRequestObject

	request.Id = id

	var body UpdateEventJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateEvent(ctx, request.(UpdateEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateEventResponseObject); ok {
		if err := validResponse.VisitUpdateEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PublishEvent operation middleware
func (sh *strictHandler) PublishEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request PublishEventRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PublishEvent(ctx, request.(PublishEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PublishEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PublishEventResponseObject); ok {
		if err := validResponse.VisitPublishEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UnpublishEvent operation middleware
func (sh *strictHandler) UnpublishEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UnpublishEventRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UnpublishEvent(ctx, request.(UnpublishEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UnpublishEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UnpublishEventResponseObject); ok {
		if err := validResponse.VisitUnpublishEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListHosts operation middleware
func (sh *strictHandler) ListHosts(w http.ResponseWriter, r *http.Request, params ListHostsParams) {
	var request ListHostsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListHosts(ctx, request.(ListHostsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListHosts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListHostsResponseObject); ok {
		if err := validResponse.VisitListHostsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSession operation middleware
func (sh *strictHandler) GetSession(w http.ResponseWriter, r *http.Request) {
	var request GetSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSession(ctx, request.(GetSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSessionResponseObject); ok {
		if err := validResponse.VisitGetSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListUsers operation middleware
func (sh *strictHandler) ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams) {
	var request ListUsersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListUsers(ctx, request.(ListUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUsers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListUsersResponseObject); ok {
		if err := validResponse.VisitListUsersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListVideos operation middleware
func (sh *strictHandler) ListVideos(w http.ResponseWriter, r *http.Request, params ListVideosParams) {
	var request ListVideosRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVideos(ctx, request.(ListVideosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVideos")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVideosResponseObject); ok {
		if err := validResponse.VisitListVideosResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FtbcxO58v8qXfP/P4SqiZ0AtXXwecoCu6SKhdRyeQHqpD3T9ohopFlJ42CofPdT3ZIvY0+MA1mWQ/G0",
	"G4/Urb7/uiU+ZYWtG2vIBJ+NPmUNOqwpkJO/znBKZ/wL/1GSL5xqgrImG2XHh2P0VEKDUwLT1mNyA3iN",
	"uiUPY9L2Eo4BHUFwhIFKQA/HgyzPFG/+qyU3z/LMYE3ZKGMaWZ75oqIaI6sJtjpko+M8m1hXY8hGmTLh",
	"3t0sz2plVN3W8jHMG4qfaEouu7rKszNyO479TE4KdgIqUO2hISciDOChxrqhEoKFUBG8Oc7h+OjoHTg0",
	"U7r25JFZ/+HvHvWdHj+k0x8dfUaWqwVVscXjGZkgJnK2IRcUyc9kSn8ivy9ZlRjoMKiaj5WI+uCUmWZX",
	"eUZM5qX8+mn7qyo7lNpWlX1ElPHkApU3Yaz8a+VCi3qN8dhaTWj4c9OOtfLVzWh63U575fABXbiRXnw7",
	"Dipoemx4j2m1xrGmbBRcSzuWn+m9lq+R7v92pnu/tQ0f+gY6ucozR3+1ylGZjd5kYj7R0orP6jTr3rBu",
	"oDX95QsH6xh9/WDvlmew4/dUBD62+OojCqi0OClq/XySjd58yv7f0SQbZf83XKWdYXLyYfTwq3zTxYvW",
	"OTLFfDuaH6YvUNiSBvCs1RouKzIwcSQx+1nDrNHb0/JrO/Y0fmV9TK6Scvh/dmnhifWiw0QGncN5jJ/f",
	"HNE1weNUQdvqeUSFqlGDfIZ4oBxoMB3A2+z4weDBg7fZF2ltRqalhyrM99TZcv2eGovrbWuCmz+0ZY9o",
	"py+ew73jX345PAbUTYWHd6GI68UX9hbiGdZ0EyF4/U2EOLM+oF7IsN+eF8ERhT3WbwZ79JCFw20H5rtF",
	"aJ6apg3bSn1cqsDsYKJIl56rJBqQHJFDy9V+Yh2MbaigkLIOaEqIqWAAL8jNyB3WaHDKSyONA1XmsEod",
	"OSwzxx3BB2pqrKOS3e7HivrbLcxs0tPS9wTCI7GTmBzQe1sowVuXKlQCZISu4JdF9vlsed9OPbtL9y1m",
	"HzgB1ixYBx/J2bS5xgvyK2n2N/QPDxB+ZuLvMRPfEuJaBH0fxHpCqEO13Q/4gKGNncEHrBstuy4+CxTT",
	"tl5ODEi2+CQb/y3+MMFa6fkzabF6fH6qZmSu/bpnC+NRtwHjmTdFUMf/MlCT99zbXtA8Za3C1rU1A0m1",
	"g9X+Qek+L1QfLl/J0RG5zwZnOFWG87qUb79tjhID7g0xF0B7K9E3kU1Syi4SZ6uVm7LJUTq0dkr0ZIGO",
	"v0Kg6zDzPyHPK5+GJ18hD9P4XuR5rUqyXyuQEPk+JOqN+NU3qCkgE4S4YqzMVJCHo9A6kyZe23BVZlhb",
	"dF9WBD2TMggVBrhEv6TKBG806cqXs6depjSZUBHUjCJbrz4S4CSQg0Jj3Sgz/QKOwYaIATf48c8LyZaT",
	"NSyc9R5QazmC3+T3y/11fkfX8mMZ/eeZCg+QlBqB4rYCdkt81DtNXHezNKZczfyiPjrn7He8UFS7+q4X",
	"pNNZY3O03ngN4PGM3Dy2U6A8WNmFegQ49gKGY6PFzZSmSYDWBNsWFZW5tGfp8xiLCyphPAeERa2Cwuq2",
	"NlDjHMYEhSZ0cU2D3rPj8yk+NFoVKsiun23a1zZi8Cc1GotFO/NB+cCK9hTgsrKaPGq6xW6te8bftGqa",
	"mNCUh2BhgtpzahMnX++wggWS3j6eH2HC5hNQnLMVQyVZjADL0pH3DI7Iw8TZOhJvcK4tltzIKc4CjrCc",
	"gw/c7IM13db0n59o/WwUfzaK36hR7NaHPPtwOLWH6Uf+jx9sFoy1NYeqbqyL/Rhy/5dNVaja8aCw9bC2",
	"zn4cVrYm67FRZPzh1A6FpnAWWLl9g1Sj0h33jr/0JUv+8NCaiXL1zluJ76LF+5JbqsbRhJyj8qktUPd4",
	"cfxdPDYlnkamVWT6ydmJ0nSmitA66p7aqb4dzkauZBiUvMn+pGmrkTvMk5Kxig8Og3VrQGNXi7mw5DWt",
	"ZmK3LXZHeX2Y5jVqVQpgfuycdT318A9suB5G3GKwJq4ps+U2IN636LIP/B2ZLQsuli3bSIOWjLAsVQRB",
	"Z50V15XGxbE3NJQI9oon/cpWqOzpeF+Wo/vstz1B2j7tlbj6xPZkXBPIGdSA7DpQoq/GFl0JJ2enC1xJ",
	"pmysMoGrtCc3Y/xHlTIlYz9sQ0UmqCJe4QsVT96z/Q48kVTxITZqGL/VnM9BGbik8dDZNpC7k4OXG3VH",
	"zMJYaMgdLrlaJ39HL2F21qmP0UFUBAmx/xu8NW/NU+XD8sAefMWYF9NcBlbtHxTWBIdFGDGFOWBRUBPg",
	"nAH8uYDi8wTiz0Eu9GH17EE+x65M0K+ZkbYNLWDQObeG5yBgS5aikE2Mz1fdY7QOwz1vW1fQAhBFoD7R",
	"GOBwCROVNR4OBDrmEdv4HBxNY7Tz1xwGg0G6MTGBbcLur+dgaxXYOAl5EWhWkqPGEXcHcffgrVm4UDbK",
	"nnCBgFQhQNIKe0TGtcz56DpHg+PBEfurbchgo7JRdm9wNLgnbXaoJBqGtBxGTWPx41gRjqclp0rlQ5pX",
	"5Z2HJdfcA6+WDFcvOK7yzy9ef/Fx9Y7DyDfW+Bizd4+O4rxS1Cbpo+GORs45fO/jOGD1fGOPGcRyDCex",
	"1425k9hv2klEtz4H60pKbZWASeDaAweGLslzsnM+3JHo921do5snzaX9UkXSBLar3odyBRdneTF1kA+/",
	"2nJ+a+KuQZCrbnriqn61pejj2+W8eEDQo+WXFaUryDLqKcuzirBMozeuYv2Dnld/PmXbhM39g84Tnt1F",
	"Ws5z/+7dW5N2q5j2SLxaAxNUmsoNl3m4uJBN+uCvKUCHn1R5FVWhKfRgmjNyNfKR9BziGr8kJElOBS+N",
	"bSdhcW6byK1wyo33jx6ANQUfYm4NQYUevJoa4j5y1M1n8W2YjNUK60q2yWVlZb5xyaUGPGGQ0oGg1WzR",
	"liqZmKkUTq1Jr4a4pVVceHwgLAdwYubQOFu2RViaOcKLNUIyLIm1LocxFdh6isEKWhlKYywBRsRSKXGS",
	"bgw+Em0tYnAjx21crgvfxik2GFzQfPmmTID88kmZ1P1upPW7Zi/46El/93tGMxHC+4i3Vlphi42JTPKC",
	"kpPP/T4Cz2zakaYbGECl1Q++aVi87Jx9w8VMCQUaY9nMK5E6YRMNuBY2eX8t+53C923lo2+ae1O1WWbf",
	"G/pJxwS/U+B4V2aqF7Ycz9dVGO8JQlFtm+WVzEu/O8vcfineHAnsVY+/rU+khz1f5hHfX0GNrnV9QR2m",
	"2iNdYi9AO4sLfrzq4NuiIO8nLTcgy4e7//sm/wPdxRrw8SvZBtvmX4KPdQfYUKQmdGtUTsIATvQlzuVa",
	"jIFODsoUui0ZwDBAWTIXVXXK2WjtskBNzWHbeLggathAyq3hqKXBcsZE71sfwAfbsO14M/eHjLBMCe+t",
	"MjjWNIBX60gKoXQ4EYyEYOyhbbaBz3LDD+PdcTihrZmS+3Kn7vjTS7xYJRCwk2gboV2IHeQaVjyrWj7n",
	"uQ5+pAc/f2OSTxx6AucFuZkqZIATDzrfalhnZMh7Rt1jSiItHnZcOxyITz9+tNlAlGrnaCBNetYmAxIA",
	"PUOAKhHLs2EavO3ykRdpyd8oZnyasi1cvO0N0KanK/fjNGAzaEJ3ptgDBaU1j8T0fNE/KpMIsyLaxQub",
	"pIYuj+fNcjY2UTosFHzuCV1RnQ/g19TqMRk4Oz1lryZTuHkjeTGAIx9yOUckIIUvXFqQyddIIrpGpQ99",
	"hfIvhsjVTKRmjMYA6AMWfHacInekQulcdvynQl+dw1grbqpNSR/gAAPU3Fpzx+zItzrc+Td30GDjHesG",
	"ceSkXKCnQ2U8Ga/k3YBvxzELdpiWtJAqvouQ5wAy/Rd/8zl47o+iftdcQm434KA1ckSuUs8PzJ07cYq4",
	"HcbxxdM3DON861472ol1xc1/NM/yarrHNDOFMfUvrRLNsa75GeqWYhHcoW+hDNZsKnu4ruioub5/QBa9",
	"sjN8qpV5SmbK1eD423Z+G2/YdqYwCcJOCos3Ruw+ew4428Qlz4az5SOza4tFeof2o1WLJNZOXUftdJR9",
	"+qhPo7M1YnKZk3TUOp2NstVFTXb17uq/AQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
