//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UserRole.
const (
	Administrator UserRole = "Administrator"
	Regular       UserRole = "Regular"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Administrator:
		return true
	case Regular:
		return true
	default:
		return false
	}
}

// Event defines model for Event.
type Event struct {
	EndsAt     time.Time          `json:"endsAt"`
	EventType  string             `json:"eventType"`
	Id         openapi_types.UUID `json:"id"`
	InsertedAt time.Time          `json:"insertedAt"`
	IsVirtual  bool               `json:"isVirtual"`
	Slug       string             `json:"slug"`
	StartsAt   time.Time          `json:"startsAt"`
	SubtitleEn *string            `json:"subtitleEn,omitempty"`
	SubtitlePl *string            `json:"subtitlePl,omitempty"`
	TitleEn    string             `json:"titleEn"`
	TitlePl    string             `json:"titlePl"`
	UpdatedAt  time.Time          `json:"updatedAt"`
}

// EventDetails defines model for EventDetails.
type EventDetails struct {
	// Currency Currency code. Null when free.
	Currency      *string            `json:"currency,omitempty"`
	DescriptionEn string             `json:"descriptionEn"`
	DescriptionPl string             `json:"descriptionPl"`
	EndsAt        time.Time          `json:"endsAt"`
	EventType     string             `json:"eventType"`
	Hosts         []Host             `json:"hosts"`
	Id            openapi_types.UUID `json:"id"`
	InsertedAt    time.Time          `json:"insertedAt"`
	IsFree        bool               `json:"isFree"`
	IsVirtual     bool               `json:"isVirtual"`

	// Price Decimal price string, e.g. "19.99". Null when free.
	Price      *string   `json:"price,omitempty"`
	Slug       string    `json:"slug"`
	StartsAt   time.Time `json:"startsAt"`
	SubtitleEn *string   `json:"subtitleEn,omitempty"`
	SubtitlePl *string   `json:"subtitlePl,omitempty"`
	TitleEn    string    `json:"titleEn"`
	TitlePl    string    `json:"titlePl"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// EventInput Editable fields of an event, used for both create and update. Server-managed fields (id, insertedAt, updatedAt) are ignored.
type EventInput struct {
	// Currency Currency code. Null when free.
	Currency      *string   `json:"currency,omitempty"`
	DescriptionEn string    `json:"descriptionEn"`
	DescriptionPl string    `json:"descriptionPl"`
	EndsAt        time.Time `json:"endsAt"`
	EventType     string    `json:"eventType"`

	// HostIds IDs of hosts associated with the event.
	HostIds   []openapi_types.UUID `json:"hostIds"`
	IsFree    bool                 `json:"isFree"`
	IsVirtual bool                 `json:"isVirtual"`

	// Price Decimal price string, e.g. "19.99". Null when free.
	Price      *string   `json:"price,omitempty"`
	Slug       string    `json:"slug"`
	StartsAt   time.Time `json:"startsAt"`
	SubtitleEn *string   `json:"subtitleEn,omitempty"`
	SubtitlePl *string   `json:"subtitlePl,omitempty"`
	TitleEn    string    `json:"titleEn"`
	TitlePl    string    `json:"titlePl"`
}

// Health defines model for Health.
type Health struct {
	// Status Example: ok
	Status string `json:"status"`
}

// Host defines model for Host.
type Host struct {
	// Country ISO 3166-1 alpha-2 country code
	Country    *string            `json:"country,omitempty"`
	FamilyName string             `json:"familyName"`
	GivenName  string             `json:"givenName"`
	Id         openapi_types.UUID `json:"id"`

	// Salutation i18n message key, e.g. common.hosts.salutation.dr
	Salutation *string `json:"salutation,omitempty"`
}

// PaginatedEvents defines model for PaginatedEvents.
type PaginatedEvents struct {
	Data []Event `json:"data"`

	// Pagination Pagination metadata describing the returned page.
	Pagination Pagination `json:"pagination"`
}

// PaginatedHosts defines model for PaginatedHosts.
type PaginatedHosts struct {
	Data []Host `json:"data"`

	// Pagination Pagination metadata describing the returned page.
	Pagination Pagination `json:"pagination"`
}

// PaginatedUsers defines model for PaginatedUsers.
type PaginatedUsers struct {
	Data []User `json:"data"`

	// Pagination Pagination metadata describing the returned page.
	Pagination Pagination `json:"pagination"`
}

// PaginatedVideos defines model for PaginatedVideos.
type PaginatedVideos struct {
	Data []Video `json:"data"`

	// Pagination Pagination metadata describing the returned page.
	Pagination Pagination `json:"pagination"`
}

// Pagination Pagination metadata describing the returned page.
type Pagination struct {
	// Page The 1-based page number that was returned.
	Page int32 `json:"page"`

	// PerPage The effective page size after clamping.
	PerPage int32 `json:"perPage"`

	// Total Total number of items across all pages.
	Total int64 `json:"total"`

	// TotalPages Total number of pages given the effective page size.
	TotalPages int32 `json:"totalPages"`
}

// User defines model for User.
type User struct {
	Email            openapi_types.Email `json:"email"`
	EmailConfirmedAt *time.Time          `json:"emailConfirmedAt,omitempty"`
	FamilyName       string              `json:"familyName"`
	GivenName        string              `json:"givenName"`
	Id               openapi_types.UUID  `json:"id"`
	InsertedAt       time.Time           `json:"insertedAt"`

	// PreferredLocale Locale code, e.g. pl or en
	PreferredLocale string   `json:"preferredLocale"`
	ProfilePicture  *string  `json:"profilePicture,omitempty"`
	Role            UserRole `json:"role"`
}

// UserRole defines model for User.Role.
type UserRole string

// Video defines model for Video.
type Video struct {
	Id      openapi_types.UUID `json:"id"`
	TitleEn string             `json:"titleEn"`
	TitlePl string             `json:"titlePl"`
}

// PageParam defines model for PageParam.
type PageParam = int32

// PerPageParam defines model for PerPageParam.
type PerPageParam = int32

// ListEventsParams defines parameters for ListEvents.
type ListEventsParams struct {
	// Page 1-based page number. Values below 1 are treated as 1.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of items per page. Clamped to the [1, 100] range.
	PerPage *PerPageParam `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// ListHostsParams defines parameters for ListHosts.
type ListHostsParams struct {
	// Page 1-based page number. Values below 1 are treated as 1.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of items per page. Clamped to the [1, 100] range.
	PerPage *PerPageParam `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Page 1-based page number. Values below 1 are treated as 1.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of items per page. Clamped to the [1, 100] range.
	PerPage *PerPageParam `form:"perPage,omitempty" json:"perPage,omitempty"`

	// Search Filter term. An email address is matched exactly via the email_hash index; any other value is a case-insensitive substring match on decrypted given/family names.
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// ListVideosParams defines parameters for ListVideos.
type ListVideosParams struct {
	// Page 1-based page number. Values below 1 are treated as 1.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of items per page. Clamped to the [1, 100] range.
	PerPage *PerPageParam `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody = EventInput

// UpdateEventJSONRequestBody defines body for UpdateEvent for application/json ContentType.
type UpdateEventJSONRequestBody = EventInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListEvents List events
	// (GET /events)
	ListEvents(w http.ResponseWriter, r *http.Request, params ListEventsParams)
	// CreateEvent Create an event
	// (POST /events)
	CreateEvent(w http.ResponseWriter, r *http.Request)
	// GetEvent Get a single event by primary key
	// (GET /events/{id})
	GetEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateEvent Update an event
	// (PUT /events/{id})
	UpdateEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetHealth Liveness probe
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// ListHosts List hosts
	// (GET /hosts)
	ListHosts(w http.ResponseWriter, r *http.Request, params ListHostsParams)
	// GetSession Get the currently signed in user
	// (GET /session)
	GetSession(w http.ResponseWriter, r *http.Request)
	// ListUsers List users
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams)
	// ListVideos List videos
	// (GET /videos)
	ListVideos(w http.ResponseWriter, r *http.Request, params ListVideosParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListEvents operation middleware
func (siw *ServerInterfaceWrapper) ListEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEventsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "perPage", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "perPage"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateEvent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEvent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvent operation middleware
func (siw *ServerInterfaceWrapper) GetEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateEvent operation middleware
func (siw *ServerInterfaceWrapper) UpdateEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListHosts operation middleware
func (siw *ServerInterfaceWrapper) ListHosts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListHostsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "perPage", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "perPage"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHosts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "perPage", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "perPage"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "search"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVideos operation middleware
func (siw *ServerInterfaceWrapper) ListVideos(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVideosParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "perPage", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "perPage"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVideos(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/session", wrapper.GetSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users", wrapper.ListUsers)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/videos", wrapper.ListVideos)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/events", wrapper.ListEvents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/events", wrapper.CreateEvent)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/events/{id}", wrapper.GetEvent)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/events/{id}", wrapper.UpdateEvent)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/hosts", wrapper.ListHosts)

	return m
}

type ListEventsRequestObject struct {
	Params ListEventsParams
}

type ListEventsResponseObject interface {
	VisitListEventsResponse(w http.ResponseWriter) error
}

type ListEvents200JSONResponse PaginatedEvents

func (response ListEvents200JSONResponse) VisitListEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEventRequestObject struct {
	Body *CreateEventJSONRequestBody
}

type CreateEventResponseObject interface {
	VisitCreateEventResponse(w http.ResponseWriter) error
}

type CreateEvent201ResponseHeaders struct {
	Location *string
}

type CreateEvent201JSONResponse struct {
	Body    EventDetails
	Headers CreateEvent201ResponseHeaders
}

func (response CreateEvent201JSONResponse) VisitCreateEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEvent422Response struct {
}

func (response CreateEvent422Response) VisitCreateEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(422)
	return nil
}

type GetEventRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetEventResponseObject interface {
	VisitGetEventResponse(w http.ResponseWriter) error
}

type GetEvent200JSONResponse EventDetails

func (response GetEvent200JSONResponse) VisitGetEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetEvent404Response struct {
}

func (response GetEvent404Response) VisitGetEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateEventRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateEventJSONRequestBody
}

type UpdateEventResponseObject interface {
	VisitUpdateEventResponse(w http.ResponseWriter) error
}

type UpdateEvent200JSONResponse EventDetails

func (response UpdateEvent200JSONResponse) VisitUpdateEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateEvent404Response struct {
}

func (response UpdateEvent404Response) VisitUpdateEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateEvent422Response struct {
}

func (response UpdateEvent422Response) VisitUpdateEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(422)
	return nil
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListHostsRequestObject struct {
	Params ListHostsParams
}

type ListHostsResponseObject interface {
	VisitListHostsResponse(w http.ResponseWriter) error
}

type ListHosts200JSONResponse PaginatedHosts

func (response ListHosts200JSONResponse) VisitListHostsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSessionRequestObject struct {
}

type GetSessionResponseObject interface {
	VisitGetSessionResponse(w http.ResponseWriter) error
}

type GetSession200JSONResponse User

func (response GetSession200JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSession401Response struct {
}

func (response GetSession401Response) VisitGetSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ListUsersRequestObject struct {
	Params ListUsersParams
}

type ListUsersResponseObject interface {
	VisitListUsersResponse(w http.ResponseWriter) error
}

type ListUsers200JSONResponse PaginatedUsers

func (response ListUsers200JSONResponse) VisitListUsersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListVideosRequestObject struct {
	Params ListVideosParams
}

type ListVideosResponseObject interface {
	VisitListVideosResponse(w http.ResponseWriter) error
}

type ListVideos200JSONResponse PaginatedVideos

func (response ListVideos200JSONResponse) VisitListVideosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListEvents List events
	// (GET /events)
	ListEvents(ctx context.Context, request ListEventsRequestObject) (ListEventsResponseObject, error)
	// CreateEvent Create an event
	// (POST /events)
	CreateEvent(ctx context.Context, request CreateEventRequestObject) (CreateEventResponseObject, error)
	// GetEvent Get a single event by primary key
	// (GET /events/{id})
	GetEvent(ctx context.Context, request GetEventRequestObject) (GetEventResponseObject, error)
	// UpdateEvent Update an event
	// (PUT /events/{id})
	UpdateEvent(ctx context.Context, request UpdateEventRequestObject) (UpdateEventResponseObject, error)
	// GetHealth Liveness probe
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// ListHosts List hosts
	// (GET /hosts)
	ListHosts(ctx context.Context, request ListHostsRequestObject) (ListHostsResponseObject, error)
	// GetSession Get the currently signed in user
	// (GET /session)
	GetSession(ctx context.Context, request GetSessionRequestObject) (GetSessionResponseObject, error)
	// ListUsers List users
	// (GET /users)
	ListUsers(ctx context.Context, request ListUsersRequestObject) (ListUsersResponseObject, error)
	// ListVideos List videos
	// (GET /videos)
	ListVideos(ctx context.Context, request ListVideosRequestObject) (ListVideosResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListEvents operation middleware
func (sh *strictHandler) ListEvents(w http.ResponseWriter, r *http.Request, params ListEventsParams) {
	var request ListEventsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListEvents(ctx, request.(ListEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListEventsResponseObject); ok {
		if err := validResponse.VisitListEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateEvent operation middleware
func (sh *strictHandler) CreateEvent(w http.ResponseWriter, r *http.Request) {
	var request CreateEventRequestObject

	var body CreateEventJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateEvent(ctx, request.(CreateEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateEventResponseObject); ok {
		if err := validResponse.VisitCreateEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEvent operation middleware
func (sh *strictHandler) GetEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetEventRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEvent(ctx, request.(GetEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEventResponseObject); ok {
		if err := validResponse.VisitGetEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateEvent operation middleware
func (sh *strictHandler) UpdateEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateEventRequestObject

	request.Id = id

	var body UpdateEventJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateEvent(ctx, request.(UpdateEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateEventResponseObject); ok {
		if err := validResponse.VisitUpdateEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListHosts operation middleware
func (sh *strictHandler) ListHosts(w http.ResponseWriter, r *http.Request, params ListHostsParams) {
	var request ListHostsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListHosts(ctx, request.(ListHostsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListHosts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListHostsResponseObject); ok {
		if err := validResponse.VisitListHostsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSession operation middleware
func (sh *strictHandler) GetSession(w http.ResponseWriter, r *http.Request) {
	var request GetSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSession(ctx, request.(GetSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSessionResponseObject); ok {
		if err := validResponse.VisitGetSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListUsers operation middleware
func (sh *strictHandler) ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams) {
	var request ListUsersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListUsers(ctx, request.(ListUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUsers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListUsersResponseObject); ok {
		if err := validResponse.VisitListUsersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListVideos operation middleware
func (sh *strictHandler) ListVideos(w http.ResponseWriter, r *http.Request, params ListVideosParams) {
	var request ListVideosRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVideos(ctx, request.(ListVideosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVideos")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVideosResponseObject); ok {
		if err := validResponse.VisitListVideosResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Frdb9s4Ev9XBrx7SABFttPe4up76rbdbYCiDdptX9riMpbGFncpUktSTr2F//cDh/SnZCfp1/b6FovU",
	"fM/8Zkb5KApTN0aT9k6MP4oGLdbkyfKvS5zRZXgSfpTkCisbL40WYzE6m6CjEhqcEei2npDN4Q2qlhxM",
	"SJlrGAFaAm8JPZWADka5yIQML//Zkl2ITGisSYxFoCEy4YqKaoysptgqL8ajTEyNrdGLsZDa3zsXmail",
	"lnVb86FfNBSPaEZWLJeZuCR7ROznLCmYKUhPtYOGLKuQwyOFdUMleAO+Ing7ymA0HL4Hi3pGByWPzPqF",
	"P/9Xn/T4IUk/HN6gy3JFlX3xZE7as4usach6SfyYdOke8vM1qxI9nXlZB7ESUeet1DOxzAQFMr/x04/d",
	"U1nuUGpbWfYRkdqR9VTehbF0b6T1LaotxhNjFKEOx061s16RnEfr76SiaydeekVPdHhHt0rhRJEYe9vS",
	"keuX6lbXt0j3n12q3rO2CULfwWTLTFj6s5WWSjF+K9gTbKUNn400247dtvWW/bJVrOz4b1uw92sZzOR3",
	"KnwQm8PuMXmUiuMNlXoxFeO3H8U/LU3FWPxjsKkggxSvgxisy2w/WovWWtLFopuYj9IJFKakHJ63SsF1",
	"RRqmljj9bnTMFr0D7tm6ccBJlXGxDnJ1CH8c0/KpcWyjRAatxUUM9V8sUX+cN1YW1FX/MRWyRgV8DFGg",
	"DCif5fBOjB7kDx68E59glf0YioKt9Ny3yL4Nu/HwfhURF7ppfVeNJ6X0QRyYSlKlC3UWNXBoZtAGvJga",
	"CxPjKygYGAB1CTECc3hFdk72rEaNs3A10jiRZQabiM1gHbCnjDBypo2lMljj/yvYvmzpDi69KF1X2YvH",
	"7Ad2OaBzppCMyNfSVwx1TJcRbhX0NwLAXSL+hsL/bRPihweavYz/UoCxXThClO1nwH6890HJU0Llq24L",
	"4zz6NjYzH7BuFL/1x42AmF7r5RQKc4dPYVrtbU85uHj1Au6NfvrpbASomgrPziHd5QJxm6iaYi3V4jl3",
	"hT3+msk56YOnt+y6HKrWY5R5XwU5+reGmpwL7fgftEipUpi6Njrn3M837+elvTt2BJk2euyo3OeDS5xJ",
	"HQoN44XruqNEj7eG2lVD0ak8TWSTjHKMxOXm5r5uLMoOraMaPV11CZ+h0KHe4e/Q57VL895n6BNofC/6",
	"vJElmc9ViIl8Hxr1ZvzmDGryGAhCvDGResbAbsm3Vqchvdsf8djdoftbRdAz3IOv0MM1ujXVQPBOw3m2",
	"Hpd7mdJ0SoWXc4psnfyLAKeeLBRhNJd69gkcvfGx8djjFx6vNFsvA7CwxjlApVgEt8/vp/vb/IYH+QUd",
	"3c1MmQdwSY19WNcAxzUe9i5AtsMsbVY2a4pojx05+wKPs7m7a6hRqh2oik/6etVw8MjoqbT10aH3u0DW",
	"T9lnNJamZC2Vz0yBqiem43PuIBIaNwqMBdL95MxUKrqUhW8t7UptZd8b1kSupEMsvBUvadYqDMD+sAwh",
	"4rxFb+yWf48h+8qTBxA+seuqvWO8vlCKdbQTS7f0zBdpgiPpTgvclXbJsTA1PS2i9mQ1KsBgWyjRVROD",
	"toSHlxc5PJmTXQDpsjFSe5AOXBhlS5hQJXUZZmBsfUXayyJuQ5mKI+dC/T5xRFwBBtjIQTyrQwMKUsM1",
	"TQbWtJ7saQaOl5Nh6HWgDTRkz9ZcjeXfPDUzO2PlXxEgZCwwEZfyd/qdfiadXwvswFVhksbUL8IGlqAw",
	"2lss/DhQWAAWBTUerkJhueLh/SoVlyvg3ShsNsh8HNGCtwB6Tso0FAdPhKsAWVfAuMpXkckmxlcbVIve",
	"yeElOdPaIpTHhTJYOh7/pwo9nK0HW2m0gxNueLM4PLoMLM1iOoTTDPI8T6sD7YNPjEalFmBq6YNzptbU",
	"bC8VjGSpseRIx87Z5e/0KoTEWDw1NRlw2EjSDjjvQkSITMzJuhg6w3yUD0O8moY0NlKMxb18mN9j+PcV",
	"Z8OA1k3yjLgIhVxhjhdlqCXS+dRHZzs7+gN7uM2VwWYZvsxuvry9PF++D2nkGqNdzNnz4TDOUWw23gY2",
	"jQohLY0e/O5im7LZhN+iN1qPB5x7uzn3MOKgmcYNhcvA2JJsSKsF8JQKoTjDiaZrch6m0jp/ytnv2rrG",
	"MOqJGOiJRyaaNBnumvcR76LijBFLBzn/sykXX0zdraXZcrc8Bdhbdgw9+rKcVwvcHiuH1qtIH2koWaAi",
	"LNNIEMp8fwP6+uWz4Bu//36+8zXkOIqxPPfPz7vU36CSZSxBU5SKyj2/PlqtD5PQ4TRl0eCjLJcHU+lX",
	"8itH7yXS3iozXAoVJDAMI/X6G1DI2s0nIAaXXXf269+LcF81x27j+hTsa+cHfwzv93w4M/HCam2IHuS+",
	"T34lDwhO6plKW8WQqVsm5Axse5zymle6351f/v468G2DIW3WPy0UPjGRo+v3ErlarwoP5XBaJn5FgyUO",
	"PaZ6RXYuC27CoqCLDujMSZNz0FgzoaTSaml0EOCfpo8yPxa+R62Ownvq1rbQnXO4B8irRCwTg9Q8H4uR",
	"V+nKV1Qzrr26ysUvTB7atBa7HxF9P5H87lzQU08ZXiMxtQAnZ5rK0M9HwsEQ7Wp7l8ywy+NFs+5vp1L5",
	"lYGvHKEtqqscfqYCW0dMEC4vLkJUky7souFBJTTAzmcsRyQAFTrw1wa4ex1z5obh8cxVyP9AQbYORGr0",
	"RRWKyQcsguw4Q6ld1OiK3/hvha66gokKM5LUJX2AE/RQG+fB6IBNrlX+9D+AegEmDD4d4ujC1IKOzsIY",
	"qp3k/YlrJ7GQ7zAtaaVV3LmEmSOOuBxvLgNXoE723QoJHuHhpNUsIpUZvDjRp6dxEuimcdymfsM0zvZ9",
	"/kv0U7BVDg+TewDL0oaa1OOaucS4gVp7Jbpj2/JzVC2XvKP2Zspg9L6xB9uGjpbr+3+aGJU7DWQt9TPS",
	"s4AGo2/bPu3tx4+WME7CnRIW1yIhfG45pLSJSyYG8/UC+yBYpB33j4YWSa2jto7W2TH2xeM+i863iPFC",
	"JtmotUqMxWbZIpbvl/8LAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
