// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package queries

import (
	"context"

	"uuid"
)

const insertAsset = `-- name: InsertAsset :one
insert into assets (object_key, original_filename) values ($1, $2) returning id, object_key, original_filename, inserted_at, updated_at, scaled
`

type InsertAssetParams struct {
	ObjectKey        *string
	OriginalFilename *string
}

func (q *Queries) InsertAsset(ctx context.Context, arg *InsertAssetParams) (*Asset, error) {
	row := q.db.QueryRow(ctx, insertAsset, arg.ObjectKey, arg.OriginalFilename)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.Scaled,
	)
	return &i, err
}

const listAssetsByIDs = `-- name: ListAssetsByIDs :many
select id, object_key, original_filename, inserted_at, updated_at, scaled from assets where id = any($1::uuid[]) order by id
`

func (q *Queries) ListAssetsByIDs(ctx context.Context, assetIds []uuid.UUID) ([]*Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsByIDs, assetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.ObjectKey,
			&i.OriginalFilename,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.Scaled,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
