// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blog_posts.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const getBlogPostById = `-- name: GetBlogPostById :one
select id, title, slug, language, body, published_at, inserted_at, updated_at from blog_posts where id = $1
`

func (q *Queries) GetBlogPostById(ctx context.Context, id uuid.UUID) (*BlogPost, error) {
	row := q.db.QueryRow(ctx, getBlogPostById, id)
	var i BlogPost
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Language,
		&i.Body,
		&i.PublishedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getBlogPostBySlug = `-- name: GetBlogPostBySlug :one
select id, title, slug, language, body, published_at, inserted_at, updated_at from blog_posts where slug = $1
`

func (q *Queries) GetBlogPostBySlug(ctx context.Context, slug string) (*BlogPost, error) {
	row := q.db.QueryRow(ctx, getBlogPostBySlug, slug)
	var i BlogPost
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Language,
		&i.Body,
		&i.PublishedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertBlogPost = `-- name: InsertBlogPost :one
insert into blog_posts (title, slug, body, language) values ($1, $2, $3, $4)
returning id, title, slug, language, body, published_at, inserted_at, updated_at
`

type InsertBlogPostParams struct {
	Title    string
	Slug     string
	Body     *string
	Language Locale
}

func (q *Queries) InsertBlogPost(ctx context.Context, arg *InsertBlogPostParams) (*BlogPost, error) {
	row := q.db.QueryRow(ctx, insertBlogPost,
		arg.Title,
		arg.Slug,
		arg.Body,
		arg.Language,
	)
	var i BlogPost
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Language,
		&i.Body,
		&i.PublishedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAllBlogPosts = `-- name: ListAllBlogPosts :many
select id, title, slug, language, body, published_at, inserted_at, updated_at from blog_posts p order by id desc
`

func (q *Queries) ListAllBlogPosts(ctx context.Context) ([]*BlogPost, error) {
	rows, err := q.db.Query(ctx, listAllBlogPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*BlogPost
	for rows.Next() {
		var i BlogPost
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Language,
			&i.Body,
			&i.PublishedAt,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedBlogPostsByLanguage = `-- name: ListPublishedBlogPostsByLanguage :many
select id, title, slug, language, body, published_at, inserted_at, updated_at from blog_posts p
where p.published_at is not null
and language = $1 order by id desc
`

func (q *Queries) ListPublishedBlogPostsByLanguage(ctx context.Context, language Locale) ([]*BlogPost, error) {
	rows, err := q.db.Query(ctx, listPublishedBlogPostsByLanguage, language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*BlogPost
	for rows.Next() {
		var i BlogPost
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Language,
			&i.Body,
			&i.PublishedAt,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishBlogPost = `-- name: PublishBlogPost :one
update blog_posts set published_at = now() where id = $1
returning id, title, slug, language, body, published_at, inserted_at, updated_at
`

func (q *Queries) PublishBlogPost(ctx context.Context, id uuid.UUID) (*BlogPost, error) {
	row := q.db.QueryRow(ctx, publishBlogPost, id)
	var i BlogPost
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Language,
		&i.Body,
		&i.PublishedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const unpublishBlogPost = `-- name: UnpublishBlogPost :one
update blog_posts set published_at = null where id = $1
returning id, title, slug, language, body, published_at, inserted_at, updated_at
`

func (q *Queries) UnpublishBlogPost(ctx context.Context, id uuid.UUID) (*BlogPost, error) {
	row := q.db.QueryRow(ctx, unpublishBlogPost, id)
	var i BlogPost
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Language,
		&i.Body,
		&i.PublishedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
