// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: carts.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countCartLineItemQuantitiesForProducts = `-- name: CountCartLineItemQuantitiesForProducts :many
select e.id event_id, c.quantity
from cart_line_items c
join events e on c.product_id = e.product_id
where e.id = any($1::uuid[]) and c.cart_id = $2::uuid
`

type CountCartLineItemQuantitiesForProductsParams struct {
	EventIds []uuid.UUID `json:"eventIds"`
	CartID   uuid.UUID   `json:"cartId"`
}

type CountCartLineItemQuantitiesForProductsRow struct {
	EventID  uuid.UUID `json:"eventId"`
	Quantity int32     `json:"quantity"`
}

func (q *Queries) CountCartLineItemQuantitiesForProducts(ctx context.Context, arg *CountCartLineItemQuantitiesForProductsParams) ([]*CountCartLineItemQuantitiesForProductsRow, error) {
	rows, err := q.db.Query(ctx, countCartLineItemQuantitiesForProducts, arg.EventIds, arg.CartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CountCartLineItemQuantitiesForProductsRow
	for rows.Next() {
		var i CountCartLineItemQuantitiesForProductsRow
		if err := rows.Scan(&i.EventID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCart = `-- name: DeleteCart :exec
delete from cart_line_items where cart_id = $1::uuid
`

func (q *Queries) DeleteCart(ctx context.Context, cartID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCart, cartID)
	return err
}

const deleteCartItem = `-- name: DeleteCartItem :one
delete from cart_line_items cli where cart_id = $1::uuid and product_id = $2::uuid returning id
`

type DeleteCartItemParams struct {
	CartID    uuid.UUID `json:"cartId"`
	ProductID uuid.UUID `json:"productId"`
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg *DeleteCartItemParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteCartItem, arg.CartID, arg.ProductID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getCart = `-- name: GetCart :one
select cli.cart_id, count(cli.id) item_count, sum(cli.quantity * p.base_price_amount)::decimal product_total
from cart_line_items cli
join products p on cli.product_id = p.id
where cli.cart_id = $1::uuid
group by 1
`

type GetCartRow struct {
	CartID       uuid.UUID       `json:"cartId"`
	ItemCount    int64           `json:"itemCount"`
	ProductTotal decimal.Decimal `json:"productTotal"`
}

func (q *Queries) GetCart(ctx context.Context, cartID uuid.UUID) (*GetCartRow, error) {
	row := q.db.QueryRow(ctx, getCart, cartID)
	var i GetCartRow
	err := row.Scan(&i.CartID, &i.ItemCount, &i.ProductTotal)
	return &i, err
}

const getCartItemsByCartId = `-- name: GetCartItemsByCartId :many
select c.id, c.cart_id, c.quantity, c.inserted_at, c.updated_at, c.product_id, (p.base_price_amount * c.quantity)::decimal as subtotal, p.base_price_amount, p.title_en, p.title_pl, e.slug::text slug
from cart_line_items c
join products p on c.product_id = p.id
left join events e on e.product_id = p.id
where c.cart_id = $1::uuid and (e.id is not null)
`

type GetCartItemsByCartIdRow struct {
	ID              uuid.UUID       `json:"id"`
	CartID          uuid.UUID       `json:"cartId"`
	Quantity        int32           `json:"quantity"`
	InsertedAt      time.Time       `json:"insertedAt"`
	UpdatedAt       time.Time       `json:"updatedAt"`
	ProductID       uuid.UUID       `json:"productId"`
	Subtotal        decimal.Decimal `json:"subtotal"`
	BasePriceAmount decimal.Decimal `json:"basePriceAmount"`
	TitleEn         string          `json:"titleEn"`
	TitlePl         string          `json:"titlePl"`
	Slug            string          `json:"slug"`
}

func (q *Queries) GetCartItemsByCartId(ctx context.Context, cartID uuid.UUID) ([]*GetCartItemsByCartIdRow, error) {
	rows, err := q.db.Query(ctx, getCartItemsByCartId, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetCartItemsByCartIdRow
	for rows.Next() {
		var i GetCartItemsByCartIdRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.Quantity,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.ProductID,
			&i.Subtotal,
			&i.BasePriceAmount,
			&i.TitleEn,
			&i.TitlePl,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCartLineItem = `-- name: InsertCartLineItem :one
insert into cart_line_items as cli (cart_id, product_id, quantity) values ($1, $2, 1) on conflict (cart_id, product_id)
do update set quantity = cli.quantity + excluded.quantity returning id, cart_id, quantity, inserted_at, updated_at, product_id
`

type InsertCartLineItemParams struct {
	CartID    uuid.UUID `json:"cartId"`
	ProductID uuid.UUID `json:"productId"`
}

func (q *Queries) InsertCartLineItem(ctx context.Context, arg *InsertCartLineItemParams) (*CartLineItem, error) {
	row := q.db.QueryRow(ctx, insertCartLineItem, arg.CartID, arg.ProductID)
	var i CartLineItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.Quantity,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ProductID,
	)
	return &i, err
}
