// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verifications.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserEmailVerificationRateLimit = `-- name: CheckUserEmailVerificationRateLimit :one
select
    coalesce(max(ut.inserted_at) + $2::interval <= now(), true)::bool as can_request,
    coalesce(
        case
            when max(ut.inserted_at) + $2::interval > now()
            then max(ut.inserted_at) + $2::interval
        end,
        '0001-01-01 00:00:00'::timestamp
    )::timestamp as limited_until
from user_tokens ut
join users u on ut.user_id = u.id
where u.email_hash = $1 and u.email_confirmed_at is null
and ut.context = 'email_verification'
`

type CheckUserEmailVerificationRateLimitParams struct {
	EmailHash       []byte
	RateLimitPeriod pgtype.Interval
}

type CheckUserEmailVerificationRateLimitRow struct {
	CanRequest   bool
	LimitedUntil time.Time
}

func (q *Queries) CheckUserEmailVerificationRateLimit(ctx context.Context, arg *CheckUserEmailVerificationRateLimitParams) (*CheckUserEmailVerificationRateLimitRow, error) {
	row := q.db.QueryRow(ctx, checkUserEmailVerificationRateLimit, arg.EmailHash, arg.RateLimitPeriod)
	var i CheckUserEmailVerificationRateLimitRow
	err := row.Scan(&i.CanRequest, &i.LimitedUntil)
	return &i, err
}

const getExistingEmailVerificationToken = `-- name: GetExistingEmailVerificationToken :one
select id, user_id, context, token, inserted_at, valid_until from user_tokens ut
where ut.user_id = $1 and ut.context = 'email_verification'
and ut.inserted_at > (now() - $2::interval)
`

type GetExistingEmailVerificationTokenParams struct {
	UserID          uuid.UUID
	RateLimitPeriod pgtype.Interval
}

func (q *Queries) GetExistingEmailVerificationToken(ctx context.Context, arg *GetExistingEmailVerificationTokenParams) (*UserToken, error) {
	row := q.db.QueryRow(ctx, getExistingEmailVerificationToken, arg.UserID, arg.RateLimitPeriod)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Context,
		&i.Token,
		&i.InsertedAt,
		&i.ValidUntil,
	)
	return &i, err
}

const getUnverifiedUserByEmail = `-- name: GetUnverifiedUserByEmail :one
select id, salutation, country, profession, organization, company, password_hash, last_login_at, last_login_ip, inserted_at, updated_at, profile_picture, user_role, email_encrypted, email_hash, given_name_encrypted, family_name_encrypted, email_confirmed_at, licence_number_encrypted, preferred_locale, google_oauth_last_used_at from users where email_hash = $1 and email_confirmed_at is null
`

func (q *Queries) GetUnverifiedUserByEmail(ctx context.Context, emailHash []byte) (*User, error) {
	row := q.db.QueryRow(ctx, getUnverifiedUserByEmail, emailHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Salutation,
		&i.Country,
		&i.Profession,
		&i.Organization,
		&i.Company,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ProfilePicture,
		&i.UserRole,
		&i.Email,
		&i.EmailHash,
		&i.GivenName,
		&i.FamilyName,
		&i.EmailConfirmedAt,
		&i.LicenceNumber,
		&i.PreferredLocale,
		&i.GoogleOauthLastUsedAt,
	)
	return &i, err
}
