// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countEvents = `-- name: CountEvents :one
select count(*) from events
`

func (q *Queries) CountEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRegistrationsForEvent = `-- name: CountRegistrationsForEvent :one
select count(*) from event_registrations where event_id = $1
`

func (q *Queries) CountRegistrationsForEvent(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRegistrationsForEvent, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEvent = `-- name: DeleteEvent :execrows
delete from events where id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEvent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEventHosts = `-- name: DeleteEventHosts :exec
delete from events_hosts where event_id = $1
`

func (q *Queries) DeleteEventHosts(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventHosts, eventID)
	return err
}

const getEventById = `-- name: GetEventById :one
select id, title_en, title_pl, starts_at, ends_at, is_virtual, description_en, description_pl, event_type, inserted_at, updated_at, slug, subtitle_en, subtitle_pl, venue_name_en, venue_name_pl, venue_street, venue_city_en, venue_city_pl, venue_postal_code, venue_country_code, product_id, published_at, meeting_url from events where id = $1
`

func (q *Queries) GetEventById(ctx context.Context, id uuid.UUID) (*Event, error) {
	row := q.db.QueryRow(ctx, getEventById, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TitleEn,
		&i.TitlePl,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsVirtual,
		&i.DescriptionEn,
		&i.DescriptionPl,
		&i.EventType,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.SubtitleEn,
		&i.SubtitlePl,
		&i.VenueNameEn,
		&i.VenueNamePl,
		&i.VenueStreet,
		&i.VenueCityEn,
		&i.VenueCityPl,
		&i.VenuePostalCode,
		&i.VenueCountryCode,
		&i.ProductID,
		&i.PublishedAt,
		&i.MeetingUrl,
	)
	return &i, err
}

const getEventBySlug = `-- name: GetEventBySlug :one
select id, title_en, title_pl, starts_at, ends_at, is_virtual, description_en, description_pl, event_type, inserted_at, updated_at, slug, subtitle_en, subtitle_pl, venue_name_en, venue_name_pl, venue_street, venue_city_en, venue_city_pl, venue_postal_code, venue_country_code, product_id, published_at, meeting_url from events where slug = $1
`

func (q *Queries) GetEventBySlug(ctx context.Context, slug string) (*Event, error) {
	row := q.db.QueryRow(ctx, getEventBySlug, slug)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TitleEn,
		&i.TitlePl,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsVirtual,
		&i.DescriptionEn,
		&i.DescriptionPl,
		&i.EventType,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.SubtitleEn,
		&i.SubtitlePl,
		&i.VenueNameEn,
		&i.VenueNamePl,
		&i.VenueStreet,
		&i.VenueCityEn,
		&i.VenueCityPl,
		&i.VenuePostalCode,
		&i.VenueCountryCode,
		&i.ProductID,
		&i.PublishedAt,
		&i.MeetingUrl,
	)
	return &i, err
}

const getPaidEventById = `-- name: GetPaidEventById :one
select e.id, e.title_en, e.title_pl, e.starts_at, e.ends_at, e.is_virtual, e.description_en, e.description_pl, e.event_type, e.inserted_at, e.updated_at, e.slug, e.subtitle_en, e.subtitle_pl, e.venue_name_en, e.venue_name_pl, e.venue_street, e.venue_city_en, e.venue_city_pl, e.venue_postal_code, e.venue_country_code, e.product_id, e.published_at, e.meeting_url, p.id, p.product_type, p.title_pl, p.title_en, p.base_price_amount, p.base_price_currency, p.inserted_at, p.updated_at
from events e
join products p on e.product_id = p.id
where e.id = $1
`

type GetPaidEventByIdRow struct {
	Event   Event
	Product Product
}

func (q *Queries) GetPaidEventById(ctx context.Context, id uuid.UUID) (*GetPaidEventByIdRow, error) {
	row := q.db.QueryRow(ctx, getPaidEventById, id)
	var i GetPaidEventByIdRow
	err := row.Scan(
		&i.Event.ID,
		&i.Event.TitleEn,
		&i.Event.TitlePl,
		&i.Event.StartsAt,
		&i.Event.EndsAt,
		&i.Event.IsVirtual,
		&i.Event.DescriptionEn,
		&i.Event.DescriptionPl,
		&i.Event.EventType,
		&i.Event.InsertedAt,
		&i.Event.UpdatedAt,
		&i.Event.Slug,
		&i.Event.SubtitleEn,
		&i.Event.SubtitlePl,
		&i.Event.VenueNameEn,
		&i.Event.VenueNamePl,
		&i.Event.VenueStreet,
		&i.Event.VenueCityEn,
		&i.Event.VenueCityPl,
		&i.Event.VenuePostalCode,
		&i.Event.VenueCountryCode,
		&i.Event.ProductID,
		&i.Event.PublishedAt,
		&i.Event.MeetingUrl,
		&i.Product.ID,
		&i.Product.ProductType,
		&i.Product.TitlePl,
		&i.Product.TitleEn,
		&i.Product.BasePriceAmount,
		&i.Product.BasePriceCurrency,
		&i.Product.InsertedAt,
		&i.Product.UpdatedAt,
	)
	return &i, err
}

const getRegisterableFreeEventById = `-- name: GetRegisterableFreeEventById :one
select id, title_en, title_pl, starts_at, ends_at, is_virtual, description_en, description_pl, event_type, inserted_at, updated_at, slug, subtitle_en, subtitle_pl, venue_name_en, venue_name_pl, venue_street, venue_city_en, venue_city_pl, venue_postal_code, venue_country_code, product_id, published_at, meeting_url from events where product_id is null and id = $1 and ends_at > now()
`

// Registration is only possible while the event is still running: once it has
// ended, there is nothing left to sign up for.
func (q *Queries) GetRegisterableFreeEventById(ctx context.Context, id uuid.UUID) (*Event, error) {
	row := q.db.QueryRow(ctx, getRegisterableFreeEventById, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TitleEn,
		&i.TitlePl,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsVirtual,
		&i.DescriptionEn,
		&i.DescriptionPl,
		&i.EventType,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.SubtitleEn,
		&i.SubtitlePl,
		&i.VenueNameEn,
		&i.VenueNamePl,
		&i.VenueStreet,
		&i.VenueCityEn,
		&i.VenueCityPl,
		&i.VenuePostalCode,
		&i.VenueCountryCode,
		&i.ProductID,
		&i.PublishedAt,
		&i.MeetingUrl,
	)
	return &i, err
}

const insertEvent = `-- name: InsertEvent :one
insert into events (title_en, title_pl, starts_at, ends_at, is_virtual, description_en, description_pl, event_type, slug, subtitle_en, subtitle_pl, venue_name_en, venue_name_pl, venue_street, venue_city_en, venue_city_pl, venue_postal_code, venue_country_code, product_id, meeting_url)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,$13,$14, $15, $16, $17, $18, $19, $20)
returning id, title_en, title_pl, starts_at, ends_at, is_virtual, description_en, description_pl, event_type, inserted_at, updated_at, slug, subtitle_en, subtitle_pl, venue_name_en, venue_name_pl, venue_street, venue_city_en, venue_city_pl, venue_postal_code, venue_country_code, product_id, published_at, meeting_url
`

type InsertEventParams struct {
	TitleEn          string
	TitlePl          string
	StartsAt         time.Time
	EndsAt           time.Time
	IsVirtual        bool
	DescriptionEn    *string
	DescriptionPl    *string
	EventType        EventType
	Slug             string
	SubtitleEn       *string
	SubtitlePl       *string
	VenueNameEn      *string
	VenueNamePl      *string
	VenueStreet      *string
	VenueCityEn      *string
	VenueCityPl      *string
	VenuePostalCode  *string
	VenueCountryCode *string
	ProductID        *uuid.UUID
	MeetingUrl       *string
}

func (q *Queries) InsertEvent(ctx context.Context, arg *InsertEventParams) (*Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.TitleEn,
		arg.TitlePl,
		arg.StartsAt,
		arg.EndsAt,
		arg.IsVirtual,
		arg.DescriptionEn,
		arg.DescriptionPl,
		arg.EventType,
		arg.Slug,
		arg.SubtitleEn,
		arg.SubtitlePl,
		arg.VenueNameEn,
		arg.VenueNamePl,
		arg.VenueStreet,
		arg.VenueCityEn,
		arg.VenueCityPl,
		arg.VenuePostalCode,
		arg.VenueCountryCode,
		arg.ProductID,
		arg.MeetingUrl,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TitleEn,
		&i.TitlePl,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsVirtual,
		&i.DescriptionEn,
		&i.DescriptionPl,
		&i.EventType,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.SubtitleEn,
		&i.SubtitlePl,
		&i.VenueNameEn,
		&i.VenueNamePl,
		&i.VenueStreet,
		&i.VenueCityEn,
		&i.VenueCityPl,
		&i.VenuePostalCode,
		&i.VenueCountryCode,
		&i.ProductID,
		&i.PublishedAt,
		&i.MeetingUrl,
	)
	return &i, err
}

const insertEventHost = `-- name: InsertEventHost :one
insert into events_hosts (event_id, host_id, position) values ($1, $2, $3) returning id, event_id, host_id, position, inserted_at, updated_at
`

type InsertEventHostParams struct {
	EventID  uuid.UUID
	HostID   uuid.UUID
	Position int32
}

func (q *Queries) InsertEventHost(ctx context.Context, arg *InsertEventHostParams) (*EventsHost, error) {
	row := q.db.QueryRow(ctx, insertEventHost, arg.EventID, arg.HostID, arg.Position)
	var i EventsHost
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.HostID,
		&i.Position,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listEventRegistrationsForUserForEvents = `-- name: ListEventRegistrationsForUserForEvents :many
select er.id, er.event_id, er.user_id, er.inserted_at, er.reminder_24h_sent_at, er.reminder_1h_sent_at from event_registrations er
where er.event_id = any($1::uuid[])
and er.user_id = $2::uuid
`

type ListEventRegistrationsForUserForEventsParams struct {
	Eventids []uuid.UUID
	Userid   uuid.UUID
}

func (q *Queries) ListEventRegistrationsForUserForEvents(ctx context.Context, arg *ListEventRegistrationsForUserForEventsParams) ([]*EventRegistration, error) {
	rows, err := q.db.Query(ctx, listEventRegistrationsForUserForEvents, arg.Eventids, arg.Userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*EventRegistration
	for rows.Next() {
		var i EventRegistration
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.InsertedAt,
			&i.Reminder24hSentAt,
			&i.Reminder1hSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostsForEvents = `-- name: ListHostsForEvents :many
select eh.event_id, h.id, h.salutation, h.given_name, h.family_name, h.profile_picture_id, h.inserted_at, h.updated_at, h.country, a.object_key profile_picture_url
from hosts h
join events_hosts eh on eh.host_id = h.id
left join assets a on h.profile_picture_id = a.id
where eh.event_id = any($1::uuid[])
order by eh.event_id, eh.position
`

type ListHostsForEventsRow struct {
	EventID           uuid.UUID
	ID                uuid.UUID
	Salutation        *string
	GivenName         string
	FamilyName        string
	ProfilePictureID  *uuid.UUID
	InsertedAt        time.Time
	UpdatedAt         time.Time
	Country           *string
	ProfilePictureUrl *string
}

func (q *Queries) ListHostsForEvents(ctx context.Context, eventids []uuid.UUID) ([]*ListHostsForEventsRow, error) {
	rows, err := q.db.Query(ctx, listHostsForEvents, eventids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListHostsForEventsRow
	for rows.Next() {
		var i ListHostsForEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.ID,
			&i.Salutation,
			&i.GivenName,
			&i.FamilyName,
			&i.ProfilePictureID,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.Country,
			&i.ProfilePictureUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricesForEvents = `-- name: ListPricesForEvents :many
select e.id event_id, p.id, p.price_type, p.rule_type, p.price_amount, p.price_currency, p.discount_code, p.priority, p.is_active, p.valid_from, p.valid_until, p.created_at, p.updated_at, p.product_id from product_prices p
join events e on e.product_id = p.id
where e.id = any($1::uuid[])
order by e.id, p.priority
`

type ListPricesForEventsRow struct {
	EventID      uuid.UUID
	ProductPrice ProductPrice
}

func (q *Queries) ListPricesForEvents(ctx context.Context, eventids []uuid.UUID) ([]*ListPricesForEventsRow, error) {
	rows, err := q.db.Query(ctx, listPricesForEvents, eventids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPricesForEventsRow
	for rows.Next() {
		var i ListPricesForEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.ProductPrice.ID,
			&i.ProductPrice.PriceType,
			&i.ProductPrice.RuleType,
			&i.ProductPrice.PriceAmount,
			&i.ProductPrice.PriceCurrency,
			&i.ProductPrice.DiscountCode,
			&i.ProductPrice.Priority,
			&i.ProductPrice.IsActive,
			&i.ProductPrice.ValidFrom,
			&i.ProductPrice.ValidUntil,
			&i.ProductPrice.CreatedAt,
			&i.ProductPrice.UpdatedAt,
			&i.ProductPrice.ProductID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsForEvents = `-- name: ListProductsForEvents :many
select e.id event_id, p.id, p.product_type, p.title_pl, p.title_en, p.base_price_amount, p.base_price_currency, p.inserted_at, p.updated_at
from events e
join products p on e.product_id = p.id
where e.id = any($1::uuid[])
order by 1
`

type ListProductsForEventsRow struct {
	EventID uuid.UUID
	Product Product
}

func (q *Queries) ListProductsForEvents(ctx context.Context, eventids []uuid.UUID) ([]*ListProductsForEventsRow, error) {
	rows, err := q.db.Query(ctx, listProductsForEvents, eventids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListProductsForEventsRow
	for rows.Next() {
		var i ListProductsForEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.Product.ID,
			&i.Product.ProductType,
			&i.Product.TitlePl,
			&i.Product.TitleEn,
			&i.Product.BasePriceAmount,
			&i.Product.BasePriceCurrency,
			&i.Product.InsertedAt,
			&i.Product.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEvents = `-- name: ListPublishedEvents :many
select e.id, e.slug, e.title_en, e.title_pl, e.is_virtual, p.base_price_amount, p.base_price_currency,
       e.event_type, e.starts_at, e.ends_at, e.subtitle_pl, e.subtitle_en,
       e.venue_street, e.venue_city_en, e.venue_city_pl, e.venue_country_code
from events e
left join products p on e.product_id = p.id
where published_at is not null
order by e.starts_at desc
`

type ListPublishedEventsRow struct {
	ID                uuid.UUID
	Slug              string
	TitleEn           string
	TitlePl           string
	IsVirtual         bool
	BasePriceAmount   *decimal.Decimal
	BasePriceCurrency *string
	EventType         EventType
	StartsAt          time.Time
	EndsAt            time.Time
	SubtitlePl        *string
	SubtitleEn        *string
	VenueStreet       *string
	VenueCityEn       *string
	VenueCityPl       *string
	VenueCountryCode  *string
}

func (q *Queries) ListPublishedEvents(ctx context.Context) ([]*ListPublishedEventsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPublishedEventsRow
	for rows.Next() {
		var i ListPublishedEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.TitleEn,
			&i.TitlePl,
			&i.IsVirtual,
			&i.BasePriceAmount,
			&i.BasePriceCurrency,
			&i.EventType,
			&i.StartsAt,
			&i.EndsAt,
			&i.SubtitlePl,
			&i.SubtitleEn,
			&i.VenueStreet,
			&i.VenueCityEn,
			&i.VenueCityPl,
			&i.VenueCountryCode,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paginateEvents = `-- name: PaginateEvents :many
select id, title_en, title_pl, starts_at, ends_at, is_virtual, description_en, description_pl, event_type, inserted_at, updated_at, slug, subtitle_en, subtitle_pl, venue_name_en, venue_name_pl, venue_street, venue_city_en, venue_city_pl, venue_postal_code, venue_country_code, product_id, published_at, meeting_url from events
order by starts_at desc
limit ($2::int) offset ((($1::int) - 1) * $2::int)
`

type PaginateEventsParams struct {
	Page    int32
	PerPage int32
}

func (q *Queries) PaginateEvents(ctx context.Context, arg *PaginateEventsParams) ([]*Event, error) {
	rows, err := q.db.Query(ctx, paginateEvents, arg.Page, arg.PerPage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TitleEn,
			&i.TitlePl,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsVirtual,
			&i.DescriptionEn,
			&i.DescriptionPl,
			&i.EventType,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.SubtitleEn,
			&i.SubtitlePl,
			&i.VenueNameEn,
			&i.VenueNamePl,
			&i.VenueStreet,
			&i.VenueCityEn,
			&i.VenueCityPl,
			&i.VenuePostalCode,
			&i.VenueCountryCode,
			&i.ProductID,
			&i.PublishedAt,
			&i.MeetingUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishEvent = `-- name: PublishEvent :one
update events set published_at = now(), updated_at = now()
where id = $1 and published_at is null returning id, title_en, title_pl, starts_at, ends_at, is_virtual, description_en, description_pl, event_type, inserted_at, updated_at, slug, subtitle_en, subtitle_pl, venue_name_en, venue_name_pl, venue_street, venue_city_en, venue_city_pl, venue_postal_code, venue_country_code, product_id, published_at, meeting_url
`

func (q *Queries) PublishEvent(ctx context.Context, id uuid.UUID) (*Event, error) {
	row := q.db.QueryRow(ctx, publishEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TitleEn,
		&i.TitlePl,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsVirtual,
		&i.DescriptionEn,
		&i.DescriptionPl,
		&i.EventType,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.SubtitleEn,
		&i.SubtitlePl,
		&i.VenueNameEn,
		&i.VenueNamePl,
		&i.VenueStreet,
		&i.VenueCityEn,
		&i.VenueCityPl,
		&i.VenuePostalCode,
		&i.VenueCountryCode,
		&i.ProductID,
		&i.PublishedAt,
		&i.MeetingUrl,
	)
	return &i, err
}

const unpublishEvent = `-- name: UnpublishEvent :one
update events set published_at = null, updated_at = now()
where id = $1 returning id, title_en, title_pl, starts_at, ends_at, is_virtual, description_en, description_pl, event_type, inserted_at, updated_at, slug, subtitle_en, subtitle_pl, venue_name_en, venue_name_pl, venue_street, venue_city_en, venue_city_pl, venue_postal_code, venue_country_code, product_id, published_at, meeting_url
`

func (q *Queries) UnpublishEvent(ctx context.Context, id uuid.UUID) (*Event, error) {
	row := q.db.QueryRow(ctx, unpublishEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TitleEn,
		&i.TitlePl,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsVirtual,
		&i.DescriptionEn,
		&i.DescriptionPl,
		&i.EventType,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.SubtitleEn,
		&i.SubtitlePl,
		&i.VenueNameEn,
		&i.VenueNamePl,
		&i.VenueStreet,
		&i.VenueCityEn,
		&i.VenueCityPl,
		&i.VenuePostalCode,
		&i.VenueCountryCode,
		&i.ProductID,
		&i.PublishedAt,
		&i.MeetingUrl,
	)
	return &i, err
}
