// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_registrations.sql

package queries

import (
	"context"

	sqlcrypter "github.com/bincyber/go-sqlcrypter"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertEventRegistration = `-- name: InsertEventRegistration :one
insert into event_registrations (event_id, user_id, is_host, given_name_encrypted, family_name_encrypted, email_encrypted, country, attending_in_person, email_confirmed_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
returning id, event_id, user_id, attending_in_person, is_host, inserted_at, updated_at, given_name_encrypted, family_name_encrypted, email_encrypted, country, email_confirmed_at
`

type InsertEventRegistrationParams struct {
	EventID           pgtype.UUID               `json:"eventId"`
	UserID            pgtype.UUID               `json:"userId"`
	IsHost            bool                      `json:"isHost"`
	GivenName         sqlcrypter.EncryptedBytes `json:"givenNameEncrypted"`
	FamilyName        sqlcrypter.EncryptedBytes `json:"familyNameEncrypted"`
	Email             sqlcrypter.EncryptedBytes `json:"emailEncrypted"`
	Country           string                    `json:"country"`
	AttendingInPerson bool                      `json:"attendingInPerson"`
	EmailConfirmedAt  pgtype.Timestamp          `json:"emailConfirmedAt"`
}

func (q *Queries) InsertEventRegistration(ctx context.Context, arg *InsertEventRegistrationParams) (*EventRegistration, error) {
	row := q.db.QueryRow(ctx, insertEventRegistration,
		arg.EventID,
		arg.UserID,
		arg.IsHost,
		arg.GivenName,
		arg.FamilyName,
		arg.Email,
		arg.Country,
		arg.AttendingInPerson,
		arg.EmailConfirmedAt,
	)
	var i EventRegistration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.AttendingInPerson,
		&i.IsHost,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.GivenName,
		&i.FamilyName,
		&i.Email,
		&i.Country,
		&i.EmailConfirmedAt,
	)
	return &i, err
}
