// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package queries

import (
	"context"
)

const listEvents = `-- name: ListEvents :many
select id, title_en, title_pl, starts_at, ends_at, is_virtual, description_en, description_pl, event_type, base_price_amount, base_price_currency, inserted_at, updated_at from events order by starts_at desc
`

func (q *Queries) ListEvents(ctx context.Context) ([]*Event, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TitleEn,
			&i.TitlePl,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsVirtual,
			&i.DescriptionEn,
			&i.DescriptionPl,
			&i.EventType,
			&i.BasePriceAmount,
			&i.BasePriceCurrency,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
