// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_registrations.sql

package queries

import (
	"context"
	"time"

	sqlcrypter "github.com/bincyber/go-sqlcrypter"
	"uuid"
)

const claimEventRegistrationsForReminder1h = `-- name: ClaimEventRegistrationsForReminder1h :many
update event_registrations set reminder_1h_sent_at = now()
where id in (
  select er.id from event_registrations er
  join events e on e.id = er.event_id
  where e.published_at is not null
    and er.reminder_1h_sent_at is null
    and e.starts_at > now()
    and e.starts_at <= now() + interval '1 hour'
  for update of er skip locked
)
returning event_id, user_id
`

type ClaimEventRegistrationsForReminder1hRow struct {
	EventID uuid.UUID
	UserID  uuid.UUID
}

// The one-hour counterpart of ClaimEventRegistrationsForReminder24h.
func (q *Queries) ClaimEventRegistrationsForReminder1h(ctx context.Context) ([]*ClaimEventRegistrationsForReminder1hRow, error) {
	rows, err := q.db.Query(ctx, claimEventRegistrationsForReminder1h)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ClaimEventRegistrationsForReminder1hRow
	for rows.Next() {
		var i ClaimEventRegistrationsForReminder1hRow
		if err := rows.Scan(&i.EventID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimEventRegistrationsForReminder24h = `-- name: ClaimEventRegistrationsForReminder24h :many
update event_registrations set reminder_24h_sent_at = now()
where id in (
  select er.id from event_registrations er
  join events e on e.id = er.event_id
  where e.published_at is not null
    and er.reminder_24h_sent_at is null
    and e.starts_at > now() + interval '1 hour'
    and e.starts_at <= now() + interval '24 hours'
  for update of er skip locked
)
returning event_id, user_id
`

type ClaimEventRegistrationsForReminder24hRow struct {
	EventID uuid.UUID
	UserID  uuid.UUID
}

// Stamps and returns the registrations whose day-ahead reminder is due, so that
// a second worker running concurrently cannot pick the same one up. The stamps
// live on the registration rather than on the event, so that somebody
// registering after the scan has run still gets whatever reminders are left.
// Events starting within the hour are left to the one-hour reminder, which keeps
// a late registration from firing both reminders at once.
func (q *Queries) ClaimEventRegistrationsForReminder24h(ctx context.Context) ([]*ClaimEventRegistrationsForReminder24hRow, error) {
	rows, err := q.db.Query(ctx, claimEventRegistrationsForReminder24h)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ClaimEventRegistrationsForReminder24hRow
	for rows.Next() {
		var i ClaimEventRegistrationsForReminder24hRow
		if err := rows.Scan(&i.EventID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEventRegistrations = `-- name: CountEventRegistrations :one
select count(er.id) from event_registrations er
where er.event_id = $1::uuid
`

func (q *Queries) CountEventRegistrations(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEventRegistrations, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRegistrationsForEvents = `-- name: CountRegistrationsForEvents :many
select er.event_id, count(er.id) from event_registrations er
where er.event_id = any($1::uuid[])
group by 1
`

type CountRegistrationsForEventsRow struct {
	EventID uuid.UUID
	Count   int64
}

func (q *Queries) CountRegistrationsForEvents(ctx context.Context, eventids []uuid.UUID) ([]*CountRegistrationsForEventsRow, error) {
	rows, err := q.db.Query(ctx, countRegistrationsForEvents, eventids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CountRegistrationsForEventsRow
	for rows.Next() {
		var i CountRegistrationsForEventsRow
		if err := rows.Scan(&i.EventID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEventRegistration = `-- name: DeleteEventRegistration :one
delete from event_registrations where event_id = $1 and user_id = $2 returning id
`

type DeleteEventRegistrationParams struct {
	EventID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) DeleteEventRegistration(ctx context.Context, arg *DeleteEventRegistrationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteEventRegistration, arg.EventID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getLastEventRegistration = `-- name: GetLastEventRegistration :one
select id, event_id, user_id, inserted_at, reminder_24h_sent_at, reminder_1h_sent_at from event_registrations order by id desc limit 1
`

// Only for testing
func (q *Queries) GetLastEventRegistration(ctx context.Context) (*EventRegistration, error) {
	row := q.db.QueryRow(ctx, getLastEventRegistration)
	var i EventRegistration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.InsertedAt,
		&i.Reminder24hSentAt,
		&i.Reminder1hSentAt,
	)
	return &i, err
}

const getLastEventRegistrationWithDetails = `-- name: GetLastEventRegistrationWithDetails :one
select u.id, u.salutation, u.country, u.profession, u.organization, u.company, u.password_hash, u.last_login_at, u.last_login_ip, u.inserted_at, u.updated_at, u.profile_picture, u.user_role, u.email_encrypted, u.email_hash, u.given_name_encrypted, u.family_name_encrypted, u.email_confirmed_at, u.licence_number_encrypted, u.preferred_locale, u.google_oauth_last_used_at, u.preferred_timezone_encrypted, u.preferred_timezone_locked, e.id, e.title_en, e.title_pl, e.starts_at, e.ends_at, e.is_virtual, e.description_en, e.description_pl, e.event_type, e.inserted_at, e.updated_at, e.slug, e.subtitle_en, e.subtitle_pl, e.venue_name_en, e.venue_name_pl, e.venue_street, e.venue_city_en, e.venue_city_pl, e.venue_postal_code, e.venue_country_code, e.product_id, e.published_at, e.meeting_url
from event_registrations er
join users u on u.id = er.user_id
join events e on e.id = er.event_id
order by er.inserted_at desc
limit 1
`

type GetLastEventRegistrationWithDetailsRow struct {
	User  User
	Event Event
}

// For dev email preview only
func (q *Queries) GetLastEventRegistrationWithDetails(ctx context.Context) (*GetLastEventRegistrationWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getLastEventRegistrationWithDetails)
	var i GetLastEventRegistrationWithDetailsRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Salutation,
		&i.User.Country,
		&i.User.Profession,
		&i.User.Organization,
		&i.User.Company,
		&i.User.PasswordHash,
		&i.User.LastLoginAt,
		&i.User.LastLoginIp,
		&i.User.InsertedAt,
		&i.User.UpdatedAt,
		&i.User.ProfilePicture,
		&i.User.UserRole,
		&i.User.Email,
		&i.User.EmailHash,
		&i.User.GivenName,
		&i.User.FamilyName,
		&i.User.EmailConfirmedAt,
		&i.User.LicenceNumber,
		&i.User.PreferredLocale,
		&i.User.GoogleOauthLastUsedAt,
		&i.User.PreferredTimezone,
		&i.User.PreferredTimezoneLocked,
		&i.Event.ID,
		&i.Event.TitleEn,
		&i.Event.TitlePl,
		&i.Event.StartsAt,
		&i.Event.EndsAt,
		&i.Event.IsVirtual,
		&i.Event.DescriptionEn,
		&i.Event.DescriptionPl,
		&i.Event.EventType,
		&i.Event.InsertedAt,
		&i.Event.UpdatedAt,
		&i.Event.Slug,
		&i.Event.SubtitleEn,
		&i.Event.SubtitlePl,
		&i.Event.VenueNameEn,
		&i.Event.VenueNamePl,
		&i.Event.VenueStreet,
		&i.Event.VenueCityEn,
		&i.Event.VenueCityPl,
		&i.Event.VenuePostalCode,
		&i.Event.VenueCountryCode,
		&i.Event.ProductID,
		&i.Event.PublishedAt,
		&i.Event.MeetingUrl,
	)
	return &i, err
}

const insertEventRegistration = `-- name: InsertEventRegistration :one
insert into event_registrations as er (event_id, user_id) values ($1, $2)
on conflict (event_id, user_id) do update set event_id = excluded.event_id
returning er.id, er.event_id, er.user_id, er.inserted_at, er.reminder_24h_sent_at, er.reminder_1h_sent_at, (xmax = 0)::boolean new_record
`

type InsertEventRegistrationParams struct {
	EventID uuid.UUID
	UserID  uuid.UUID
}

type InsertEventRegistrationRow struct {
	EventRegistration EventRegistration
	NewRecord         bool
}

// The ON CONFLICT DO UPDATE clause is required to force Postgres to return the existing row.
// Since the event_id column is the same for all insert of the same conflicting event,
func (q *Queries) InsertEventRegistration(ctx context.Context, arg *InsertEventRegistrationParams) (*InsertEventRegistrationRow, error) {
	row := q.db.QueryRow(ctx, insertEventRegistration, arg.EventID, arg.UserID)
	var i InsertEventRegistrationRow
	err := row.Scan(
		&i.EventRegistration.ID,
		&i.EventRegistration.EventID,
		&i.EventRegistration.UserID,
		&i.EventRegistration.InsertedAt,
		&i.EventRegistration.Reminder24hSentAt,
		&i.EventRegistration.Reminder1hSentAt,
		&i.NewRecord,
	)
	return &i, err
}

const listEligibleUsersForEvent = `-- name: ListEligibleUsersForEvent :many
select u.id, u.given_name_encrypted, u.family_name_encrypted, u.email_encrypted,
  (er.id is null)::boolean as can_register
from users u
left join event_registrations er on er.user_id = u.id and er.event_id = $1::uuid
order by er.id desc
`

type ListEligibleUsersForEventRow struct {
	ID          uuid.UUID
	GivenName   sqlcrypter.EncryptedBytes
	FamilyName  sqlcrypter.EncryptedBytes
	Email       sqlcrypter.EncryptedBytes
	CanRegister bool
}

func (q *Queries) ListEligibleUsersForEvent(ctx context.Context, eventID uuid.UUID) ([]*ListEligibleUsersForEventRow, error) {
	rows, err := q.db.Query(ctx, listEligibleUsersForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListEligibleUsersForEventRow
	for rows.Next() {
		var i ListEligibleUsersForEventRow
		if err := rows.Scan(
			&i.ID,
			&i.GivenName,
			&i.FamilyName,
			&i.Email,
			&i.CanRegister,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paginateEventRegistrations = `-- name: PaginateEventRegistrations :many
select distinct on (er.id)
  u.id, o.id order_id, o.order_number, u.given_name_encrypted, u.family_name_encrypted,
  u.email_encrypted, er.inserted_at
from event_registrations er
join users u on er.user_id = u.id
join events e on er.event_id = e.id
left join order_line_items oli on oli.product_id = e.product_id
left join orders o on o.id = oli.order_id and o.user_id = er.user_id and o.paid_at is not null and o.cancelled_at is null
where er.event_id = $1::uuid
order by er.id desc, o.paid_at desc
limit ($3::int) offset ((($2::int) - 1) * $3::int)
`

type PaginateEventRegistrationsParams struct {
	EventID uuid.UUID
	Page    int32
	PerPage int32
}

type PaginateEventRegistrationsRow struct {
	ID          uuid.UUID
	OrderID     *uuid.UUID
	OrderNumber *int64
	GivenName   sqlcrypter.EncryptedBytes
	FamilyName  sqlcrypter.EncryptedBytes
	Email       sqlcrypter.EncryptedBytes
	InsertedAt  time.Time
}

func (q *Queries) PaginateEventRegistrations(ctx context.Context, arg *PaginateEventRegistrationsParams) ([]*PaginateEventRegistrationsRow, error) {
	rows, err := q.db.Query(ctx, paginateEventRegistrations, arg.EventID, arg.Page, arg.PerPage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PaginateEventRegistrationsRow
	for rows.Next() {
		var i PaginateEventRegistrationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.OrderNumber,
			&i.GivenName,
			&i.FamilyName,
			&i.Email,
			&i.InsertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
