// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hosts.sql

package queries

import (
	"context"
)

const listHosts = `-- name: ListHosts :many
select id, salutation, given_name, family_name, profile_picture_id, inserted_at, updated_at, country from hosts
order by family_name, given_name
`

func (q *Queries) ListHosts(ctx context.Context) ([]*Host, error) {
	rows, err := q.db.Query(ctx, listHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Salutation,
			&i.GivenName,
			&i.FamilyName,
			&i.ProfilePictureID,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
