// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	sqlcrypter "github.com/bincyber/go-sqlcrypter"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type EventType string

const (
	EventTypeSeminar EventType = "seminar"
	EventTypeWebinar EventType = "webinar"
)

func (e *EventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventType(s)
	case string:
		*e = EventType(s)
	default:
		return fmt.Errorf("unsupported scan type for EventType: %T", src)
	}
	return nil
}

type NullEventType struct {
	EventType EventType `json:"eventType"`
	Valid     bool      `json:"valid"` // Valid is true if EventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventType) Scan(value interface{}) error {
	if value == nil {
		ns.EventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventType), nil
}

type PriceRuleType string

const (
	PriceRuleTypeBase         PriceRuleType = "Base"
	PriceRuleTypeDiscountCode PriceRuleType = "DiscountCode"
	PriceRuleTypeEarlyBird    PriceRuleType = "EarlyBird"
)

func (e *PriceRuleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PriceRuleType(s)
	case string:
		*e = PriceRuleType(s)
	default:
		return fmt.Errorf("unsupported scan type for PriceRuleType: %T", src)
	}
	return nil
}

type NullPriceRuleType struct {
	PriceRuleType PriceRuleType `json:"priceRuleType"`
	Valid         bool          `json:"valid"` // Valid is true if PriceRuleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPriceRuleType) Scan(value interface{}) error {
	if value == nil {
		ns.PriceRuleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PriceRuleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPriceRuleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PriceRuleType), nil
}

type PriceType string

const (
	PriceTypeFixed              PriceType = "Fixed"
	PriceTypePercentage         PriceType = "Percentage"
	PriceTypeDiscountFixed      PriceType = "DiscountFixed"
	PriceTypeDiscountPercentage PriceType = "DiscountPercentage"
)

func (e *PriceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PriceType(s)
	case string:
		*e = PriceType(s)
	default:
		return fmt.Errorf("unsupported scan type for PriceType: %T", src)
	}
	return nil
}

type NullPriceType struct {
	PriceType PriceType `json:"priceType"`
	Valid     bool      `json:"valid"` // Valid is true if PriceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPriceType) Scan(value interface{}) error {
	if value == nil {
		ns.PriceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PriceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPriceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PriceType), nil
}

type UserRole string

const (
	UserRoleRegular       UserRole = "Regular"
	UserRoleAdministrator UserRole = "Administrator"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"userRole"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type VideoProvider string

const (
	VideoProviderYoutube    VideoProvider = "youtube"
	VideoProviderCloudfront VideoProvider = "cloudfront"
)

func (e *VideoProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VideoProvider(s)
	case string:
		*e = VideoProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for VideoProvider: %T", src)
	}
	return nil
}

type NullVideoProvider struct {
	VideoProvider VideoProvider `json:"videoProvider"`
	Valid         bool          `json:"valid"` // Valid is true if VideoProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVideoProvider) Scan(value interface{}) error {
	if value == nil {
		ns.VideoProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VideoProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVideoProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VideoProvider), nil
}

type Asset struct {
	ID               pgtype.UUID      `json:"id"`
	ObjectKey        string           `json:"objectKey"`
	OriginalFilename *string          `json:"originalFilename"`
	InsertedAt       pgtype.Timestamp `json:"insertedAt"`
	UpdatedAt        pgtype.Timestamp `json:"updatedAt"`
}

type Event struct {
	ID                pgtype.UUID      `json:"id"`
	TitleEn           string           `json:"titleEn"`
	TitlePl           string           `json:"titlePl"`
	StartsAt          pgtype.Timestamp `json:"startsAt"`
	EndsAt            pgtype.Timestamp `json:"endsAt"`
	IsVirtual         bool             `json:"isVirtual"`
	DescriptionEn     string           `json:"descriptionEn"`
	DescriptionPl     *string          `json:"descriptionPl"`
	EventType         EventType        `json:"eventType"`
	BasePriceAmount   *decimal.Decimal `json:"basePriceAmount"`
	BasePriceCurrency *string          `json:"basePriceCurrency"`
	InsertedAt        pgtype.Timestamp `json:"insertedAt"`
	UpdatedAt         pgtype.Timestamp `json:"updatedAt"`
	VenueID           pgtype.UUID      `json:"venueId"`
	Slug              string           `json:"slug"`
	SubtitleEn        *string          `json:"subtitleEn"`
	SubtitlePl        *string          `json:"subtitlePl"`
}

type EventPrice struct {
	ID            pgtype.UUID      `json:"id"`
	EventID       pgtype.UUID      `json:"eventId"`
	PriceType     PriceType        `json:"priceType"`
	RuleType      PriceRuleType    `json:"ruleType"`
	PriceAmount   decimal.Decimal  `json:"priceAmount"`
	PriceCurrency string           `json:"priceCurrency"`
	DiscountCode  *string          `json:"discountCode"`
	Priority      int32            `json:"priority"`
	IsActive      bool             `json:"isActive"`
	ValidFrom     pgtype.Timestamp `json:"validFrom"`
	ValidUntil    pgtype.Timestamp `json:"validUntil"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
	UpdatedAt     pgtype.Timestamp `json:"updatedAt"`
}

type EventRegistration struct {
	ID                pgtype.UUID                `json:"id"`
	EventID           pgtype.UUID                `json:"eventId"`
	UserID            pgtype.UUID                `json:"userId"`
	AttendingInPerson bool                       `json:"attendingInPerson"`
	IsHost            bool                       `json:"isHost"`
	InsertedAt        pgtype.Timestamp           `json:"insertedAt"`
	UpdatedAt         pgtype.Timestamp           `json:"updatedAt"`
	GivenName         sqlcrypter.EncryptedBytes  `json:"givenNameEncrypted"`
	FamilyName        sqlcrypter.EncryptedBytes  `json:"familyNameEncrypted"`
	Email             sqlcrypter.EncryptedBytes  `json:"emailEncrypted"`
	Country           string                     `json:"country"`
	EmailConfirmedAt  pgtype.Timestamp           `json:"emailConfirmedAt"`
	LicenceNumber     *sqlcrypter.EncryptedBytes `json:"licenceNumberEncrypted"`
}

type EventsHost struct {
	ID         pgtype.UUID      `json:"id"`
	EventID    pgtype.UUID      `json:"eventId"`
	HostID     pgtype.UUID      `json:"hostId"`
	Position   int32            `json:"position"`
	InsertedAt pgtype.Timestamp `json:"insertedAt"`
	UpdatedAt  pgtype.Timestamp `json:"updatedAt"`
}

type Host struct {
	ID               pgtype.UUID      `json:"id"`
	Salutation       *string          `json:"salutation"`
	GivenName        string           `json:"givenName"`
	FamilyName       string           `json:"familyName"`
	ProfilePictureID pgtype.UUID      `json:"profilePictureId"`
	InsertedAt       pgtype.Timestamp `json:"insertedAt"`
	UpdatedAt        pgtype.Timestamp `json:"updatedAt"`
	Country          *string          `json:"country"`
}

type User struct {
	ID               pgtype.UUID                `json:"id"`
	Salutation       *string                    `json:"salutation"`
	Country          *string                    `json:"country"`
	Profession       *string                    `json:"profession"`
	Organization     *string                    `json:"organization"`
	Company          *string                    `json:"company"`
	PasswordHash     *string                    `json:"passwordHash"`
	LastLoginAt      pgtype.Timestamp           `json:"lastLoginAt"`
	LastLoginIp      *netip.Addr                `json:"lastLoginIp"`
	InsertedAt       pgtype.Timestamp           `json:"insertedAt"`
	UpdatedAt        pgtype.Timestamp           `json:"updatedAt"`
	ProfilePicture   *string                    `json:"profilePicture"`
	UserRole         UserRole                   `json:"userRole"`
	Email            sqlcrypter.EncryptedBytes  `json:"emailEncrypted"`
	EmailHash        []byte                     `json:"emailHash"`
	GivenName        sqlcrypter.EncryptedBytes  `json:"givenNameEncrypted"`
	FamilyName       sqlcrypter.EncryptedBytes  `json:"familyNameEncrypted"`
	EmailConfirmedAt pgtype.Timestamp           `json:"emailConfirmedAt"`
	LicenceNumber    *sqlcrypter.EncryptedBytes `json:"licenceNumberEncrypted"`
}

type UserToken struct {
	ID         pgtype.UUID      `json:"id"`
	UserID     pgtype.UUID      `json:"userId"`
	Context    string           `json:"context"`
	Token      []byte           `json:"token"`
	InsertedAt pgtype.Timestamp `json:"insertedAt"`
	ValidUntil pgtype.Timestamp `json:"validUntil"`
}

type Venue struct {
	ID          pgtype.UUID      `json:"id"`
	NameEn      string           `json:"nameEn"`
	NamePl      *string          `json:"namePl"`
	Street      string           `json:"street"`
	CityEn      string           `json:"cityEn"`
	CityPl      *string          `json:"cityPl"`
	PostalCode  *string          `json:"postalCode"`
	CountryCode string           `json:"countryCode"`
	InsertedAt  pgtype.Timestamp `json:"insertedAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}

type Video struct {
	ID         pgtype.UUID      `json:"id"`
	Provider   VideoProvider    `json:"provider"`
	IsPublic   bool             `json:"isPublic"`
	TitleEn    string           `json:"titleEn"`
	TitlePl    string           `json:"titlePl"`
	Slug       string           `json:"slug"`
	InsertedAt pgtype.Timestamp `json:"insertedAt"`
	UpdatedAt  pgtype.Timestamp `json:"updatedAt"`
	EventID    pgtype.UUID      `json:"eventId"`
}

type VideoSource struct {
	ID          pgtype.UUID      `json:"id"`
	ContentType string           `json:"contentType"`
	Codec       *string          `json:"codec"`
	VideoID     pgtype.UUID      `json:"videoId"`
	ObjectKey   string           `json:"objectKey"`
	InsertedAt  pgtype.Timestamp `json:"insertedAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}
