// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package queries

import (
	"context"
)

const listOrders = `-- name: ListOrders :many
select id, user_id, paid_at, cancelled_at, discount_code, grand_total, currency, inserted_at, updated_at, billing_given_name_encrypted, billing_family_name_encrypted, billing_phone_encrypted, billing_street_encrypted, billing_house_number_encrypted, billing_apartment_number_encrypted, billing_city_encrypted, billing_postal_code_encrypted, billing_country from orders order by id
`

func (q *Queries) ListOrders(ctx context.Context) ([]*Order, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PaidAt,
			&i.CancelledAt,
			&i.DiscountCode,
			&i.GrandTotal,
			&i.Currency,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.BillingGivenName,
			&i.BillingFamilyName,
			&i.BillingPhone,
			&i.BillingStreet,
			&i.BillingHouseNumber,
			&i.BillingApartmentNumber,
			&i.BillingCity,
			&i.BillingPostalCode,
			&i.BillingCountry,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
