// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package queries

import (
	"context"

	sqlcrypter "github.com/bincyber/go-sqlcrypter"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getLastOrderID = `-- name: GetLastOrderID :one
select id from orders order by id desc limit 1
`

func (q *Queries) GetLastOrderID(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getLastOrderID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getOrderByCheckoutSessionID = `-- name: GetOrderByCheckoutSessionID :one
select id, user_id, paid_at, cancelled_at, discount_code, grand_total, currency, inserted_at, updated_at, billing_given_name_encrypted, billing_family_name_encrypted, billing_phone_encrypted, billing_city_encrypted, billing_postal_code_encrypted, billing_country, email_encrypted, billing_address_line1_encrypted, billing_address_line2_encrypted, stripe_checkout_session_id, order_number, billing_tax_id, preferred_locale from orders where stripe_checkout_session_id = $1::text
`

func (q *Queries) GetOrderByCheckoutSessionID(ctx context.Context, sessionID string) (*Order, error) {
	row := q.db.QueryRow(ctx, getOrderByCheckoutSessionID, sessionID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaidAt,
		&i.CancelledAt,
		&i.DiscountCode,
		&i.GrandTotal,
		&i.Currency,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.BillingGivenName,
		&i.BillingFamilyName,
		&i.BillingPhone,
		&i.BillingCity,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.Email,
		&i.BillingAddressLine1,
		&i.BillingAddressLine2,
		&i.StripeCheckoutSessionID,
		&i.OrderNumber,
		&i.BillingTaxID,
		&i.PreferredLocale,
	)
	return &i, err
}

const getOrderByCheckoutSessionIDForUpdate = `-- name: GetOrderByCheckoutSessionIDForUpdate :one
select id, user_id, paid_at, cancelled_at, discount_code, grand_total, currency, inserted_at, updated_at, billing_given_name_encrypted, billing_family_name_encrypted, billing_phone_encrypted, billing_city_encrypted, billing_postal_code_encrypted, billing_country, email_encrypted, billing_address_line1_encrypted, billing_address_line2_encrypted, stripe_checkout_session_id, order_number, billing_tax_id, preferred_locale from orders where stripe_checkout_session_id = $1::text for update
`

func (q *Queries) GetOrderByCheckoutSessionIDForUpdate(ctx context.Context, sessionID string) (*Order, error) {
	row := q.db.QueryRow(ctx, getOrderByCheckoutSessionIDForUpdate, sessionID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaidAt,
		&i.CancelledAt,
		&i.DiscountCode,
		&i.GrandTotal,
		&i.Currency,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.BillingGivenName,
		&i.BillingFamilyName,
		&i.BillingPhone,
		&i.BillingCity,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.Email,
		&i.BillingAddressLine1,
		&i.BillingAddressLine2,
		&i.StripeCheckoutSessionID,
		&i.OrderNumber,
		&i.BillingTaxID,
		&i.PreferredLocale,
	)
	return &i, err
}

const getOrderByID = `-- name: GetOrderByID :one
select id, user_id, paid_at, cancelled_at, discount_code, grand_total, currency, inserted_at, updated_at, billing_given_name_encrypted, billing_family_name_encrypted, billing_phone_encrypted, billing_city_encrypted, billing_postal_code_encrypted, billing_country, email_encrypted, billing_address_line1_encrypted, billing_address_line2_encrypted, stripe_checkout_session_id, order_number, billing_tax_id, preferred_locale from orders where id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (*Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaidAt,
		&i.CancelledAt,
		&i.DiscountCode,
		&i.GrandTotal,
		&i.Currency,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.BillingGivenName,
		&i.BillingFamilyName,
		&i.BillingPhone,
		&i.BillingCity,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.Email,
		&i.BillingAddressLine1,
		&i.BillingAddressLine2,
		&i.StripeCheckoutSessionID,
		&i.OrderNumber,
		&i.BillingTaxID,
		&i.PreferredLocale,
	)
	return &i, err
}

const getOrderLineItemsForOrderID = `-- name: GetOrderLineItemsForOrderID :many
select id, order_id, event_id, event_title, event_price_amount, event_price_currency, quantity, inserted_at, updated_at from order_line_items where order_id = $1 order by id
`

func (q *Queries) GetOrderLineItemsForOrderID(ctx context.Context, orderID uuid.UUID) ([]*OrderLineItem, error) {
	rows, err := q.db.Query(ctx, getOrderLineItemsForOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*OrderLineItem
	for rows.Next() {
		var i OrderLineItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.EventID,
			&i.EventTitle,
			&i.EventPriceAmount,
			&i.EventPriceCurrency,
			&i.Quantity,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOrder = `-- name: InsertOrder :one
insert into orders (order_number, user_id, grand_total, currency, billing_given_name_encrypted, billing_family_name_encrypted, billing_phone_encrypted, billing_city_encrypted, billing_postal_code_encrypted, billing_country, email_encrypted, billing_address_line1_encrypted, billing_address_line2_encrypted, billing_tax_id, preferred_locale)
values (generate_order_number(), $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) returning id, user_id, paid_at, cancelled_at, discount_code, grand_total, currency, inserted_at, updated_at, billing_given_name_encrypted, billing_family_name_encrypted, billing_phone_encrypted, billing_city_encrypted, billing_postal_code_encrypted, billing_country, email_encrypted, billing_address_line1_encrypted, billing_address_line2_encrypted, stripe_checkout_session_id, order_number, billing_tax_id, preferred_locale
`

type InsertOrderParams struct {
	UserID              uuid.UUID
	GrandTotal          decimal.Decimal
	Currency            string
	BillingGivenName    sqlcrypter.EncryptedBytes
	BillingFamilyName   sqlcrypter.EncryptedBytes
	BillingPhone        *sqlcrypter.EncryptedBytes
	BillingCity         sqlcrypter.EncryptedBytes
	BillingPostalCode   *sqlcrypter.EncryptedBytes
	BillingCountry      string
	Email               sqlcrypter.EncryptedBytes
	BillingAddressLine1 sqlcrypter.EncryptedBytes
	BillingAddressLine2 *sqlcrypter.EncryptedBytes
	BillingTaxID        *sqlcrypter.EncryptedBytes
	PreferredLocale     Locale
}

func (q *Queries) InsertOrder(ctx context.Context, arg *InsertOrderParams) (*Order, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.UserID,
		arg.GrandTotal,
		arg.Currency,
		arg.BillingGivenName,
		arg.BillingFamilyName,
		arg.BillingPhone,
		arg.BillingCity,
		arg.BillingPostalCode,
		arg.BillingCountry,
		arg.Email,
		arg.BillingAddressLine1,
		arg.BillingAddressLine2,
		arg.BillingTaxID,
		arg.PreferredLocale,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaidAt,
		&i.CancelledAt,
		&i.DiscountCode,
		&i.GrandTotal,
		&i.Currency,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.BillingGivenName,
		&i.BillingFamilyName,
		&i.BillingPhone,
		&i.BillingCity,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.Email,
		&i.BillingAddressLine1,
		&i.BillingAddressLine2,
		&i.StripeCheckoutSessionID,
		&i.OrderNumber,
		&i.BillingTaxID,
		&i.PreferredLocale,
	)
	return &i, err
}

const insertOrderLineItem = `-- name: InsertOrderLineItem :one
insert into order_line_items (order_id, event_id, event_title, event_price_amount) VALUES ($1, $2, $3, $4) returning id, order_id, event_id, event_title, event_price_amount, event_price_currency, quantity, inserted_at, updated_at
`

type InsertOrderLineItemParams struct {
	OrderID          uuid.UUID
	EventID          uuid.UUID
	EventTitle       string
	EventPriceAmount decimal.Decimal
}

func (q *Queries) InsertOrderLineItem(ctx context.Context, arg *InsertOrderLineItemParams) (*OrderLineItem, error) {
	row := q.db.QueryRow(ctx, insertOrderLineItem,
		arg.OrderID,
		arg.EventID,
		arg.EventTitle,
		arg.EventPriceAmount,
	)
	var i OrderLineItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.EventID,
		&i.EventTitle,
		&i.EventPriceAmount,
		&i.EventPriceCurrency,
		&i.Quantity,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listOrders = `-- name: ListOrders :many
select id, user_id, paid_at, cancelled_at, discount_code, grand_total, currency, inserted_at, updated_at, billing_given_name_encrypted, billing_family_name_encrypted, billing_phone_encrypted, billing_city_encrypted, billing_postal_code_encrypted, billing_country, email_encrypted, billing_address_line1_encrypted, billing_address_line2_encrypted, stripe_checkout_session_id, order_number, billing_tax_id, preferred_locale from orders order by id
`

func (q *Queries) ListOrders(ctx context.Context) ([]*Order, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PaidAt,
			&i.CancelledAt,
			&i.DiscountCode,
			&i.GrandTotal,
			&i.Currency,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.BillingGivenName,
			&i.BillingFamilyName,
			&i.BillingPhone,
			&i.BillingCity,
			&i.BillingPostalCode,
			&i.BillingCountry,
			&i.Email,
			&i.BillingAddressLine1,
			&i.BillingAddressLine2,
			&i.StripeCheckoutSessionID,
			&i.OrderNumber,
			&i.BillingTaxID,
			&i.PreferredLocale,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderAsPaid = `-- name: MarkOrderAsPaid :one
update orders set paid_at = now(), updated_at = now() where id = $1 returning id, user_id, paid_at, cancelled_at, discount_code, grand_total, currency, inserted_at, updated_at, billing_given_name_encrypted, billing_family_name_encrypted, billing_phone_encrypted, billing_city_encrypted, billing_postal_code_encrypted, billing_country, email_encrypted, billing_address_line1_encrypted, billing_address_line2_encrypted, stripe_checkout_session_id, order_number, billing_tax_id, preferred_locale
`

func (q *Queries) MarkOrderAsPaid(ctx context.Context, id uuid.UUID) (*Order, error) {
	row := q.db.QueryRow(ctx, markOrderAsPaid, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaidAt,
		&i.CancelledAt,
		&i.DiscountCode,
		&i.GrandTotal,
		&i.Currency,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.BillingGivenName,
		&i.BillingFamilyName,
		&i.BillingPhone,
		&i.BillingCity,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.Email,
		&i.BillingAddressLine1,
		&i.BillingAddressLine2,
		&i.StripeCheckoutSessionID,
		&i.OrderNumber,
		&i.BillingTaxID,
		&i.PreferredLocale,
	)
	return &i, err
}

const storeCheckoutSessionIDOnOrder = `-- name: StoreCheckoutSessionIDOnOrder :one
update orders set stripe_checkout_session_id = $1, updated_at = now() where id = $2 returning id, user_id, paid_at, cancelled_at, discount_code, grand_total, currency, inserted_at, updated_at, billing_given_name_encrypted, billing_family_name_encrypted, billing_phone_encrypted, billing_city_encrypted, billing_postal_code_encrypted, billing_country, email_encrypted, billing_address_line1_encrypted, billing_address_line2_encrypted, stripe_checkout_session_id, order_number, billing_tax_id, preferred_locale
`

type StoreCheckoutSessionIDOnOrderParams struct {
	StripeCheckoutSessionID *string
	ID                      uuid.UUID
}

func (q *Queries) StoreCheckoutSessionIDOnOrder(ctx context.Context, arg *StoreCheckoutSessionIDOnOrderParams) (*Order, error) {
	row := q.db.QueryRow(ctx, storeCheckoutSessionIDOnOrder, arg.StripeCheckoutSessionID, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaidAt,
		&i.CancelledAt,
		&i.DiscountCode,
		&i.GrandTotal,
		&i.Currency,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.BillingGivenName,
		&i.BillingFamilyName,
		&i.BillingPhone,
		&i.BillingCity,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.Email,
		&i.BillingAddressLine1,
		&i.BillingAddressLine2,
		&i.StripeCheckoutSessionID,
		&i.OrderNumber,
		&i.BillingTaxID,
		&i.PreferredLocale,
	)
	return &i, err
}
