// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package queries

import (
	"context"

	"github.com/shopspring/decimal"
)

const insertProduct = `-- name: InsertProduct :one
insert into products (product_type, title_pl, title_en, base_price_amount, base_price_currency) values ($1, $2, $3, $4, $5) returning id, product_type, title_pl, title_en, base_price_amount, base_price_currency, inserted_at, updated_at
`

type InsertProductParams struct {
	ProductType       ProductType
	TitlePl           string
	TitleEn           string
	BasePriceAmount   decimal.Decimal
	BasePriceCurrency string
}

func (q *Queries) InsertProduct(ctx context.Context, arg *InsertProductParams) (*Product, error) {
	row := q.db.QueryRow(ctx, insertProduct,
		arg.ProductType,
		arg.TitlePl,
		arg.TitleEn,
		arg.BasePriceAmount,
		arg.BasePriceCurrency,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductType,
		&i.TitlePl,
		&i.TitleEn,
		&i.BasePriceAmount,
		&i.BasePriceCurrency,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
