// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countProducts = `-- name: CountProducts :one
select count(*) from products
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProductById = `-- name: GetProductById :one
select id, product_type, title_pl, title_en, base_price_amount, base_price_currency, inserted_at, updated_at from products where id = $1
`

func (q *Queries) GetProductById(ctx context.Context, id uuid.UUID) (*Product, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductType,
		&i.TitlePl,
		&i.TitleEn,
		&i.BasePriceAmount,
		&i.BasePriceCurrency,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertProduct = `-- name: InsertProduct :one
insert into products (product_type, title_pl, title_en, base_price_amount, base_price_currency) values ($1, $2, $3, $4, $5) returning id, product_type, title_pl, title_en, base_price_amount, base_price_currency, inserted_at, updated_at
`

type InsertProductParams struct {
	ProductType       ProductType
	TitlePl           string
	TitleEn           string
	BasePriceAmount   decimal.Decimal
	BasePriceCurrency string
}

func (q *Queries) InsertProduct(ctx context.Context, arg *InsertProductParams) (*Product, error) {
	row := q.db.QueryRow(ctx, insertProduct,
		arg.ProductType,
		arg.TitlePl,
		arg.TitleEn,
		arg.BasePriceAmount,
		arg.BasePriceCurrency,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductType,
		&i.TitlePl,
		&i.TitleEn,
		&i.BasePriceAmount,
		&i.BasePriceCurrency,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const paginateProducts = `-- name: PaginateProducts :many
select id, product_type, title_pl, title_en, base_price_amount, base_price_currency, inserted_at, updated_at from products p order by p.id desc
limit ($2::int) offset ((($1::int) - 1) * $2::int)
`

type PaginateProductsParams struct {
	Page    int32
	PerPage int32
}

func (q *Queries) PaginateProducts(ctx context.Context, arg *PaginateProductsParams) ([]*Product, error) {
	rows, err := q.db.Query(ctx, paginateProducts, arg.Page, arg.PerPage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProductType,
			&i.TitlePl,
			&i.TitleEn,
			&i.BasePriceAmount,
			&i.BasePriceCurrency,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductPrice = `-- name: UpdateProductPrice :one
update products set base_price_amount = $1, base_price_currency = $2, updated_at = now()
where id = $3::uuid
returning id, product_type, title_pl, title_en, base_price_amount, base_price_currency, inserted_at, updated_at
`

type UpdateProductPriceParams struct {
	BasePriceAmount   decimal.Decimal
	BasePriceCurrency string
	ProductID         uuid.UUID
}

func (q *Queries) UpdateProductPrice(ctx context.Context, arg *UpdateProductPriceParams) (*Product, error) {
	row := q.db.QueryRow(ctx, updateProductPrice, arg.BasePriceAmount, arg.BasePriceCurrency, arg.ProductID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductType,
		&i.TitlePl,
		&i.TitleEn,
		&i.BasePriceAmount,
		&i.BasePriceCurrency,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
