// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seeds.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertAsset = `-- name: UpsertAsset :one
insert into assets (id, object_key, original_filename) values ($1, $2, $3)
on conflict (id) do update set object_key = excluded.object_key, original_filename = excluded.original_filename, updated_at = now()
returning id, object_key, original_filename, inserted_at, updated_at
`

type UpsertAssetParams struct {
	ID               pgtype.UUID `json:"id"`
	ObjectKey        string      `json:"objectKey"`
	OriginalFilename *string     `json:"originalFilename"`
}

func (q *Queries) UpsertAsset(ctx context.Context, arg *UpsertAssetParams) (*Asset, error) {
	row := q.db.QueryRow(ctx, upsertAsset, arg.ID, arg.ObjectKey, arg.OriginalFilename)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertHost = `-- name: UpsertHost :one
INSERT INTO hosts (id, salutation, given_name, family_name, profile_picture_id, country)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) do nothing
returning id, salutation, given_name, family_name, profile_picture_id, inserted_at, updated_at, country
`

type UpsertHostParams struct {
	ID               pgtype.UUID `json:"id"`
	Salutation       *string     `json:"salutation"`
	GivenName        string      `json:"givenName"`
	FamilyName       string      `json:"familyName"`
	ProfilePictureID pgtype.UUID `json:"profilePictureId"`
	Country          *string     `json:"country"`
}

func (q *Queries) UpsertHost(ctx context.Context, arg *UpsertHostParams) (*Host, error) {
	row := q.db.QueryRow(ctx, upsertHost,
		arg.ID,
		arg.Salutation,
		arg.GivenName,
		arg.FamilyName,
		arg.ProfilePictureID,
		arg.Country,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Salutation,
		&i.GivenName,
		&i.FamilyName,
		&i.ProfilePictureID,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.Country,
	)
	return &i, err
}
