// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package queries

import (
	"context"
	"net/netip"
	"time"

	sqlcrypter "github.com/bincyber/go-sqlcrypter"
	"github.com/google/uuid"
)

const findOrCreateUserFromClaims = `-- name: FindOrCreateUserFromClaims :one
insert into users (email_encrypted, email_hash, given_name_encrypted, family_name_encrypted, profile_picture, preferred_locale, email_confirmed_at, google_oauth_last_used_at)
values ($1, $2, $3, $4, $5, $6, now(), now())
on conflict (email_hash) do update
set given_name_encrypted = excluded.given_name_encrypted, family_name_encrypted = excluded.family_name_encrypted, profile_picture = excluded.profile_picture, updated_at = now(), email_confirmed_at = coalesce(users.email_confirmed_at, excluded.email_confirmed_at), preferred_locale = coalesce(users.preferred_locale, excluded.preferred_locale), google_oauth_last_used_at = now()
returning id, salutation, country, profession, organization, company, password_hash, last_login_at, last_login_ip, inserted_at, updated_at, profile_picture, user_role, email_encrypted, email_hash, given_name_encrypted, family_name_encrypted, email_confirmed_at, licence_number_encrypted, preferred_locale, google_oauth_last_used_at
`

type FindOrCreateUserFromClaimsParams struct {
	Email           sqlcrypter.EncryptedBytes
	EmailHash       []byte
	GivenName       sqlcrypter.EncryptedBytes
	FamilyName      sqlcrypter.EncryptedBytes
	ProfilePicture  *string
	PreferredLocale Locale
}

func (q *Queries) FindOrCreateUserFromClaims(ctx context.Context, arg *FindOrCreateUserFromClaimsParams) (*User, error) {
	row := q.db.QueryRow(ctx, findOrCreateUserFromClaims,
		arg.Email,
		arg.EmailHash,
		arg.GivenName,
		arg.FamilyName,
		arg.ProfilePicture,
		arg.PreferredLocale,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Salutation,
		&i.Country,
		&i.Profession,
		&i.Organization,
		&i.Company,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ProfilePicture,
		&i.UserRole,
		&i.Email,
		&i.EmailHash,
		&i.GivenName,
		&i.FamilyName,
		&i.EmailConfirmedAt,
		&i.LicenceNumber,
		&i.PreferredLocale,
		&i.GoogleOauthLastUsedAt,
	)
	return &i, err
}

const getUserByAccessToken = `-- name: GetUserByAccessToken :one
select u.id, u.salutation, u.country, u.profession, u.organization, u.company, u.password_hash, u.last_login_at, u.last_login_ip, u.inserted_at, u.updated_at, u.profile_picture, u.user_role, u.email_encrypted, u.email_hash, u.given_name_encrypted, u.family_name_encrypted, u.email_confirmed_at, u.licence_number_encrypted, u.preferred_locale, u.google_oauth_last_used_at from user_tokens ut
join users u on ut.user_id = u.id
where ut.valid_until > now()
and ut.token = $1 and ut.context = 'access'
`

func (q *Queries) GetUserByAccessToken(ctx context.Context, token []byte) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByAccessToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Salutation,
		&i.Country,
		&i.Profession,
		&i.Organization,
		&i.Company,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ProfilePicture,
		&i.UserRole,
		&i.Email,
		&i.EmailHash,
		&i.GivenName,
		&i.FamilyName,
		&i.EmailConfirmedAt,
		&i.LicenceNumber,
		&i.PreferredLocale,
		&i.GoogleOauthLastUsedAt,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, salutation, country, profession, organization, company, password_hash, last_login_at, last_login_ip, inserted_at, updated_at, profile_picture, user_role, email_encrypted, email_hash, given_name_encrypted, family_name_encrypted, email_confirmed_at, licence_number_encrypted, preferred_locale, google_oauth_last_used_at from users where email_hash = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, emailHash []byte) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, emailHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Salutation,
		&i.Country,
		&i.Profession,
		&i.Organization,
		&i.Company,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ProfilePicture,
		&i.UserRole,
		&i.Email,
		&i.EmailHash,
		&i.GivenName,
		&i.FamilyName,
		&i.EmailConfirmedAt,
		&i.LicenceNumber,
		&i.PreferredLocale,
		&i.GoogleOauthLastUsedAt,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, salutation, country, profession, organization, company, password_hash, last_login_at, last_login_ip, inserted_at, updated_at, profile_picture, user_role, email_encrypted, email_hash, given_name_encrypted, family_name_encrypted, email_confirmed_at, licence_number_encrypted, preferred_locale, google_oauth_last_used_at from users where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Salutation,
		&i.Country,
		&i.Profession,
		&i.Organization,
		&i.Company,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ProfilePicture,
		&i.UserRole,
		&i.Email,
		&i.EmailHash,
		&i.GivenName,
		&i.FamilyName,
		&i.EmailConfirmedAt,
		&i.LicenceNumber,
		&i.PreferredLocale,
		&i.GoogleOauthLastUsedAt,
	)
	return &i, err
}

const insertUser = `-- name: InsertUser :one
insert into users (email_encrypted, email_hash, salutation, given_name_encrypted, family_name_encrypted, country, profession, organization, company, password_hash, preferred_locale) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) returning id, salutation, country, profession, organization, company, password_hash, last_login_at, last_login_ip, inserted_at, updated_at, profile_picture, user_role, email_encrypted, email_hash, given_name_encrypted, family_name_encrypted, email_confirmed_at, licence_number_encrypted, preferred_locale, google_oauth_last_used_at
`

type InsertUserParams struct {
	Email           sqlcrypter.EncryptedBytes
	EmailHash       []byte
	Salutation      *string
	GivenName       sqlcrypter.EncryptedBytes
	FamilyName      sqlcrypter.EncryptedBytes
	Country         *string
	Profession      *string
	Organization    *string
	Company         *string
	PasswordHash    *string
	PreferredLocale Locale
}

func (q *Queries) InsertUser(ctx context.Context, arg *InsertUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Email,
		arg.EmailHash,
		arg.Salutation,
		arg.GivenName,
		arg.FamilyName,
		arg.Country,
		arg.Profession,
		arg.Organization,
		arg.Company,
		arg.PasswordHash,
		arg.PreferredLocale,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Salutation,
		&i.Country,
		&i.Profession,
		&i.Organization,
		&i.Company,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ProfilePicture,
		&i.UserRole,
		&i.Email,
		&i.EmailHash,
		&i.GivenName,
		&i.FamilyName,
		&i.EmailConfirmedAt,
		&i.LicenceNumber,
		&i.PreferredLocale,
		&i.GoogleOauthLastUsedAt,
	)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
select id, salutation, country, profession, organization, company, password_hash, last_login_at, last_login_ip, inserted_at, updated_at, profile_picture, user_role, email_encrypted, email_hash, given_name_encrypted, family_name_encrypted, email_confirmed_at, licence_number_encrypted, preferred_locale, google_oauth_last_used_at from users order by id
`

func (q *Queries) ListUsers(ctx context.Context) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Salutation,
			&i.Country,
			&i.Profession,
			&i.Organization,
			&i.Company,
			&i.PasswordHash,
			&i.LastLoginAt,
			&i.LastLoginIp,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.ProfilePicture,
			&i.UserRole,
			&i.Email,
			&i.EmailHash,
			&i.GivenName,
			&i.FamilyName,
			&i.EmailConfirmedAt,
			&i.LicenceNumber,
			&i.PreferredLocale,
			&i.GoogleOauthLastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserLastLogin = `-- name: SetUserLastLogin :exec
update users set last_login_ip = $1, last_login_at = now(), updated_at = now()
where id = $2
`

type SetUserLastLoginParams struct {
	LastLoginIp *netip.Addr
	ID          uuid.UUID
}

func (q *Queries) SetUserLastLogin(ctx context.Context, arg *SetUserLastLoginParams) error {
	_, err := q.db.Exec(ctx, setUserLastLogin, arg.LastLoginIp, arg.ID)
	return err
}

const updateUserPreferredLocale = `-- name: UpdateUserPreferredLocale :exec
update users set preferred_locale = $1 where id = $2
`

type UpdateUserPreferredLocaleParams struct {
	PreferredLocale Locale
	ID              uuid.UUID
}

func (q *Queries) UpdateUserPreferredLocale(ctx context.Context, arg *UpdateUserPreferredLocaleParams) error {
	_, err := q.db.Exec(ctx, updateUserPreferredLocale, arg.PreferredLocale, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
update users
set given_name_encrypted = $1, family_name_encrypted = $2, profession = $3, licence_number_encrypted = $4, country = $5, updated_at = now()
where id = $6 returning id, salutation, country, profession, organization, company, password_hash, last_login_at, last_login_ip, inserted_at, updated_at, profile_picture, user_role, email_encrypted, email_hash, given_name_encrypted, family_name_encrypted, email_confirmed_at, licence_number_encrypted, preferred_locale, google_oauth_last_used_at
`

type UpdateUserProfileParams struct {
	GivenName     sqlcrypter.EncryptedBytes
	FamilyName    sqlcrypter.EncryptedBytes
	Profession    *string
	LicenceNumber *sqlcrypter.EncryptedBytes
	Country       *string
	ID            uuid.UUID
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg *UpdateUserProfileParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.GivenName,
		arg.FamilyName,
		arg.Profession,
		arg.LicenceNumber,
		arg.Country,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Salutation,
		&i.Country,
		&i.Profession,
		&i.Organization,
		&i.Company,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ProfilePicture,
		&i.UserRole,
		&i.Email,
		&i.EmailHash,
		&i.GivenName,
		&i.FamilyName,
		&i.EmailConfirmedAt,
		&i.LicenceNumber,
		&i.PreferredLocale,
		&i.GoogleOauthLastUsedAt,
	)
	return &i, err
}

const upsertUserFromSeedData = `-- name: UpsertUserFromSeedData :one
insert into users (email_encrypted, email_hash, given_name_encrypted, family_name_encrypted, country, password_hash, user_role, email_confirmed_at, preferred_locale)
values ($1, $2, $3, $4, $5, $6, coalesce($8::text::user_role, 'Regular'), $7, coalesce($9::text::locale, 'pl'))
on conflict (email_hash) do update set updated_at = now()
returning id, salutation, country, profession, organization, company, password_hash, last_login_at, last_login_ip, inserted_at, updated_at, profile_picture, user_role, email_encrypted, email_hash, given_name_encrypted, family_name_encrypted, email_confirmed_at, licence_number_encrypted, preferred_locale, google_oauth_last_used_at
`

type UpsertUserFromSeedDataParams struct {
	Email            sqlcrypter.EncryptedBytes
	EmailHash        []byte
	GivenName        sqlcrypter.EncryptedBytes
	FamilyName       sqlcrypter.EncryptedBytes
	Country          *string
	PasswordHash     *string
	EmailConfirmedAt *time.Time
	UserRole         *string
	PreferredLocale  *string
}

func (q *Queries) UpsertUserFromSeedData(ctx context.Context, arg *UpsertUserFromSeedDataParams) (*User, error) {
	row := q.db.QueryRow(ctx, upsertUserFromSeedData,
		arg.Email,
		arg.EmailHash,
		arg.GivenName,
		arg.FamilyName,
		arg.Country,
		arg.PasswordHash,
		arg.EmailConfirmedAt,
		arg.UserRole,
		arg.PreferredLocale,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Salutation,
		&i.Country,
		&i.Profession,
		&i.Organization,
		&i.Company,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ProfilePicture,
		&i.UserRole,
		&i.Email,
		&i.EmailHash,
		&i.GivenName,
		&i.FamilyName,
		&i.EmailConfirmedAt,
		&i.LicenceNumber,
		&i.PreferredLocale,
		&i.GoogleOauthLastUsedAt,
	)
	return &i, err
}

const verifyEmailAddressByUserToken = `-- name: VerifyEmailAddressByUserToken :one
update users u set email_confirmed_at = now(), updated_at = now()
from user_tokens ut
where ut.token = $1 and ut.valid_until > now() and ut.user_id = u.id and u.email_confirmed_at is null
returning u.id, u.salutation, u.country, u.profession, u.organization, u.company, u.password_hash, u.last_login_at, u.last_login_ip, u.inserted_at, u.updated_at, u.profile_picture, u.user_role, u.email_encrypted, u.email_hash, u.given_name_encrypted, u.family_name_encrypted, u.email_confirmed_at, u.licence_number_encrypted, u.preferred_locale, u.google_oauth_last_used_at
`

func (q *Queries) VerifyEmailAddressByUserToken(ctx context.Context, token []byte) (*User, error) {
	row := q.db.QueryRow(ctx, verifyEmailAddressByUserToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Salutation,
		&i.Country,
		&i.Profession,
		&i.Organization,
		&i.Company,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ProfilePicture,
		&i.UserRole,
		&i.Email,
		&i.EmailHash,
		&i.GivenName,
		&i.FamilyName,
		&i.EmailConfirmedAt,
		&i.LicenceNumber,
		&i.PreferredLocale,
		&i.GoogleOauthLastUsedAt,
	)
	return &i, err
}
