// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_tokens.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deletePreexistingEmailVerificationTokens = `-- name: DeletePreexistingEmailVerificationTokens :exec
delete from user_tokens where user_id = $1 and context = 'email_verification'
`

func (q *Queries) DeletePreexistingEmailVerificationTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePreexistingEmailVerificationTokens, userID)
	return err
}

const deleteUserToken = `-- name: DeleteUserToken :one
delete from user_tokens where token = $1 returning true
`

func (q *Queries) DeleteUserToken(ctx context.Context, token []byte) (bool, error) {
	row := q.db.QueryRow(ctx, deleteUserToken, token)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const findUserAndTokenByUserToken = `-- name: FindUserAndTokenByUserToken :one
select u.id, u.salutation, u.country, u.profession, u.organization, u.company, u.password_hash, u.last_login_at, u.last_login_ip, u.inserted_at, u.updated_at, u.profile_picture, u.user_role, u.email_encrypted, u.email_hash, u.given_name_encrypted, u.family_name_encrypted, u.email_confirmed_at, u.licence_number_encrypted, u.preferred_locale, u.google_oauth_last_used_at, u.preferred_timezone_encrypted, u.preferred_timezone_locked, ut.id, ut.user_id, ut.context, ut.token, ut.inserted_at, ut.valid_until from users u
join user_tokens ut on u.id = ut.user_id
where ut.valid_until > now()
and ut.token = $1 and ut.context = $2
`

type FindUserAndTokenByUserTokenParams struct {
	Token   []byte
	Context string
}

type FindUserAndTokenByUserTokenRow struct {
	User      User
	UserToken UserToken
}

func (q *Queries) FindUserAndTokenByUserToken(ctx context.Context, arg *FindUserAndTokenByUserTokenParams) (*FindUserAndTokenByUserTokenRow, error) {
	row := q.db.QueryRow(ctx, findUserAndTokenByUserToken, arg.Token, arg.Context)
	var i FindUserAndTokenByUserTokenRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Salutation,
		&i.User.Country,
		&i.User.Profession,
		&i.User.Organization,
		&i.User.Company,
		&i.User.PasswordHash,
		&i.User.LastLoginAt,
		&i.User.LastLoginIp,
		&i.User.InsertedAt,
		&i.User.UpdatedAt,
		&i.User.ProfilePicture,
		&i.User.UserRole,
		&i.User.Email,
		&i.User.EmailHash,
		&i.User.GivenName,
		&i.User.FamilyName,
		&i.User.EmailConfirmedAt,
		&i.User.LicenceNumber,
		&i.User.PreferredLocale,
		&i.User.GoogleOauthLastUsedAt,
		&i.User.PreferredTimezone,
		&i.User.PreferredTimezoneLocked,
		&i.UserToken.ID,
		&i.UserToken.UserID,
		&i.UserToken.Context,
		&i.UserToken.Token,
		&i.UserToken.InsertedAt,
		&i.UserToken.ValidUntil,
	)
	return &i, err
}

const findUserByUserToken = `-- name: FindUserByUserToken :one
select u.id, u.salutation, u.country, u.profession, u.organization, u.company, u.password_hash, u.last_login_at, u.last_login_ip, u.inserted_at, u.updated_at, u.profile_picture, u.user_role, u.email_encrypted, u.email_hash, u.given_name_encrypted, u.family_name_encrypted, u.email_confirmed_at, u.licence_number_encrypted, u.preferred_locale, u.google_oauth_last_used_at, u.preferred_timezone_encrypted, u.preferred_timezone_locked from users u
join user_tokens ut on u.id = ut.user_id
where ut.valid_until > now()
and ut.token = $1 and ut.context = $2
`

type FindUserByUserTokenParams struct {
	Token   []byte
	Context string
}

func (q *Queries) FindUserByUserToken(ctx context.Context, arg *FindUserByUserTokenParams) (*User, error) {
	row := q.db.QueryRow(ctx, findUserByUserToken, arg.Token, arg.Context)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Salutation,
		&i.Country,
		&i.Profession,
		&i.Organization,
		&i.Company,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ProfilePicture,
		&i.UserRole,
		&i.Email,
		&i.EmailHash,
		&i.GivenName,
		&i.FamilyName,
		&i.EmailConfirmedAt,
		&i.LicenceNumber,
		&i.PreferredLocale,
		&i.GoogleOauthLastUsedAt,
		&i.PreferredTimezone,
		&i.PreferredTimezoneLocked,
	)
	return &i, err
}

const insertUserToken = `-- name: InsertUserToken :one
insert into user_tokens (user_id, context, token, valid_until) values ($1, $2, $3, $4) returning id, user_id, context, token, inserted_at, valid_until
`

type InsertUserTokenParams struct {
	UserID     uuid.UUID
	Context    string
	Token      []byte
	ValidUntil time.Time
}

func (q *Queries) InsertUserToken(ctx context.Context, arg *InsertUserTokenParams) (*UserToken, error) {
	row := q.db.QueryRow(ctx, insertUserToken,
		arg.UserID,
		arg.Context,
		arg.Token,
		arg.ValidUntil,
	)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Context,
		&i.Token,
		&i.InsertedAt,
		&i.ValidUntil,
	)
	return &i, err
}

const vacuumUserTokens = `-- name: VacuumUserTokens :exec
delete from user_tokens where valid_until < now()
`

func (q *Queries) VacuumUserTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, vacuumUserTokens)
	return err
}
