// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package queries

import (
	"context"
)

const getUserByAccessToken = `-- name: GetUserByAccessToken :one
select u.id, u.email, u.salutation, u.given_name, u.family_name, u.country, u.profession, u.organization, u.company, u.password_hash, u.last_login_at, u.last_login_ip, u.inserted_at, u.updated_at from user_tokens ut
join users u on ut.user_id = u.id
where ut.valid_until > (now() at time zone 'utc')
and ut.token = $1::bytea and ut.context = 'access'
`

func (q *Queries) GetUserByAccessToken(ctx context.Context, token []byte) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByAccessToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Salutation,
		&i.GivenName,
		&i.FamilyName,
		&i.Country,
		&i.Profession,
		&i.Organization,
		&i.Company,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, salutation, given_name, family_name, country, profession, organization, company, password_hash, last_login_at, last_login_ip, inserted_at, updated_at from users where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Salutation,
		&i.GivenName,
		&i.FamilyName,
		&i.Country,
		&i.Profession,
		&i.Organization,
		&i.Company,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
