// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserToken = `-- name: DeleteUserToken :one
delete from user_tokens where token = $1 returning true
`

func (q *Queries) DeleteUserToken(ctx context.Context, token []byte) (bool, error) {
	row := q.db.QueryRow(ctx, deleteUserToken, token)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const findOrCreateUserFromClaims = `-- name: FindOrCreateUserFromClaims :one
insert into users (email, given_name, family_name, profile_picture)
values ($1, $2, $3, $4)
on conflict (email) do update
set email = excluded.email, given_name = excluded.given_name, family_name = excluded.family_name, profile_picture = excluded.profile_picture, updated_at = now() at time zone 'utc'
returning id, email, salutation, given_name, family_name, country, profession, organization, company, password_hash, last_login_at, last_login_ip, inserted_at, updated_at, profile_picture
`

type FindOrCreateUserFromClaimsParams struct {
	Email          string  `json:"email"`
	GivenName      string  `json:"givenName"`
	FamilyName     string  `json:"familyName"`
	ProfilePicture *string `json:"profilePicture"`
}

func (q *Queries) FindOrCreateUserFromClaims(ctx context.Context, arg *FindOrCreateUserFromClaimsParams) (*User, error) {
	row := q.db.QueryRow(ctx, findOrCreateUserFromClaims,
		arg.Email,
		arg.GivenName,
		arg.FamilyName,
		arg.ProfilePicture,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Salutation,
		&i.GivenName,
		&i.FamilyName,
		&i.Country,
		&i.Profession,
		&i.Organization,
		&i.Company,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ProfilePicture,
	)
	return &i, err
}

const getUserByAccessToken = `-- name: GetUserByAccessToken :one
select u.id, u.email, u.salutation, u.given_name, u.family_name, u.country, u.profession, u.organization, u.company, u.password_hash, u.last_login_at, u.last_login_ip, u.inserted_at, u.updated_at, u.profile_picture from user_tokens ut
join users u on ut.user_id = u.id
where ut.valid_until > (now() at time zone 'utc')
and ut.token = $1::bytea and ut.context = 'access'
`

func (q *Queries) GetUserByAccessToken(ctx context.Context, token []byte) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByAccessToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Salutation,
		&i.GivenName,
		&i.FamilyName,
		&i.Country,
		&i.Profession,
		&i.Organization,
		&i.Company,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ProfilePicture,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, salutation, given_name, family_name, country, profession, organization, company, password_hash, last_login_at, last_login_ip, inserted_at, updated_at, profile_picture from users where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Salutation,
		&i.GivenName,
		&i.FamilyName,
		&i.Country,
		&i.Profession,
		&i.Organization,
		&i.Company,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ProfilePicture,
	)
	return &i, err
}

const insertUser = `-- name: InsertUser :one
insert into users (email, salutation, given_name, family_name, country, profession, organization, company, password_hash) values ($1, $2, $3, $4, $5, $6, $7, $8, $9) returning id, email, salutation, given_name, family_name, country, profession, organization, company, password_hash, last_login_at, last_login_ip, inserted_at, updated_at, profile_picture
`

type InsertUserParams struct {
	Email        string  `json:"email"`
	Salutation   *string `json:"salutation"`
	GivenName    string  `json:"givenName"`
	FamilyName   string  `json:"familyName"`
	Country      *string `json:"country"`
	Profession   *string `json:"profession"`
	Organization *string `json:"organization"`
	Company      *string `json:"company"`
	PasswordHash *string `json:"passwordHash"`
}

func (q *Queries) InsertUser(ctx context.Context, arg *InsertUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Email,
		arg.Salutation,
		arg.GivenName,
		arg.FamilyName,
		arg.Country,
		arg.Profession,
		arg.Organization,
		arg.Company,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Salutation,
		&i.GivenName,
		&i.FamilyName,
		&i.Country,
		&i.Profession,
		&i.Organization,
		&i.Company,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ProfilePicture,
	)
	return &i, err
}

const insertUserToken = `-- name: InsertUserToken :one
insert into user_tokens (user_id, context, token, valid_until) values ($1, $2, $3, $4) returning id, user_id, context, token, inserted_at, valid_until
`

type InsertUserTokenParams struct {
	UserID     pgtype.UUID      `json:"userId"`
	Context    string           `json:"context"`
	Token      []byte           `json:"token"`
	ValidUntil pgtype.Timestamp `json:"validUntil"`
}

func (q *Queries) InsertUserToken(ctx context.Context, arg *InsertUserTokenParams) (*UserToken, error) {
	row := q.db.QueryRow(ctx, insertUserToken,
		arg.UserID,
		arg.Context,
		arg.Token,
		arg.ValidUntil,
	)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Context,
		&i.Token,
		&i.InsertedAt,
		&i.ValidUntil,
	)
	return &i, err
}
