// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_tokens.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteUserToken = `-- name: DeleteUserToken :one
delete from user_tokens where token = $1 returning true
`

func (q *Queries) DeleteUserToken(ctx context.Context, token []byte) (bool, error) {
	row := q.db.QueryRow(ctx, deleteUserToken, token)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const insertUserToken = `-- name: InsertUserToken :one
insert into user_tokens (user_id, context, token, valid_until) values ($1, $2, $3, $4) returning id, user_id, context, token, inserted_at, valid_until
`

type InsertUserTokenParams struct {
	UserID     uuid.UUID
	Context    string
	Token      []byte
	ValidUntil time.Time
}

func (q *Queries) InsertUserToken(ctx context.Context, arg *InsertUserTokenParams) (*UserToken, error) {
	row := q.db.QueryRow(ctx, insertUserToken,
		arg.UserID,
		arg.Context,
		arg.Token,
		arg.ValidUntil,
	)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Context,
		&i.Token,
		&i.InsertedAt,
		&i.ValidUntil,
	)
	return &i, err
}
