// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const addVideoToVideoGroup = `-- name: AddVideoToVideoGroup :one
insert into video_groups_videos (video_id, video_group_id, position)
select $1, $2, coalesce(max(position), -1) + 1
from video_groups_videos where video_group_id = $2
on conflict (video_id, video_group_id) do nothing
returning id, position, video_id, video_group_id, inserted_at, updated_at
`

type AddVideoToVideoGroupParams struct {
	VideoID      uuid.UUID
	VideoGroupID uuid.UUID
}

func (q *Queries) AddVideoToVideoGroup(ctx context.Context, arg *AddVideoToVideoGroupParams) (*VideoGroupsVideo, error) {
	row := q.db.QueryRow(ctx, addVideoToVideoGroup, arg.VideoID, arg.VideoGroupID)
	var i VideoGroupsVideo
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.VideoID,
		&i.VideoGroupID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getVideoForUser = `-- name: GetVideoForUser :one
select v.id, v.provider, v.is_public, v.title_en, v.title_pl, v.slug, v.inserted_at, v.updated_at, v.duration_seconds, v.thumbnail_id from videos v
join video_groups_videos vgv on vgv.video_id = v.id
join video_groups vg on vgv.video_group_id = vg.id
where v.slug = $1 and vg.slug = $2 and (
    vg.product_id is null or vg.id in (
        select vg.id from video_groups vg
        join user_product_access upa on upa.product_id = vg.product_id
        where upa.user_id = $3::uuid
    ) or exists (
        select from users u where u.id = $3::uuid and u.user_role = 'Administrator'
    )
) limit 1
`

type GetVideoForUserParams struct {
	VideoSlug string
	GroupSlug string
	UserID    *uuid.UUID
}

func (q *Queries) GetVideoForUser(ctx context.Context, arg *GetVideoForUserParams) (*Video, error) {
	row := q.db.QueryRow(ctx, getVideoForUser, arg.VideoSlug, arg.GroupSlug, arg.UserID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.IsPublic,
		&i.TitleEn,
		&i.TitlePl,
		&i.Slug,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.DurationSeconds,
		&i.ThumbnailID,
	)
	return &i, err
}

const getVideoGroupForUserBySlug = `-- name: GetVideoGroupForUserBySlug :one
select vg.id, vg.title_en, vg.title_pl, vg.slug, vg.product_id, vg.inserted_at, vg.updated_at from video_groups vg
where ($1::text is null or vg.slug = $1) and (
    vg.product_id is null or vg.id in (
        select vg.id from video_groups vg
        join user_product_access upa on upa.product_id = vg.product_id
        where upa.user_id = $2::uuid
    ) or exists (
        select from users u where u.id = $2::uuid and u.user_role = 'Administrator'
    )
) limit 1
`

type GetVideoGroupForUserBySlugParams struct {
	Slug   *string
	UserID *uuid.UUID
}

func (q *Queries) GetVideoGroupForUserBySlug(ctx context.Context, arg *GetVideoGroupForUserBySlugParams) (*VideoGroup, error) {
	row := q.db.QueryRow(ctx, getVideoGroupForUserBySlug, arg.Slug, arg.UserID)
	var i VideoGroup
	err := row.Scan(
		&i.ID,
		&i.TitleEn,
		&i.TitlePl,
		&i.Slug,
		&i.ProductID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertVideoGroup = `-- name: InsertVideoGroup :one
insert into video_groups (title_en, title_pl, slug, product_id) values ($1, $2, $3, $4) returning id, title_en, title_pl, slug, product_id, inserted_at, updated_at
`

type InsertVideoGroupParams struct {
	TitleEn   string
	TitlePl   string
	Slug      string
	ProductID *uuid.UUID
}

func (q *Queries) InsertVideoGroup(ctx context.Context, arg *InsertVideoGroupParams) (*VideoGroup, error) {
	row := q.db.QueryRow(ctx, insertVideoGroup,
		arg.TitleEn,
		arg.TitlePl,
		arg.Slug,
		arg.ProductID,
	)
	var i VideoGroup
	err := row.Scan(
		&i.ID,
		&i.TitleEn,
		&i.TitlePl,
		&i.Slug,
		&i.ProductID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listVideoGroupsForUser = `-- name: ListVideoGroupsForUser :many
select vg.id, vg.title_en, vg.title_pl, vg.slug, vg.product_id, vg.inserted_at, vg.updated_at from video_groups vg
where vg.product_id is null
or vg.id in (
  select vg.id from video_groups vg
  join user_product_access upa on upa.product_id = vg.product_id
  where upa.user_id = $1::uuid
) or exists (
  select from users u where u.id = $1::uuid and u.user_role = 'Administrator'
)
`

func (q *Queries) ListVideoGroupsForUser(ctx context.Context, userID *uuid.UUID) ([]*VideoGroup, error) {
	rows, err := q.db.Query(ctx, listVideoGroupsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*VideoGroup
	for rows.Next() {
		var i VideoGroup
		if err := rows.Scan(
			&i.ID,
			&i.TitleEn,
			&i.TitlePl,
			&i.Slug,
			&i.ProductID,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideoSourcesForVideos = `-- name: ListVideoSourcesForVideos :many
select id, content_type, codec, video_id, object_key, inserted_at, updated_at, priority from video_sources vs
where vs.video_id = any($1::uuid[])
order by vs.video_id, vs.priority
`

func (q *Queries) ListVideoSourcesForVideos(ctx context.Context, videoIds []uuid.UUID) ([]*VideoSource, error) {
	rows, err := q.db.Query(ctx, listVideoSourcesForVideos, videoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*VideoSource
	for rows.Next() {
		var i VideoSource
		if err := rows.Scan(
			&i.ID,
			&i.ContentType,
			&i.Codec,
			&i.VideoID,
			&i.ObjectKey,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideos = `-- name: ListVideos :many
select v.id, v.provider, v.is_public, v.title_en, v.title_pl, v.slug, v.inserted_at, v.updated_at, v.duration_seconds, v.thumbnail_id from videos v
order by v.id desc
`

func (q *Queries) ListVideos(ctx context.Context) ([]*Video, error) {
	rows, err := q.db.Query(ctx, listVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.IsPublic,
			&i.TitleEn,
			&i.TitlePl,
			&i.Slug,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.DurationSeconds,
			&i.ThumbnailID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosForVideoGroup = `-- name: ListVideosForVideoGroup :many
select v.id, v.provider, v.is_public, v.title_en, v.title_pl, v.slug, v.inserted_at, v.updated_at, v.duration_seconds, v.thumbnail_id, a.id, a.object_key, a.original_filename, a.inserted_at, a.updated_at from videos v
join video_groups_videos vgv on vgv.video_id = v.id
left join assets a on v.thumbnail_id = a.id
where vgv.video_group_id = $1
order by position
`

type ListVideosForVideoGroupRow struct {
	Video Video
	Asset Asset
}

func (q *Queries) ListVideosForVideoGroup(ctx context.Context, videoGroupID uuid.UUID) ([]*ListVideosForVideoGroupRow, error) {
	rows, err := q.db.Query(ctx, listVideosForVideoGroup, videoGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListVideosForVideoGroupRow
	for rows.Next() {
		var i ListVideosForVideoGroupRow
		if err := rows.Scan(
			&i.Video.ID,
			&i.Video.Provider,
			&i.Video.IsPublic,
			&i.Video.TitleEn,
			&i.Video.TitlePl,
			&i.Video.Slug,
			&i.Video.InsertedAt,
			&i.Video.UpdatedAt,
			&i.Video.DurationSeconds,
			&i.Video.ThumbnailID,
			&i.Asset.ID,
			&i.Asset.ObjectKey,
			&i.Asset.OriginalFilename,
			&i.Asset.InsertedAt,
			&i.Asset.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVideoGroup = `-- name: UpsertVideoGroup :one
insert into video_groups (id, title_en, title_pl, slug, product_id) values ($1, $2, $3, $4, $5)
on conflict (slug) do update set title_en = excluded.title_en, title_pl = excluded.title_pl, product_id = excluded.product_id
returning id, title_en, title_pl, slug, product_id, inserted_at, updated_at
`

type UpsertVideoGroupParams struct {
	ID        uuid.UUID
	TitleEn   string
	TitlePl   string
	Slug      string
	ProductID *uuid.UUID
}

func (q *Queries) UpsertVideoGroup(ctx context.Context, arg *UpsertVideoGroupParams) (*VideoGroup, error) {
	row := q.db.QueryRow(ctx, upsertVideoGroup,
		arg.ID,
		arg.TitleEn,
		arg.TitlePl,
		arg.Slug,
		arg.ProductID,
	)
	var i VideoGroup
	err := row.Scan(
		&i.ID,
		&i.TitleEn,
		&i.TitlePl,
		&i.Slug,
		&i.ProductID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
