// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videos.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addVideoToVideoGroup = `-- name: AddVideoToVideoGroup :one
insert into video_groups_videos (video_id, video_group_id, position)
select $1, $2, coalesce(max(position), -1) + 1
from video_groups_videos where video_group_id = $2
on conflict (video_id, video_group_id) do nothing
returning id, position, video_id, video_group_id, inserted_at, updated_at
`

type AddVideoToVideoGroupParams struct {
	VideoID      uuid.UUID
	VideoGroupID uuid.UUID
}

func (q *Queries) AddVideoToVideoGroup(ctx context.Context, arg *AddVideoToVideoGroupParams) (*VideoGroupsVideo, error) {
	row := q.db.QueryRow(ctx, addVideoToVideoGroup, arg.VideoID, arg.VideoGroupID)
	var i VideoGroupsVideo
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.VideoID,
		&i.VideoGroupID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMinMaxRecordedDatesForVideoGroups = `-- name: GetMinMaxRecordedDatesForVideoGroups :many
select vg.id, min(v.recorded_on)::date min_recorded_on, max(v.recorded_on):: date max_recorded_on
from video_groups vg
join video_groups_videos vgv on vg.id = vgv.video_group_id
join videos v on v.id = vgv.video_id
where vg.id = any($1::uuid[])
group by 1
order by 1
`

type GetMinMaxRecordedDatesForVideoGroupsRow struct {
	ID            uuid.UUID
	MinRecordedOn time.Time
	MaxRecordedOn time.Time
}

func (q *Queries) GetMinMaxRecordedDatesForVideoGroups(ctx context.Context, videoGroupIds []uuid.UUID) ([]*GetMinMaxRecordedDatesForVideoGroupsRow, error) {
	rows, err := q.db.Query(ctx, getMinMaxRecordedDatesForVideoGroups, videoGroupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetMinMaxRecordedDatesForVideoGroupsRow
	for rows.Next() {
		var i GetMinMaxRecordedDatesForVideoGroupsRow
		if err := rows.Scan(&i.ID, &i.MinRecordedOn, &i.MaxRecordedOn); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideoForUser = `-- name: GetVideoForUser :one
select v.id, v.provider, v.is_public, v.title_en, v.title_pl, v.slug, v.inserted_at, v.updated_at, v.duration_seconds, v.recorded_on, v.host_id, v.thumbnail_en_id, v.thumbnail_pl_id, v.youtube_id, v.description_pl, v.description_en, a.has_access from videos v
join video_groups_videos vgv on vgv.video_id = v.id
join video_groups vg on vgv.video_group_id = vg.id
join user_video_group_access a on vg.id = a.video_group_id and a.user_id = $1::uuid
where v.slug = $2 and vg.slug = $3
limit 1
`

type GetVideoForUserParams struct {
	UserID    uuid.UUID
	VideoSlug string
	GroupSlug string
}

type GetVideoForUserRow struct {
	Video     Video
	HasAccess bool
}

func (q *Queries) GetVideoForUser(ctx context.Context, arg *GetVideoForUserParams) (*GetVideoForUserRow, error) {
	row := q.db.QueryRow(ctx, getVideoForUser, arg.UserID, arg.VideoSlug, arg.GroupSlug)
	var i GetVideoForUserRow
	err := row.Scan(
		&i.Video.ID,
		&i.Video.Provider,
		&i.Video.IsPublic,
		&i.Video.TitleEn,
		&i.Video.TitlePl,
		&i.Video.Slug,
		&i.Video.InsertedAt,
		&i.Video.UpdatedAt,
		&i.Video.DurationSeconds,
		&i.Video.RecordedOn,
		&i.Video.HostID,
		&i.Video.ThumbnailEnID,
		&i.Video.ThumbnailPlID,
		&i.Video.YoutubeID,
		&i.Video.DescriptionPl,
		&i.Video.DescriptionEn,
		&i.HasAccess,
	)
	return &i, err
}

const getVideoGroupForUserBySlug = `-- name: GetVideoGroupForUserBySlug :one
select vg.id, vg.title_en, vg.title_pl, vg.slug, vg.product_id, vg.inserted_at, vg.updated_at, a.has_access from video_groups vg
join user_video_group_access a on vg.id = a.video_group_id and a.user_id = $1::uuid
where ($2::text is null or vg.slug = $2)
limit 1
`

type GetVideoGroupForUserBySlugParams struct {
	UserID uuid.UUID
	Slug   *string
}

type GetVideoGroupForUserBySlugRow struct {
	VideoGroup VideoGroup
	HasAccess  bool
}

func (q *Queries) GetVideoGroupForUserBySlug(ctx context.Context, arg *GetVideoGroupForUserBySlugParams) (*GetVideoGroupForUserBySlugRow, error) {
	row := q.db.QueryRow(ctx, getVideoGroupForUserBySlug, arg.UserID, arg.Slug)
	var i GetVideoGroupForUserBySlugRow
	err := row.Scan(
		&i.VideoGroup.ID,
		&i.VideoGroup.TitleEn,
		&i.VideoGroup.TitlePl,
		&i.VideoGroup.Slug,
		&i.VideoGroup.ProductID,
		&i.VideoGroup.InsertedAt,
		&i.VideoGroup.UpdatedAt,
		&i.HasAccess,
	)
	return &i, err
}

const getVideoThumbnailData = `-- name: GetVideoThumbnailData :one
select v.id, v.provider, v.is_public, v.title_en, v.title_pl, v.slug, v.inserted_at, v.updated_at, v.duration_seconds, v.recorded_on, v.host_id, v.thumbnail_en_id, v.thumbnail_pl_id, v.youtube_id, v.description_pl, v.description_en, h.given_name host_given_name, h.family_name host_family_name, a.object_key host_profile_picture_url
from videos v
left join hosts h on h.id = v.host_id
left join assets a on a.id = h.profile_picture_id
where v.id = $1::uuid
`

type GetVideoThumbnailDataRow struct {
	Video                 Video
	HostGivenName         *string
	HostFamilyName        *string
	HostProfilePictureUrl *string
}

func (q *Queries) GetVideoThumbnailData(ctx context.Context, id uuid.UUID) (*GetVideoThumbnailDataRow, error) {
	row := q.db.QueryRow(ctx, getVideoThumbnailData, id)
	var i GetVideoThumbnailDataRow
	err := row.Scan(
		&i.Video.ID,
		&i.Video.Provider,
		&i.Video.IsPublic,
		&i.Video.TitleEn,
		&i.Video.TitlePl,
		&i.Video.Slug,
		&i.Video.InsertedAt,
		&i.Video.UpdatedAt,
		&i.Video.DurationSeconds,
		&i.Video.RecordedOn,
		&i.Video.HostID,
		&i.Video.ThumbnailEnID,
		&i.Video.ThumbnailPlID,
		&i.Video.YoutubeID,
		&i.Video.DescriptionPl,
		&i.Video.DescriptionEn,
		&i.HostGivenName,
		&i.HostFamilyName,
		&i.HostProfilePictureUrl,
	)
	return &i, err
}

const insertVideo = `-- name: InsertVideo :one
insert into videos (provider, title_en, title_pl, slug, duration_seconds, recorded_on, host_id, thumbnail_en_id, thumbnail_pl_id)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
returning id, provider, is_public, title_en, title_pl, slug, inserted_at, updated_at, duration_seconds, recorded_on, host_id, thumbnail_en_id, thumbnail_pl_id, youtube_id, description_pl, description_en
`

type InsertVideoParams struct {
	Provider        VideoProvider
	TitleEn         string
	TitlePl         string
	Slug            string
	DurationSeconds *int32
	RecordedOn      *time.Time
	HostID          *uuid.UUID
	ThumbnailEnID   *uuid.UUID
	ThumbnailPlID   *uuid.UUID
}

func (q *Queries) InsertVideo(ctx context.Context, arg *InsertVideoParams) (*Video, error) {
	row := q.db.QueryRow(ctx, insertVideo,
		arg.Provider,
		arg.TitleEn,
		arg.TitlePl,
		arg.Slug,
		arg.DurationSeconds,
		arg.RecordedOn,
		arg.HostID,
		arg.ThumbnailEnID,
		arg.ThumbnailPlID,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.IsPublic,
		&i.TitleEn,
		&i.TitlePl,
		&i.Slug,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.DurationSeconds,
		&i.RecordedOn,
		&i.HostID,
		&i.ThumbnailEnID,
		&i.ThumbnailPlID,
		&i.YoutubeID,
		&i.DescriptionPl,
		&i.DescriptionEn,
	)
	return &i, err
}

const insertVideoGroup = `-- name: InsertVideoGroup :one
insert into video_groups (title_en, title_pl, slug, product_id) values ($1, $2, $3, $4) returning id, title_en, title_pl, slug, product_id, inserted_at, updated_at
`

type InsertVideoGroupParams struct {
	TitleEn   string
	TitlePl   string
	Slug      string
	ProductID *uuid.UUID
}

func (q *Queries) InsertVideoGroup(ctx context.Context, arg *InsertVideoGroupParams) (*VideoGroup, error) {
	row := q.db.QueryRow(ctx, insertVideoGroup,
		arg.TitleEn,
		arg.TitlePl,
		arg.Slug,
		arg.ProductID,
	)
	var i VideoGroup
	err := row.Scan(
		&i.ID,
		&i.TitleEn,
		&i.TitlePl,
		&i.Slug,
		&i.ProductID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listVideoGroupsForUser = `-- name: ListVideoGroupsForUser :many
select vg.id, vg.title_en, vg.title_pl, vg.slug, vg.product_id, vg.inserted_at, vg.updated_at, a.has_access from video_groups vg
join user_video_group_access a on vg.id = a.video_group_id and a.user_id = $1::uuid
order by vg.id desc
`

type ListVideoGroupsForUserRow struct {
	VideoGroup VideoGroup
	HasAccess  bool
}

func (q *Queries) ListVideoGroupsForUser(ctx context.Context, userID uuid.UUID) ([]*ListVideoGroupsForUserRow, error) {
	rows, err := q.db.Query(ctx, listVideoGroupsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListVideoGroupsForUserRow
	for rows.Next() {
		var i ListVideoGroupsForUserRow
		if err := rows.Scan(
			&i.VideoGroup.ID,
			&i.VideoGroup.TitleEn,
			&i.VideoGroup.TitlePl,
			&i.VideoGroup.Slug,
			&i.VideoGroup.ProductID,
			&i.VideoGroup.InsertedAt,
			&i.VideoGroup.UpdatedAt,
			&i.HasAccess,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideoSourcesForVideos = `-- name: ListVideoSourcesForVideos :many
select id, content_type, codec, video_id, object_key, inserted_at, updated_at, priority from video_sources vs
where vs.video_id = any($1::uuid[])
order by vs.video_id, vs.priority
`

func (q *Queries) ListVideoSourcesForVideos(ctx context.Context, videoIds []uuid.UUID) ([]*VideoSource, error) {
	rows, err := q.db.Query(ctx, listVideoSourcesForVideos, videoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*VideoSource
	for rows.Next() {
		var i VideoSource
		if err := rows.Scan(
			&i.ID,
			&i.ContentType,
			&i.Codec,
			&i.VideoID,
			&i.ObjectKey,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideos = `-- name: ListVideos :many
select v.id, v.provider, v.is_public, v.title_en, v.title_pl, v.slug, v.inserted_at, v.updated_at, v.duration_seconds, v.recorded_on, v.host_id, v.thumbnail_en_id, v.thumbnail_pl_id, v.youtube_id, v.description_pl, v.description_en from videos v
order by v.id desc
`

func (q *Queries) ListVideos(ctx context.Context) ([]*Video, error) {
	rows, err := q.db.Query(ctx, listVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.IsPublic,
			&i.TitleEn,
			&i.TitlePl,
			&i.Slug,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.DurationSeconds,
			&i.RecordedOn,
			&i.HostID,
			&i.ThumbnailEnID,
			&i.ThumbnailPlID,
			&i.YoutubeID,
			&i.DescriptionPl,
			&i.DescriptionEn,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosForVideoGroup = `-- name: ListVideosForVideoGroup :many
select v.id, v.provider, v.is_public, v.title_en, v.title_pl, v.slug, v.inserted_at, v.updated_at, v.duration_seconds, v.recorded_on, v.host_id, v.thumbnail_en_id, v.thumbnail_pl_id, v.youtube_id, v.description_pl, v.description_en from videos v
join video_groups_videos vgv on vgv.video_id = v.id
where vgv.video_group_id = $1
order by position
`

func (q *Queries) ListVideosForVideoGroup(ctx context.Context, videoGroupID uuid.UUID) ([]*Video, error) {
	rows, err := q.db.Query(ctx, listVideosForVideoGroup, videoGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.IsPublic,
			&i.TitleEn,
			&i.TitlePl,
			&i.Slug,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.DurationSeconds,
			&i.RecordedOn,
			&i.HostID,
			&i.ThumbnailEnID,
			&i.ThumbnailPlID,
			&i.YoutubeID,
			&i.DescriptionPl,
			&i.DescriptionEn,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listYoutubeVideos = `-- name: ListYoutubeVideos :many
select id, provider, is_public, title_en, title_pl, slug, inserted_at, updated_at, duration_seconds, recorded_on, host_id, thumbnail_en_id, thumbnail_pl_id, youtube_id, description_pl, description_en from videos where provider = 'youtube' order by recorded_on desc
`

func (q *Queries) ListYoutubeVideos(ctx context.Context) ([]*Video, error) {
	rows, err := q.db.Query(ctx, listYoutubeVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.IsPublic,
			&i.TitleEn,
			&i.TitlePl,
			&i.Slug,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.DurationSeconds,
			&i.RecordedOn,
			&i.HostID,
			&i.ThumbnailEnID,
			&i.ThumbnailPlID,
			&i.YoutubeID,
			&i.DescriptionPl,
			&i.DescriptionEn,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVideoGroup = `-- name: UpsertVideoGroup :one
insert into video_groups (id, title_en, title_pl, slug, product_id) values ($1, $2, $3, $4, $5)
on conflict (slug) do update set title_en = excluded.title_en, title_pl = excluded.title_pl, product_id = excluded.product_id
returning id, title_en, title_pl, slug, product_id, inserted_at, updated_at
`

type UpsertVideoGroupParams struct {
	ID        uuid.UUID
	TitleEn   string
	TitlePl   string
	Slug      string
	ProductID *uuid.UUID
}

func (q *Queries) UpsertVideoGroup(ctx context.Context, arg *UpsertVideoGroupParams) (*VideoGroup, error) {
	row := q.db.QueryRow(ctx, upsertVideoGroup,
		arg.ID,
		arg.TitleEn,
		arg.TitlePl,
		arg.Slug,
		arg.ProductID,
	)
	var i VideoGroup
	err := row.Scan(
		&i.ID,
		&i.TitleEn,
		&i.TitlePl,
		&i.Slug,
		&i.ProductID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
