// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/moroz/homeosapiens-go/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserMailer creates a new instance of MockUserMailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserMailer {
	mock := &MockUserMailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserMailer is an autogenerated mock type for the UserMailer type
type MockUserMailer struct {
	mock.Mock
}

type MockUserMailer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserMailer) EXPECT() *MockUserMailer_Expecter {
	return &MockUserMailer_Expecter{mock: &_m.Mock}
}

// SendUserEmailVerification provides a mock function for the type MockUserMailer
func (_mock *MockUserMailer) SendUserEmailVerification(context1 context.Context, userTokenDTO *types.UserTokenDTO) error {
	ret := _mock.Called(context1, userTokenDTO)

	if len(ret) == 0 {
		panic("no return value specified for SendUserEmailVerification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.UserTokenDTO) error); ok {
		r0 = returnFunc(context1, userTokenDTO)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserMailer_SendUserEmailVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendUserEmailVerification'
type MockUserMailer_SendUserEmailVerification_Call struct {
	*mock.Call
}

// SendUserEmailVerification is a helper method to define mock.On call
//   - context1 context.Context
//   - userTokenDTO *types.UserTokenDTO
func (_e *MockUserMailer_Expecter) SendUserEmailVerification(context1 interface{}, userTokenDTO interface{}) *MockUserMailer_SendUserEmailVerification_Call {
	return &MockUserMailer_SendUserEmailVerification_Call{Call: _e.mock.On("SendUserEmailVerification", context1, userTokenDTO)}
}

func (_c *MockUserMailer_SendUserEmailVerification_Call) Run(run func(context1 context.Context, userTokenDTO *types.UserTokenDTO)) *MockUserMailer_SendUserEmailVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.UserTokenDTO
		if args[1] != nil {
			arg1 = args[1].(*types.UserTokenDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserMailer_SendUserEmailVerification_Call) Return(err error) *MockUserMailer_SendUserEmailVerification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserMailer_SendUserEmailVerification_Call) RunAndReturn(run func(context1 context.Context, userTokenDTO *types.UserTokenDTO) error) *MockUserMailer_SendUserEmailVerification_Call {
	_c.Call.Return(run)
	return _c
}
