// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/moroz/homeosapiens-go/types"
	mock "github.com/stretchr/testify/mock"
	"github.com/stripe/stripe-go/v84"
)

// NewMockStripeService creates a new instance of MockStripeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStripeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStripeService {
	mock := &MockStripeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStripeService is an autogenerated mock type for the StripeService type
type MockStripeService struct {
	mock.Mock
}

type MockStripeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStripeService) EXPECT() *MockStripeService_Expecter {
	return &MockStripeService_Expecter{mock: &_m.Mock}
}

// CreateCheckoutSession provides a mock function for the type MockStripeService
func (_mock *MockStripeService) CreateCheckoutSession(context1 context.Context, orderDTO *types.OrderDTO) (*stripe.CheckoutSession, error) {
	ret := _mock.Called(context1, orderDTO)

	if len(ret) == 0 {
		panic("no return value specified for CreateCheckoutSession")
	}

	var r0 *stripe.CheckoutSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.OrderDTO) (*stripe.CheckoutSession, error)); ok {
		return returnFunc(context1, orderDTO)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.OrderDTO) *stripe.CheckoutSession); ok {
		r0 = returnFunc(context1, orderDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.CheckoutSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.OrderDTO) error); ok {
		r1 = returnFunc(context1, orderDTO)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStripeService_CreateCheckoutSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCheckoutSession'
type MockStripeService_CreateCheckoutSession_Call struct {
	*mock.Call
}

// CreateCheckoutSession is a helper method to define mock.On call
//   - context1 context.Context
//   - orderDTO *types.OrderDTO
func (_e *MockStripeService_Expecter) CreateCheckoutSession(context1 interface{}, orderDTO interface{}) *MockStripeService_CreateCheckoutSession_Call {
	return &MockStripeService_CreateCheckoutSession_Call{Call: _e.mock.On("CreateCheckoutSession", context1, orderDTO)}
}

func (_c *MockStripeService_CreateCheckoutSession_Call) Run(run func(context1 context.Context, orderDTO *types.OrderDTO)) *MockStripeService_CreateCheckoutSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.OrderDTO
		if args[1] != nil {
			arg1 = args[1].(*types.OrderDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStripeService_CreateCheckoutSession_Call) Return(checkoutSession *stripe.CheckoutSession, err error) *MockStripeService_CreateCheckoutSession_Call {
	_c.Call.Return(checkoutSession, err)
	return _c
}

func (_c *MockStripeService_CreateCheckoutSession_Call) RunAndReturn(run func(context1 context.Context, orderDTO *types.OrderDTO) (*stripe.CheckoutSession, error)) *MockStripeService_CreateCheckoutSession_Call {
	_c.Call.Return(run)
	return _c
}

// DecodeWebhook provides a mock function for the type MockStripeService
func (_mock *MockStripeService) DecodeWebhook(payload []byte, signature string) (any, error) {
	ret := _mock.Called(payload, signature)

	if len(ret) == 0 {
		panic("no return value specified for DecodeWebhook")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, string) (any, error)); ok {
		return returnFunc(payload, signature)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, string) any); ok {
		r0 = returnFunc(payload, signature)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, string) error); ok {
		r1 = returnFunc(payload, signature)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStripeService_DecodeWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeWebhook'
type MockStripeService_DecodeWebhook_Call struct {
	*mock.Call
}

// DecodeWebhook is a helper method to define mock.On call
//   - payload []byte
//   - signature string
func (_e *MockStripeService_Expecter) DecodeWebhook(payload interface{}, signature interface{}) *MockStripeService_DecodeWebhook_Call {
	return &MockStripeService_DecodeWebhook_Call{Call: _e.mock.On("DecodeWebhook", payload, signature)}
}

func (_c *MockStripeService_DecodeWebhook_Call) Run(run func(payload []byte, signature string)) *MockStripeService_DecodeWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStripeService_DecodeWebhook_Call) Return(v any, err error) *MockStripeService_DecodeWebhook_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockStripeService_DecodeWebhook_Call) RunAndReturn(run func(payload []byte, signature string) (any, error)) *MockStripeService_DecodeWebhook_Call {
	_c.Call.Return(run)
	return _c
}
