// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/moroz/homeosapiens-go/db/queries"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEmailVerificationService creates a new instance of MockEmailVerificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailVerificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailVerificationService {
	mock := &MockEmailVerificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailVerificationService is an autogenerated mock type for the EmailVerificationService type
type MockEmailVerificationService struct {
	mock.Mock
}

type MockEmailVerificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailVerificationService) EXPECT() *MockEmailVerificationService_Expecter {
	return &MockEmailVerificationService_Expecter{mock: &_m.Mock}
}

// MaybeResendVerificationEmail provides a mock function for the type MockEmailVerificationService
func (_mock *MockEmailVerificationService) MaybeResendVerificationEmail(ctx context.Context, email string) (bool, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for MaybeResendVerificationEmail")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailVerificationService_MaybeResendVerificationEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaybeResendVerificationEmail'
type MockEmailVerificationService_MaybeResendVerificationEmail_Call struct {
	*mock.Call
}

// MaybeResendVerificationEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockEmailVerificationService_Expecter) MaybeResendVerificationEmail(ctx interface{}, email interface{}) *MockEmailVerificationService_MaybeResendVerificationEmail_Call {
	return &MockEmailVerificationService_MaybeResendVerificationEmail_Call{Call: _e.mock.On("MaybeResendVerificationEmail", ctx, email)}
}

func (_c *MockEmailVerificationService_MaybeResendVerificationEmail_Call) Run(run func(ctx context.Context, email string)) *MockEmailVerificationService_MaybeResendVerificationEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailVerificationService_MaybeResendVerificationEmail_Call) Return(sent bool, err error) *MockEmailVerificationService_MaybeResendVerificationEmail_Call {
	_c.Call.Return(sent, err)
	return _c
}

func (_c *MockEmailVerificationService_MaybeResendVerificationEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (bool, error)) *MockEmailVerificationService_MaybeResendVerificationEmail_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmailAddress provides a mock function for the type MockEmailVerificationService
func (_mock *MockEmailVerificationService) VerifyEmailAddress(ctx context.Context, token string) (*queries.User, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmailAddress")
	}

	var r0 *queries.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*queries.User, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *queries.User); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*queries.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailVerificationService_VerifyEmailAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmailAddress'
type MockEmailVerificationService_VerifyEmailAddress_Call struct {
	*mock.Call
}

// VerifyEmailAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockEmailVerificationService_Expecter) VerifyEmailAddress(ctx interface{}, token interface{}) *MockEmailVerificationService_VerifyEmailAddress_Call {
	return &MockEmailVerificationService_VerifyEmailAddress_Call{Call: _e.mock.On("VerifyEmailAddress", ctx, token)}
}

func (_c *MockEmailVerificationService_VerifyEmailAddress_Call) Run(run func(ctx context.Context, token string)) *MockEmailVerificationService_VerifyEmailAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailVerificationService_VerifyEmailAddress_Call) Return(user *queries.User, err error) *MockEmailVerificationService_VerifyEmailAddress_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockEmailVerificationService_VerifyEmailAddress_Call) RunAndReturn(run func(ctx context.Context, token string) (*queries.User, error)) *MockEmailVerificationService_VerifyEmailAddress_Call {
	_c.Call.Return(run)
	return _c
}
